// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** One Level II product in the queue. */
export interface RadarQueueProduct {
  /** Always `wx:RadarQueue`. */
  '@type': 'wx:RadarQueue'
  /** The distribution host. */
  host: 'rds' | 'tds'
  /** When the product arrived at the host. */
  arrivalTime: TimestampIso
  /** When the radar created it. */
  creationTime: TimestampIso
  /** The radar, such as `KATX`. */
  stationId: string
  /** Part of the Level II volume this is: `start`, `intermediate`, `end` or `model` on 2026-10-01. Undocumented, so not enumerated. */
  type: string
  /** Feed it came on, such as `NEXRAD2`. */
  feed: string
  /** Resolution version, such as `6`. */
  resolutionVersion: number
  /** Volume and chunk sequence, such as `490-050`. */
  sequenceNumber: string
  /** Size of the product, in bytes. */
  size: number
}

export const RadarQueueProduct: Codec<RadarQueueProduct> = t.object({
  '@type': t.literal('wx:RadarQueue'),
  host: t.literal('rds', 'tds'),
  arrivalTime: t.dateTime,
  creationTime: t.dateTime,
  stationId: t.string,
  type: t.string,
  feed: t.string,
  resolutionVersion: t.integer,
  sequenceNumber: t.string,
  size: t.integer,
})

/** Which host, and which products. Every filter is optional. */
export interface Request {
  /** Distribution host: `rds` or `tds`. */
  host: 'rds' | 'tds'
  /** Most products to return, 1 to 50,000. Without it, 500. */
  limit?: number
  /** Only products that arrived in this ISO 8601 interval: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT10M`. The answer starts at the interval's start, so a `limit` keeps the oldest. Without it, about the last two minutes. The service keeps about a week. */
  arrived?: string
  /** Only products the radar created in this ISO 8601 interval, in the same forms as `arrived`. Every request with it answered 503 on 2026-10-01 (`An upstream data source is temporarily unavailable`). */
  created?: string
  /** Only products published in this ISO 8601 interval, in the same forms as `arrived`. */
  published?: string
  /** Only this radar's products, such as `KATX`. An unknown one answers an empty `@graph`. */
  station?: string
  /** Only this kind of product. Undocumented; `start`, `intermediate`, `end` and `model` on 2026-10-01, which are the parts of a Level II volume. */
  type?: string
  /** Only products from this feed, such as `NEXRAD2`. */
  feed?: string
  /** Only products of this resolution version, such as `6` or `8`. */
  resolution?: number
}

export const Request: Codec<Request> = t.object({
  host: t.literal('rds', 'tds'),
  limit: t.optional(t.integer),
  arrived: t.optional(t.string),
  created: t.optional(t.string),
  published: t.optional(t.string),
  station: t.optional(t.string),
  type: t.optional(t.string),
  feed: t.optional(t.string),
  resolution: t.optional(t.integer),
})

/** The products, as a JSON-LD graph. */
export interface RadarQueue {
  /** URL of this queue. */
  '@id'?: string
  /** The products, by arrival. */
  '@graph': RadarQueueProduct[]
}

export const RadarQueue: Codec<RadarQueue> = t.object({
  '@id': t.optional(t.string),
  '@graph': t.array(RadarQueueProduct),
})

/** The Level II products that passed through one distribution host's LDM queue, oldest first from the start of the interval. JSON-LD: the products come as a `@graph`. */
export class GetQueue {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getQueue(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The Level II products that passed through one distribution host's LDM queue, oldest first from the start of the interval. JSON-LD: the products come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_queue
   */
  getQueue(request: Request, options?: CallOptions): Promise<RadarQueue>
  async getQueue(request: Request, options?: CallOptions): Promise<RadarQueue> {
    return this.core.request({
      method: 'GET',
      path: '/radar/queues/{host}',
      request,
      requestCodec: Request,
      responseCodec: RadarQueue,
      meta: {},
      ...options,
    })
  }
}
