// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { RadarStationFeature } from '../types/index.js'

/** Which radar. */
export interface Request {
  /** Station identifier, such as `KATX`. `radar.list_stations` returns it as `properties.id`. */
  station_id: string
  /** Monitoring host to report status and latency from. `rdss` is the only one the service knew on 2026-10-01. */
  reportingHost?: string
  /** LDM host to measure `latency` at, such as `ldm1`. Without it, `ldm4` on 2026-10-01; a host the service does not know answers a `latency` of nulls. */
  host?: string
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
  reportingHost: t.optional(t.string),
  host: t.optional(t.string),
})

/** One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports. */
export class GetStation {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getStation(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_station
   */
  getStation(request: Request, options?: CallOptions): Promise<RadarStationFeature>
  async getStation(request: Request, options?: CallOptions): Promise<RadarStationFeature> {
    return this.core.request({
      method: 'GET',
      path: '/radar/stations/{station_id}',
      request,
      requestCodec: Request,
      responseCodec: RadarStationFeature,
      meta: {},
      ...options,
    })
  }
}
