// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

export type RadarProfiler = unknown

export const RadarProfiler: Codec<RadarProfiler> = t.unknown

/** Which profiler, and over what time. */
export interface Request {
  /** Profiler station identifier, such as `TLKA2`. `radar.list_stations` with a `station_type` of `Profiler` lists them. */
  station_id: string
  /** Time interval, in ISO 8601: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT1H`. */
  time?: string
  /** Averaging interval, as an ISO 8601 duration such as `PT1H`. */
  interval?: string
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
  time: t.optional(t.string),
  interval: t.optional(t.string),
})

/** Metadata about one radar wind profiler, as JSON-LD. Unverified: every profiler answered 404 on 2026-10-01, so the response is not described. */
export class GetProfiler {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getProfiler(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Metadata about one radar wind profiler, as JSON-LD. Unverified: every profiler answered 404 on 2026-10-01, so the response is not described.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_profiler
   */
  getProfiler(request: Request, options?: CallOptions): Promise<RadarProfiler>
  async getProfiler(request: Request, options?: CallOptions): Promise<RadarProfiler> {
    return this.core.request({
      method: 'GET',
      path: '/radar/profilers/{station_id}',
      request,
      requestCodec: Request,
      responseCodec: RadarProfiler,
      meta: {},
      ...options,
    })
  }
}
