// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { RadarServer } from '../types/index.js'

/** Which server. */
export interface Request {
  /** Server name, such as `ldm1`. `radar.list_servers` returns it as `id`. */
  server_id: string
  /** Monitoring host to report from. `rdss` is the only one the service knew on 2026-10-01; any other value answers 404. */
  reportingHost?: string
}

export const Request: Codec<Request> = t.object({
  server_id: t.string,
  reportingHost: t.optional(t.string),
})

/** One server of the radar data distribution network, and its health. */
export class GetServer {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getServer(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One server of the radar data distribution network, and its health.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_server
   */
  getServer(request: Request, options?: CallOptions): Promise<RadarServer>
  async getServer(request: Request, options?: CallOptions): Promise<RadarServer> {
    return this.core.request({
      method: 'GET',
      path: '/radar/servers/{server_id}',
      request,
      requestCodec: Request,
      responseCodec: RadarServer,
      meta: {},
      ...options,
    })
  }
}
