// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { RadarServer, RadarStationFeature } from '../types/index.js'
import * as getQueue from './get_queue.js'
import * as getServer from './get_server.js'
import * as getStation from './get_station.js'
import * as listServers from './list_servers.js'
import * as listSpgds from './list_spgds.js'
import * as listStationAlarms from './list_station_alarms.js'
import * as listStations from './list_stations.js'

/**
 * The radar network: the NEXRAD, TDWR and profiler radars, their status and alarms, and the servers and queues that distribute their Level II data.
 *
 * @see https://www.weather.gov/documentation/services-web-api#/default/radar_stations
 */
export class Radar {
  private readonly getQueue_: getQueue.GetQueue
  private readonly getServer_: getServer.GetServer
  private readonly getStation_: getStation.GetStation
  private readonly listServers_: listServers.ListServers
  private readonly listSpgds_: listSpgds.ListSpgds
  private readonly listStationAlarms_: listStationAlarms.ListStationAlarms
  private readonly listStations_: listStations.ListStations

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getQueue_ = new getQueue.GetQueue(core)
    this.getServer_ = new getServer.GetServer(core)
    this.getStation_ = new getStation.GetStation(core)
    this.listServers_ = new listServers.ListServers(core)
    this.listSpgds_ = new listSpgds.ListSpgds(core)
    this.listStationAlarms_ = new listStationAlarms.ListStationAlarms(core)
    this.listStations_ = new listStations.ListStations(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getQueue(request: getQueue.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The Level II products that passed through one distribution host's LDM queue, oldest first from the start of the interval. JSON-LD: the products come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_queue
   */
  getQueue(request: getQueue.Request, options?: CallOptions): Promise<getQueue.RadarQueue>
  getQueue(request: getQueue.Request, options?: CallOptions): Promise<getQueue.RadarQueue> {
    return this.getQueue_.getQueue(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getServer(request: getServer.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One server of the radar data distribution network, and its health.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_server
   */
  getServer(request: getServer.Request, options?: CallOptions): Promise<RadarServer>
  getServer(request: getServer.Request, options?: CallOptions): Promise<RadarServer> {
    return this.getServer_.getServer(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getStation(request: getStation.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_station
   */
  getStation(request: getStation.Request, options?: CallOptions): Promise<RadarStationFeature>
  getStation(request: getStation.Request, options?: CallOptions): Promise<RadarStationFeature> {
    return this.getStation_.getStation(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listServers(request: listServers.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The servers of the radar data distribution network -- the LDM servers that ingest NEXRAD data and the hosts that serve it on -- each with its health. JSON-LD: the servers come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_servers
   */
  listServers(request?: listServers.Request, options?: CallOptions): Promise<listServers.RadarServerCollection>
  listServers(request?: listServers.Request, options?: CallOptions): Promise<listServers.RadarServerCollection> {
    return this.listServers_.listServers(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listSpgds(request: listSpgds.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Status reports from the SPG data servers, which feed radar data to the Supplemental Product Generators at airport TDWR sites. JSON-LD: the reports come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_spgds
   */
  listSpgds(request?: listSpgds.Request, options?: CallOptions): Promise<listSpgds.SpgdsCollection>
  listSpgds(request?: listSpgds.Request, options?: CallOptions): Promise<listSpgds.SpgdsCollection> {
    return this.listSpgds_.listSpgds(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listStationAlarms(request: listStationAlarms.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alarm log of one radar: each alarm the radar raised or cleared, newest first. JSON-LD: the alarms come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_station_alarms
   */
  listStationAlarms(request: listStationAlarms.Request, options?: CallOptions): Promise<listStationAlarms.RadarAlarmCollection>
  listStationAlarms(request: listStationAlarms.Request, options?: CallOptions): Promise<listStationAlarms.RadarAlarmCollection> {
    return this.listStationAlarms_.listStationAlarms(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listStations(request: listStations.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every radar the service tracks -- NEXRAD (WSR-88D), terminal Doppler (TDWR) and wind profilers -- each with its data latency and status.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_stations
   */
  listStations(request?: listStations.Request, options?: CallOptions): Promise<listStations.RadarStationCollection>
  listStations(request?: listStations.Request, options?: CallOptions): Promise<listStations.RadarStationCollection> {
    return this.listStations_.listStations(request, options)
  }
}
