// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { RadarStationFeature } from '../types/index.js'

/** Which radars. Every filter is optional. Give one value to `stationType`: the service reads several only comma-separated, and this client sends them as repeated keys, of which the service keeps the last. */
export interface Request {
  /** Kinds of radar to narrow to: `WSR-88D`, `TDWR` or `Profiler`, matched case-sensitively (`tdwr` answers an empty list). Undocumented, so not enumerated. */
  stationType?: string[]
  /** Monitoring host to report status and latency from: `rdss` or `tdss` on 2026-10-01. Without it, the service picks one; any other value answers 503. */
  reportingHost?: string
  /** LDM host to measure `latency` at, such as `ldm1`. Without it, `ldm4` on 2026-10-01; a host the service does not know answers 503. */
  host?: string
}

export const Request: Codec<Request> = t.object({
  stationType: t.optional(t.array(t.string)),
  reportingHost: t.optional(t.string),
  host: t.optional(t.string),
})

/** The radars, as a GeoJSON feature collection. */
export interface RadarStationCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The radars. */
  features: RadarStationFeature[]
}

export const RadarStationCollection: Codec<RadarStationCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(RadarStationFeature),
})

/** Every radar the service tracks -- NEXRAD (WSR-88D), terminal Doppler (TDWR) and wind profilers -- each with its data latency and status. */
export class ListStations {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listStations(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every radar the service tracks -- NEXRAD (WSR-88D), terminal Doppler (TDWR) and wind profilers -- each with its data latency and status.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_stations
   */
  listStations(request?: Request, options?: CallOptions): Promise<RadarStationCollection>
  async listStations(request?: Request, options?: CallOptions): Promise<RadarStationCollection> {
    return this.core.request({
      method: 'GET',
      path: '/radar/stations',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: RadarStationCollection,
      meta: {},
      ...options,
    })
  }
}
