// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { RadarServer } from '../types/index.js'

/** Which servers. The filter is optional. */
export interface Request {
  /** Monitoring host to report from. `rdss` is the only one the service knew on 2026-10-01; any other value answers an empty list. */
  reportingHost?: string
}

export const Request: Codec<Request> = t.object({
  reportingHost: t.optional(t.string),
})

/** The servers, as a JSON-LD graph. */
export interface RadarServerCollection {
  /** The servers. */
  '@graph': RadarServer[]
}

export const RadarServerCollection: Codec<RadarServerCollection> = t.object({
  '@graph': t.array(RadarServer),
})

/** The servers of the radar data distribution network -- the LDM servers that ingest NEXRAD data and the hosts that serve it on -- each with its health. JSON-LD: the servers come as a `@graph`. */
export class ListServers {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listServers(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The servers of the radar data distribution network -- the LDM servers that ingest NEXRAD data and the hosts that serve it on -- each with its health. JSON-LD: the servers come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_servers
   */
  listServers(request?: Request, options?: CallOptions): Promise<RadarServerCollection>
  async listServers(request?: Request, options?: CallOptions): Promise<RadarServerCollection> {
    return this.core.request({
      method: 'GET',
      path: '/radar/servers',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: RadarServerCollection,
      meta: {},
      ...options,
    })
  }
}
