// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** One alarm message. */
export interface RadarAlarm {
  /** Always `wx:RadarStationAlarm`. */
  '@type': 'wx:RadarStationAlarm'
  /** The radar, such as `KATX`. */
  stationId: string
  /** Alarm class. Undocumented, so not enumerated; on 2026-10-01 the 208 radars' logs held `cleared`, `required`, `secondary`, `mandatory` and `inoperative`. */
  status: string
  /** Redundant channel the alarm came from: `0`, `1` or `2` on 2026-10-01. */
  activeChannel: number
  /** The alarm text, such as `RPG LINK INITIALIZATION ERROR`. */
  message: string
  /** When the alarm was raised or cleared. */
  timestamp: TimestampIso
}

export const RadarAlarm: Codec<RadarAlarm> = t.object({
  '@type': t.literal('wx:RadarStationAlarm'),
  stationId: t.string,
  status: t.string,
  activeChannel: t.integer,
  message: t.string,
  timestamp: t.dateTime,
})

/** Which radar. */
export interface Request {
  /** Station identifier, such as `KATX`. A profiler, or any radar with no log, answers an empty `@graph`. */
  station_id: string
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
})

/** The alarms, as a JSON-LD graph. */
export interface RadarAlarmCollection {
  /** URL of this alarm log. */
  '@id'?: string
  /** The alarms, newest first. */
  '@graph': RadarAlarm[]
}

export const RadarAlarmCollection: Codec<RadarAlarmCollection> = t.object({
  '@id': t.optional(t.string),
  '@graph': t.array(RadarAlarm),
})

/** The alarm log of one radar: each alarm the radar raised or cleared, newest first. JSON-LD: the alarms come as a `@graph`. */
export class ListStationAlarms {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listStationAlarms(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alarm log of one radar: each alarm the radar raised or cleared, newest first. JSON-LD: the alarms come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_station_alarms
   */
  listStationAlarms(request: Request, options?: CallOptions): Promise<RadarAlarmCollection>
  async listStationAlarms(request: Request, options?: CallOptions): Promise<RadarAlarmCollection> {
    return this.core.request({
      method: 'GET',
      path: '/radar/stations/{station_id}/alarms',
      request,
      requestCodec: Request,
      responseCodec: RadarAlarmCollection,
      meta: {},
      ...options,
    })
  }
}
