// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type Decimal, type HttpEndpoint, type TimestampIso, type TimestampSeconds, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Which reports. Without `published`, the latest two from each server. */
export interface Request {
  /** Only reports made in this ISO 8601 interval: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T12:00:00Z/PT1M`. The service keeps about a week; each server reports about every 15 seconds, so an hour is about 1,000 reports and 4 MB. */
  published?: string
}

export const Request: Codec<Request> = t.object({
  published: t.optional(t.string),
})

/** The feeds to one SPG site. */
export interface SpgSite {
  /** State of the SWIM data feed: `1` up, `0` down. Undocumented, so not enumerated. */
  swimDataState: string
  /** When that state began, in Unix seconds sent as a string. */
  swimDataStateSince: TimestampSeconds
  /** When it was last confirmed, in Unix seconds sent as a string. */
  swimDataStateValid: TimestampSeconds
  /** Whether the site answers an LDM ping: `1` yes, `0` no. Undocumented, so not enumerated. */
  ldmPingState: string
  /** When that state began, in Unix seconds sent as a string. */
  ldmPingStateSince: TimestampSeconds
  /** When it was last confirmed, in Unix seconds sent as a string. */
  ldmPingStateValid: TimestampSeconds
}

export const SpgSite: Codec<SpgSite> = t.object({
  swimDataState: t.string,
  swimDataStateSince: t.epochSeconds,
  swimDataStateValid: t.epochSeconds,
  ldmPingState: t.string,
  ldmPingStateSince: t.epochSeconds,
  ldmPingStateValid: t.epochSeconds,
})

/** Whether the server application is running. */
export interface SpgdsApplication {
  /** State code: `1` on a healthy server. Undocumented, so not enumerated. */
  state: string
  /** When the state began, in Unix seconds sent as a string. */
  stateSince: TimestampSeconds
  /** When the state was last confirmed, in Unix seconds sent as a string. */
  stateValid: TimestampSeconds
}

export const SpgdsApplication: Codec<SpgdsApplication> = t.object({
  state: t.string,
  stateSince: t.epochSeconds,
  stateValid: t.epochSeconds,
})

/** State of the connection queue. */
export interface SpgdsConnectQueue {
  /** State code: `1` on a healthy server. Undocumented, so not enumerated. */
  state: string
  /** When the state began, in Unix seconds sent as a string. */
  stateSince: TimestampSeconds
  /** When the state was last confirmed, in Unix seconds sent as a string. */
  stateValid: TimestampSeconds
}

export const SpgdsConnectQueue: Codec<SpgdsConnectQueue> = t.object({
  state: t.string,
  stateSince: t.epochSeconds,
  stateValid: t.epochSeconds,
})

/** Whether data is flowing through the server. */
export interface SpgdsDataflow {
  /** State code: `1` on a healthy server. Undocumented, so not enumerated. */
  state: string
  /** When the state began, in Unix seconds sent as a string. */
  stateSince: TimestampSeconds
  /** When the state was last confirmed, in Unix seconds sent as a string. */
  stateValid: TimestampSeconds
}

export const SpgdsDataflow: Codec<SpgdsDataflow> = t.object({
  state: t.string,
  stateSince: t.epochSeconds,
  stateValid: t.epochSeconds,
})

/** The server's LDM connections. */
export interface SpgdsLdm {
  /** Open LDM connections, sent as a string. */
  conns: bigint
  /** When the count was last confirmed, in Unix seconds sent as a string. */
  connsValid: TimestampSeconds
}

export const SpgdsLdm: Codec<SpgdsLdm> = t.object({
  conns: t.integerString,
  connsValid: t.epochSeconds,
})

/** The server's second disk. */
export interface SpgdsSecondDisk {
  /** State code: `1` on a healthy disk. Undocumented, so not enumerated. */
  state: string
  /** When the state began, in Unix seconds sent as a string. */
  stateSince: TimestampSeconds
  /** When the state was last confirmed, in Unix seconds sent as a string. */
  stateValid: TimestampSeconds
  /** Disk used, in percent, sent as a string. */
  pctUsed: bigint
  /** When the usage was last confirmed, in Unix seconds sent as a string. */
  pctUsedValid: TimestampSeconds
}

export const SpgdsSecondDisk: Codec<SpgdsSecondDisk> = t.object({
  state: t.string,
  stateSince: t.epochSeconds,
  stateValid: t.epochSeconds,
  pctUsed: t.integerString,
  pctUsedValid: t.epochSeconds,
})

/** Data rates through the server. */
export interface SpgdsThroughput {
  /** Inbound rate, sent as a decimal string. The unit is undocumented. */
  in: Decimal
  /** When the inbound rate was measured, in Unix seconds sent as a string. */
  inDateTime: TimestampSeconds
  /** When it was last confirmed, in Unix seconds sent as a string. */
  inValid: TimestampSeconds
  /** Outbound rate, sent as a decimal string. The unit is undocumented. */
  out: Decimal
  /** When the outbound rate was measured, in Unix seconds sent as a string. */
  outDateTime: TimestampSeconds
  /** When it was last confirmed, in Unix seconds sent as a string. */
  outValid: TimestampSeconds
}

export const SpgdsThroughput: Codec<SpgdsThroughput> = t.object({
  in: t.decimal,
  inDateTime: t.epochSeconds,
  inValid: t.epochSeconds,
  out: t.decimal,
  outDateTime: t.epochSeconds,
  outValid: t.epochSeconds,
})

/** How long the server has been up. */
export interface SpgdsUptime {
  /** When it came up, in Unix seconds sent as a string. */
  upSince: TimestampSeconds
  /** When that was last confirmed, in Unix seconds sent as a string. */
  upSinceValid: TimestampSeconds
}

export const SpgdsUptime: Codec<SpgdsUptime> = t.object({
  upSince: t.epochSeconds,
  upSinceValid: t.epochSeconds,
})

/** One status report from one SPG data server. */
export interface RadarSpgds {
  /** Always `wx:RadarSPGDS`. */
  '@type': 'wx:RadarSPGDS'
  /** Server name, such as `spgds1`. */
  id: string
  /** When the report was made. */
  timestamp: TimestampIso
  dataflow: SpgdsDataflow
  connectQ: SpgdsConnectQueue
  appRunning: SpgdsApplication
  ldm: SpgdsLdm
  secondHD: SpgdsSecondDisk
  spgdsUpSince: SpgdsUptime
  throughput: SpgdsThroughput
  /** Each Supplemental Product Generator the server feeds, by site identifier (`TATL`, `TBOS`): 46 per server on 2026-10-01. */
  spg: Record<string, SpgSite>
}

export const RadarSpgds: Codec<RadarSpgds> = t.object({
  '@type': t.literal('wx:RadarSPGDS'),
  id: t.string,
  timestamp: t.dateTime,
  dataflow: SpgdsDataflow,
  connectQ: SpgdsConnectQueue,
  appRunning: SpgdsApplication,
  ldm: SpgdsLdm,
  secondHD: SpgdsSecondDisk,
  spgdsUpSince: SpgdsUptime,
  throughput: SpgdsThroughput,
  spg: t.record(SpgSite),
})

/** The reports, as a JSON-LD graph. */
export interface SpgdsCollection {
  /** The reports, newest first. Empty when nothing was published in the interval. */
  '@graph': RadarSpgds[]
}

export const SpgdsCollection: Codec<SpgdsCollection> = t.object({
  '@graph': t.array(RadarSpgds),
})

/** Status reports from the SPG data servers, which feed radar data to the Supplemental Product Generators at airport TDWR sites. JSON-LD: the reports come as a `@graph`. */
export class ListSpgds {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listSpgds(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Status reports from the SPG data servers, which feed radar data to the Supplemental Product Generators at airport TDWR sites. JSON-LD: the reports come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/radar_spgds
   */
  listSpgds(request?: Request, options?: CallOptions): Promise<SpgdsCollection>
  async listSpgds(request?: Request, options?: CallOptions): Promise<SpgdsCollection> {
    return this.core.request({
      method: 'GET',
      path: '/radar/spgds',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: SpgdsCollection,
      meta: {},
      ...options,
    })
  }
}
