// Generated by truewire — do not edit by hand.
import type { HttpEndpoint } from '@truewire/core'
import { Alerts } from './alerts/index.js'
import { Forecast } from './forecast/index.js'
import type { DefaultMeta } from './meta.js'
import { Offices } from './offices/index.js'
import { Points } from './points/index.js'
import { Products } from './products/index.js'
import { Stations } from './stations/index.js'

/**
 * The United States National Weather Service API (`api.weather.gov`): forecasts, observations, active alerts and the offices and stations behind them. No credentials -- the service asks only that a caller identify itself in `User-Agent`.
 *
 * @see https://www.weather.gov/documentation/services-web-api
 */
export class Weather {
  /** Watches, warnings and advisories in effect. */
  readonly alerts: Alerts
  /** Forecasts for one grid cell: the twice-daily narrative, the hourly series, and the raw gridded data both are rendered from. */
  readonly forecast: Forecast
  /** The weather forecast offices that issue everything else here. */
  readonly offices: Offices
  /** Turning a latitude/longitude into the grid the rest of the API is addressed by. */
  readonly points: Points
  /** The text products the service publishes, by type. */
  readonly products: Products
  /** Observation stations and what they have reported. */
  readonly stations: Stations

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.alerts = new Alerts(core)
    this.forecast = new Forecast(core)
    this.offices = new Offices(core)
    this.points = new Points(core)
    this.products = new Products(core)
    this.stations = new Stations(core)
  }
}
