// Generated by truewire — do not edit by hand.
import { LogicError } from '@truewire/core'

/** `[policy].rate`: requests per second the core's `HttpClient` paces to; `undefined` for none. */
export const RATE: number | undefined = undefined
/** `[policy].retry`: whether the core's `HttpClient` retries on its own. */
export const RETRY: boolean = false

/** A call to an endpoint `[policy].refuse` names (W15); thrown before any request is made. */
export class RefusedByPolicy extends LogicError {
  // No `name` of its own: `isTruewireError` recognises a runtime error that crossed a
  // duplicated `@truewire/core` bundle by the runtime's class names, `LogicError` among them.

  /** @param endpoint The refused endpoint's function path (`account.withdraw`). */
  constructor(readonly endpoint: string) {
    super(`${endpoint} is refused by [policy].refuse; no request was made`)
  }
}

/** Throws `RefusedByPolicy`: the first statement of every call a refused endpoint makes. */
export function refuse(endpoint: string): void {
  throw new RefusedByPolicy(endpoint)
}
