//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::Product;

/// Which type, from where.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Three-letter product type, such as `AFD`. `products.list_product_types` names every code.
    pub type_id: String,
    /// Issuance location, such as `SEW` for Seattle. `products.list_locations` names every id; `products.list_locations_for_type` narrows them to one type.
    pub location_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The newest product of one type from one location, with its text.
#[derive(Clone)]
pub struct GetLatestProduct {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetLatestProduct {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The newest product of one type from one location, with its text.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/latest_product_type_location>.
    pub async fn get_latest_product(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<Product> {
        let raw = self.get_latest_product_raw(request, options).await?;
        decode(raw)
    }

    /// `get_latest_product` without validation: the wire body as it came.
    pub async fn get_latest_product_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/products/types/{type_id}/locations/{location_id}/latest",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
