//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::ProductCollection;

/// Which type.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Three-letter product type, such as `AFD`. `products.list_product_types` names every code.
    pub type_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Every product of one type the service still holds, newest first. Header fields only.
#[derive(Clone)]
pub struct ListProductsByType {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListProductsByType {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Every product of one type the service still holds, newest first. Header fields only.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/products_type>.
    pub async fn list_products_by_type(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ProductCollection> {
        let raw = self.list_products_by_type_raw(request, options).await?;
        decode(raw)
    }

    /// `list_products_by_type` without validation: the wire body as it came.
    pub async fn list_products_by_type_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/products/types/{type_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
