//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::ProductTypeCollection;

/// Which location.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Issuance location, such as `SEW` for Seattle. `products.list_locations` names every id; `products.list_locations_for_type` narrows them to one type.
    pub location_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The product types one location issues.
#[derive(Clone)]
pub struct ListTypesForLocation {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListTypesForLocation {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The product types one location issues.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/location_products>.
    pub async fn list_types_for_location(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ProductTypeCollection> {
        let raw = self.list_types_for_location_raw(request, options).await?;
        decode(raw)
    }

    /// `list_types_for_location` without validation: the wire body as it came.
    pub async fn list_types_for_location_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/products/locations/{location_id}/types",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
