//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::DefaultMeta;
use crate::types::ZoneKind;

/// One period: a named half-day.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ZoneForecastPeriod {
    /// Sequence number within the forecast, starting at 1.
    pub number: i64,
    /// Name of the period, such as `Tonight` or `Wednesday Night`.
    pub name: String,
    /// The forecaster's text for the period.
    #[serde(rename = "detailedForecast")]
    pub detailed_forecast: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Which zone.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// Public zone code, such as `WAZ315`.
    pub zone_id: String,
    /// The zone type. Only public zones have one, addressed as `forecast`, `public` or `land`; a county, fire or marine zone answers 404.
    pub zone_type: ZoneKind,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The forecast itself.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ZoneForecast {
    /// URL of the zone the forecast is for.
    pub zone: String,
    /// When the forecaster issued it.
    pub updated: TimestampIso,
    /// The forecast periods, in order.
    pub periods: Vec<ZoneForecastPeriod>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The text forecast for a public forecast zone: the forecaster's narrative, period by period, for the week ahead. Coarser than `forecast.get_forecast`, which renders one grid cell; this is what is read on NOAA Weather Radio for the whole zone.
#[derive(Clone)]
pub struct GetForecast {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetForecast {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The text forecast for a public forecast zone: the forecaster's narrative, period by period, for the week ahead. Coarser than `forecast.get_forecast`, which renders one grid cell; this is what is read on NOAA Weather Radio for the whole zone.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone_forecast>.
    pub async fn get_forecast(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ZoneForecast> {
        let raw = self.get_forecast_raw(request, options).await?;
        decode(raw)
    }

    /// `get_forecast` without validation: the wire body as it came.
    pub async fn get_forecast_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            payload: Some("properties".to_string()),
        };
        let call = HttpCall {
            method: Some("GET"),
            path: "/zones/{zone_type}/{zone_id}/forecast",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
