//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso};

use crate::meta::DefaultMeta;

use crate::types::{ZoneFeature, ZoneKind};

/// Which zone, and as of when.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// Zone code, such as `WAZ315`. `points.get_point` returns the forecast, county and fire-weather zones of a place as URLs ending in one.
    pub zone_id: String,
    /// The zone type. Any of them finds a zone of another type too (`/zones/forecast/PZZ135` answers the coastal zone), but the code decides what comes back.
    pub zone_type: ZoneKind,
    /// Answer as the zone stood at this time rather than now. Before the zone took effect the service answers 404.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new(zone_id: String, zone_type: ZoneKind) -> Self {
        Self {
            zone_id,
            zone_type,
            effective: None,
            extra: Default::default(),
        }
    }
}

/// One zone, with its outline. The outline is most of what a zone is, so the client hands back the whole GeoJSON feature: `geometry` is the area, `properties` the rest.
#[derive(Clone)]
pub struct GetZone {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetZone {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One zone, with its outline. The outline is most of what a zone is, so the client hands back the whole GeoJSON feature: `geometry` is the area, `properties` the rest.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone>.
    pub async fn get_zone(&self, request: Request, options: CallOptions) -> Result<ZoneFeature> {
        let raw = self.get_zone_raw(request, options).await?;
        decode(raw)
    }

    /// `get_zone` without validation: the wire body as it came.
    pub async fn get_zone_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/zones/{zone_type}/{zone_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
