//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::DefaultMeta;
use crate::types::ZoneCollection;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestZoneType {
    #[serde(rename = "land")]
    Land,
    #[serde(rename = "marine")]
    Marine,
    #[serde(rename = "forecast")]
    Forecast,
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "coastal")]
    Coastal,
    #[serde(rename = "offshore")]
    Offshore,
    #[serde(rename = "fire")]
    Fire,
    #[serde(rename = "county")]
    County,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestRegionItem {
    #[serde(rename = "AR")]
    Ar,
    #[serde(rename = "CR")]
    Cr,
    #[serde(rename = "ER")]
    Er,
    #[serde(rename = "PR")]
    Pr,
    #[serde(rename = "SR")]
    Sr,
    #[serde(rename = "WR")]
    Wr,
    #[serde(rename = "AL")]
    Al,
    #[serde(rename = "AT")]
    At,
    #[serde(rename = "GL")]
    Gl,
    #[serde(rename = "GM")]
    Gm,
    #[serde(rename = "PA")]
    Pa,
    #[serde(rename = "PI")]
    Pi,
}

/// Which type, and which of its zones. Give one value per array filter: the service reads several only comma-separated, and this client sends them as repeated keys, of which the service keeps the last.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// The zone type. The service answers with five of these: `public` (what `forecast` and `land` also address), `county`, `fire`, `coastal` and `offshore` (what `marine` also addresses).
    pub zone_type: RequestZoneType,
    /// Zone codes to narrow to, such as `WAZ315` or `WAC033`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<String>>,
    /// Two-letter state, territory or marine-area codes to narrow to, such as `WA` or `PZ`. Un-enumerated for the reason `alerts.get_active_alerts` gives for `area`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub area: Option<Vec<String>>,
    /// Regions to narrow to: a land region (`AR` Alaska, `CR` Central, `ER` Eastern, `PR` Pacific, `SR` Southern, `WR` Western) or a marine one (`AL` Alaska waters, `AT` Atlantic, `GL` Great Lakes, `GM` Gulf of Mexico, `PA` Eastern Pacific, `PI` Pacific Islands).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<Vec<RequestRegionItem>>,
    /// A `latitude,longitude` pair, such as `47.6062,-122.3321`; returns the zones containing it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub point: Option<String>,
    /// Answer as the zone boundaries stood at this time rather than now. A zone that did not exist yet is left out.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effective: Option<TimestampIso>,
    /// Most zones to return. At least 1 (`0` is a 400). Without it the service answers every match: all of `/zones` is over 11,000 zones and about 16 MB.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The zones of one type, optionally narrowed by code, place, region or point. Each comes without its outline; `zones.get_zone` has it.
#[derive(Clone)]
pub struct ListZonesByType {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListZonesByType {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The zones of one type, optionally narrowed by code, place, region or point. Each comes without its outline; `zones.get_zone` has it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone_list_type>.
    pub async fn list_zones_by_type(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ZoneCollection> {
        let raw = self.list_zones_by_type_raw(request, options).await?;
        decode(raw)
    }

    /// `list_zones_by_type` without validation: the wire body as it came.
    pub async fn list_zones_by_type_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/zones/{zone_type}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
