//! Generated by truewire — do not edit by hand.

pub mod get_forecast;
pub mod get_zone;
pub mod list_transmitters;
pub mod list_zones;
pub mod list_zones_by_type;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::{ZoneCollection, ZoneFeature};

/// Forecast, county, fire-weather and marine zones: the areas forecasts, alerts and radio broadcasts are issued for.
///
/// See <https://www.weather.gov/documentation/services-web-api#/default/zone_list>.
#[derive(Clone)]
pub struct Zones {
    get_forecast: get_forecast::GetForecast,
    get_zone: get_zone::GetZone,
    list_transmitters: list_transmitters::ListTransmitters,
    list_zones: list_zones::ListZones,
    list_zones_by_type: list_zones_by_type::ListZonesByType,
}

impl Zones {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_forecast: get_forecast::GetForecast::new(core.clone()),
            get_zone: get_zone::GetZone::new(core.clone()),
            list_transmitters: list_transmitters::ListTransmitters::new(core.clone()),
            list_zones: list_zones::ListZones::new(core.clone()),
            list_zones_by_type: list_zones_by_type::ListZonesByType::new(core),
        }
    }

    /// The text forecast for a public forecast zone: the forecaster's narrative, period by period, for the week ahead. Coarser than `forecast.get_forecast`, which renders one grid cell; this is what is read on NOAA Weather Radio for the whole zone.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone_forecast>.
    pub async fn get_forecast(
        &self,
        request: get_forecast::Request,
        options: CallOptions,
    ) -> Result<get_forecast::ZoneForecast> {
        self.get_forecast.get_forecast(request, options).await
    }

    /// `get_forecast` without validation: the wire body as it came.
    pub async fn get_forecast_raw(
        &self,
        request: get_forecast::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_forecast.get_forecast_raw(request, options).await
    }

    /// One zone, with its outline. The outline is most of what a zone is, so the client hands back the whole GeoJSON feature: `geometry` is the area, `properties` the rest.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone>.
    pub async fn get_zone(
        &self,
        request: get_zone::Request,
        options: CallOptions,
    ) -> Result<ZoneFeature> {
        self.get_zone.get_zone(request, options).await
    }

    /// `get_zone` without validation: the wire body as it came.
    pub async fn get_zone_raw(
        &self,
        request: get_zone::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_zone.get_zone_raw(request, options).await
    }

    /// The NOAA Weather Radio transmitters that broadcast for a county. JSON-LD, not GeoJSON: the transmitters come as a `@graph`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/transmitter_zone>.
    pub async fn list_transmitters(
        &self,
        request: list_transmitters::Request,
        options: CallOptions,
    ) -> Result<list_transmitters::TransmitterCollection> {
        self.list_transmitters
            .list_transmitters(request, options)
            .await
    }

    /// `list_transmitters` without validation: the wire body as it came.
    pub async fn list_transmitters_raw(
        &self,
        request: list_transmitters::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.list_transmitters
            .list_transmitters_raw(request, options)
            .await
    }

    /// The zones the service knows about, of every type, optionally narrowed by code, place, region, type or point. Each comes without its outline; `zones.get_zone` has it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone_list>.
    pub async fn list_zones(
        &self,
        request: list_zones::Request,
        options: CallOptions,
    ) -> Result<ZoneCollection> {
        self.list_zones.list_zones(request, options).await
    }

    /// `list_zones` without validation: the wire body as it came.
    pub async fn list_zones_raw(
        &self,
        request: list_zones::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.list_zones.list_zones_raw(request, options).await
    }

    /// The zones of one type, optionally narrowed by code, place, region or point. Each comes without its outline; `zones.get_zone` has it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/zone_list_type>.
    pub async fn list_zones_by_type(
        &self,
        request: list_zones_by_type::Request,
        options: CallOptions,
    ) -> Result<ZoneCollection> {
        self.list_zones_by_type
            .list_zones_by_type(request, options)
            .await
    }

    /// `list_zones_by_type` without validation: the wire body as it came.
    pub async fn list_zones_by_type_raw(
        &self,
        request: list_zones_by_type::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.list_zones_by_type
            .list_zones_by_type_raw(request, options)
            .await
    }
}
