// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ZoneFeature, ZoneKind } from '../types/index.js'

/** Which zone, and as of when. */
export interface Request {
  /** Zone code, such as `WAZ315`. `points.get_point` returns the forecast, county and fire-weather zones of a place as URLs ending in one. */
  zone_id: string
  /** The zone type. Any of them finds a zone of another type too (`/zones/forecast/PZZ135` answers the coastal zone), but the code decides what comes back. */
  zone_type: ZoneKind
  /** Answer as the zone stood at this time rather than now. Before the zone took effect the service answers 404. */
  effective?: TimestampIso
}

export const Request: Codec<Request> = t.object({
  zone_id: t.string,
  zone_type: ZoneKind,
  effective: t.optional(t.dateTime),
})

/** One zone, with its outline. The outline is most of what a zone is, so the client hands back the whole GeoJSON feature: `geometry` is the area, `properties` the rest. */
export class GetZone {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getZone(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One zone, with its outline. The outline is most of what a zone is, so the client hands back the whole GeoJSON feature: `geometry` is the area, `properties` the rest.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/zone
   */
  getZone(request: Request, options?: CallOptions): Promise<ZoneFeature>
  async getZone(request: Request, options?: CallOptions): Promise<ZoneFeature> {
    return this.core.request({
      method: 'GET',
      path: '/zones/{zone_type}/{zone_id}',
      request,
      requestCodec: Request,
      responseCodec: ZoneFeature,
      meta: {},
      ...options,
    })
  }
}
