// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { TransmitterCollection, ZoneCollection, ZoneFeature } from '../types/index.js'
import * as getForecast from './get_forecast.js'
import * as getZone from './get_zone.js'
import * as listTransmitters from './list_transmitters.js'
import * as listZones from './list_zones.js'
import * as listZonesByType from './list_zones_by_type.js'

/**
 * Forecast, county, fire-weather and marine zones: the areas forecasts, alerts and radio broadcasts are issued for.
 *
 * @see https://www.weather.gov/documentation/services-web-api#/default/zone_list
 */
export class Zones {
  private readonly getForecast_: getForecast.GetForecast
  private readonly getZone_: getZone.GetZone
  private readonly listTransmitters_: listTransmitters.ListTransmitters
  private readonly listZones_: listZones.ListZones
  private readonly listZonesByType_: listZonesByType.ListZonesByType

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getForecast_ = new getForecast.GetForecast(core)
    this.getZone_ = new getZone.GetZone(core)
    this.listTransmitters_ = new listTransmitters.ListTransmitters(core)
    this.listZones_ = new listZones.ListZones(core)
    this.listZonesByType_ = new listZonesByType.ListZonesByType(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getForecast(request: getForecast.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The text forecast for a public forecast zone: the forecaster's narrative, period by period, for the week ahead. Coarser than `forecast.get_forecast`, which renders one grid cell; this is what is read on NOAA Weather Radio for the whole zone.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/zone_forecast
   */
  getForecast(request: getForecast.Request, options?: CallOptions & { validate?: true }): Promise<getForecast.ZoneForecast>
  /** When validation may be disabled, returned values are typed `unknown`. */
  getForecast(request: getForecast.Request, options?: CallOptions): Promise<unknown>
  getForecast(request: getForecast.Request, options?: CallOptions): Promise<unknown> {
    return this.getForecast_.getForecast(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getZone(request: getZone.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One zone, with its outline. The outline is most of what a zone is, so the client hands back the whole GeoJSON feature: `geometry` is the area, `properties` the rest.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/zone
   */
  getZone(request: getZone.Request, options?: CallOptions & { validate?: true }): Promise<ZoneFeature>
  /** When validation may be disabled, returned values are typed `unknown`. */
  getZone(request: getZone.Request, options?: CallOptions): Promise<unknown>
  getZone(request: getZone.Request, options?: CallOptions): Promise<unknown> {
    return this.getZone_.getZone(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTransmitters(request: listTransmitters.ListTransmittersArgs, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The NOAA Weather Radio transmitters that broadcast for a county. JSON-LD, not GeoJSON: the transmitters come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/transmitter_zone
   */
  listTransmitters(request: listTransmitters.ListTransmittersArgs, options?: CallOptions & { validate?: true }): Promise<TransmitterCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  listTransmitters(request: listTransmitters.ListTransmittersArgs, options?: CallOptions): Promise<unknown>
  listTransmitters(request: listTransmitters.ListTransmittersArgs, options?: CallOptions): Promise<unknown> {
    return this.listTransmitters_.listTransmitters(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listZones(request: listZones.Request | undefined, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The zones the service knows about, of every type, optionally narrowed by code, place, region, type or point. Each comes without its outline; `zones.get_zone` has it.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/zone_list
   */
  listZones(request?: listZones.Request, options?: CallOptions & { validate?: true }): Promise<ZoneCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  listZones(request?: listZones.Request, options?: CallOptions): Promise<unknown>
  listZones(request?: listZones.Request, options?: CallOptions): Promise<unknown> {
    return this.listZones_.listZones(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listZonesByType(request: listZonesByType.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The zones of one type, optionally narrowed by code, place, region or point. Each comes without its outline; `zones.get_zone` has it.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/zone_list_type
   */
  listZonesByType(request: listZonesByType.Request, options?: CallOptions & { validate?: true }): Promise<ZoneCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  listZonesByType(request: listZonesByType.Request, options?: CallOptions): Promise<unknown>
  listZonesByType(request: listZonesByType.Request, options?: CallOptions): Promise<unknown> {
    return this.listZonesByType_.listZonesByType(request, options)
  }
}
