// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { TransmitterCollection } from '../types/index.js'

/** Which county. */
export interface Request {
  /** County code, such as `WAC033`. */
  zone_id: string
  /** The zone type. Only `county`: the OpenAPI lists every zone type, but the service refuses any other with a 404 naming `county` as the one value it takes. */
  zone_type: 'county'
}

export const Request: Codec<Request> = t.object({
  zone_id: t.string,
  zone_type: t.literal('county'),
})

/** `listTransmitters`'s request: `Request` with the fixed wire values the method fills in for you. */
export type ListTransmittersArgs = Omit<Request, 'zone_type'> & { zone_type?: 'county' }

/** The NOAA Weather Radio transmitters that broadcast for a county. JSON-LD, not GeoJSON: the transmitters come as a `@graph`. */
export class ListTransmitters {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTransmitters(request: ListTransmittersArgs, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The NOAA Weather Radio transmitters that broadcast for a county. JSON-LD, not GeoJSON: the transmitters come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/transmitter_zone
   */
  listTransmitters(request: ListTransmittersArgs, options?: CallOptions): Promise<TransmitterCollection>
  async listTransmitters(request: ListTransmittersArgs, options?: CallOptions): Promise<TransmitterCollection> {
    const wire: Request = { ...request, zone_type: request.zone_type ?? 'county' }
    return this.core.request({
      method: 'GET',
      path: '/zones/{zone_type}/{zone_id}/radio',
      request: wire,
      requestCodec: Request,
      responseCodec: TransmitterCollection,
      meta: {},
      ...options,
    })
  }
}
