//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use truewire_core::HttpEndpoint;

use crate::alerts::Alerts;
use crate::forecast::Forecast;
use crate::meta::DefaultMeta;
use crate::offices::Offices;
use crate::points::Points;
use crate::products::Products;
use crate::radar::Radar;
use crate::stations::Stations;
use crate::zones::Zones;

/// The United States National Weather Service API (`api.weather.gov`): forecasts, observations, active alerts and the offices and stations behind them. No credentials -- the service asks only that a caller identify itself in `User-Agent`.
///
/// See <https://www.weather.gov/documentation/services-web-api>.
#[derive(Clone)]
pub struct Weather {
    /// Watches, warnings and advisories in effect.
    pub alerts: Alerts,
    /// Forecasts for one grid cell: the twice-daily narrative, the hourly series, and the raw gridded data both are rendered from.
    pub forecast: Forecast,
    /// The weather forecast offices that issue everything else here.
    pub offices: Offices,
    /// Turning a latitude/longitude into the grid the rest of the API is addressed by.
    pub points: Points,
    /// The text products the service publishes, by type.
    pub products: Products,
    /// The radar network: the NEXRAD, TDWR and profiler radars, their status and alarms, and the servers and queues that distribute their Level II data.
    pub radar: Radar,
    /// Observation stations and what they have reported.
    pub stations: Stations,
    /// Forecast, county, fire-weather and marine zones: the areas forecasts, alerts and radio broadcasts are issued for.
    pub zones: Zones,
}

impl Weather {
    /// `[policy].rate`: requests per second the core's `HttpClient` paces to; `None` for none.
    pub const RATE: Option<f64> = None;
    /// `[policy].retry`: whether the core's `HttpClient` retries on its own.
    pub const RETRY: bool = false;

    pub fn from_core(core: impl HttpEndpoint<DefaultMeta> + 'static) -> Self {
        let core: Arc<dyn HttpEndpoint<DefaultMeta>> = Arc::new(core);
        Self {
            alerts: Alerts::new(core.clone()),
            forecast: Forecast::new(core.clone()),
            offices: Offices::new(core.clone()),
            points: Points::new(core.clone()),
            products: Products::new(core.clone()),
            radar: Radar::new(core.clone()),
            stations: Stations::new(core.clone()),
            zones: Zones::new(core),
        }
    }
}
