//! Generated by truewire — do not edit by hand.
//!
//! The United States National Weather Service API (`api.weather.gov`): forecasts, observations, active alerts and the offices and stations behind them. No credentials -- the service asks only that a caller identify itself in `User-Agent`.
//!
//! See <https://www.weather.gov/documentation/services-web-api>.

pub mod alerts;
pub mod client;
pub mod core;
pub mod forecast;
pub mod meta;
pub mod offices;
pub mod points;
pub mod products;
pub mod stations;
pub mod types;

pub use client::Weather;
pub use truewire_core::CallOptions;
