//! Generated by truewire — do not edit by hand.

use std::collections::HashMap;
use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// Counts of the alerts in effect. Only keys with at least one alert appear in the three maps.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ActiveAlertCount {
    /// Alerts in effect.
    pub total: i64,
    /// Alerts affecting land zones.
    pub land: i64,
    /// Alerts affecting marine zones.
    pub marine: i64,
    /// Alerts by marine region code, such as `GL`.
    pub regions: HashMap<String, i64>,
    /// Alerts by state, territory or marine-area code, such as `TX` or `PZ`.
    pub areas: HashMap<String, i64>,
    /// Alerts by zone or county code, such as `AZC009`.
    pub zones: HashMap<String, i64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Takes nothing.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone.
#[derive(Clone)]
pub struct CountActiveAlerts {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl CountActiveAlerts {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active_count>.
    pub async fn count_active_alerts(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ActiveAlertCount> {
        let raw = self.count_active_alerts_raw(request, options).await?;
        decode(raw)
    }

    /// `count_active_alerts` without validation: the wire body as it came.
    pub async fn count_active_alerts_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/alerts/active/count",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
