//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::AlertCollection;

/// Which zone.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Forecast zone (`WAZ315`) or county (`AZC009`) code: two letters of state or marine area, `Z` or `C`, three digits.
    pub zone_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The alerts in effect for one forecast zone or county. The same as `alerts.get_active_alerts` narrowed by `zone`, with the zone in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
#[derive(Clone)]
pub struct GetActiveAlertsForZone {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetActiveAlertsForZone {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The alerts in effect for one forecast zone or county. The same as `alerts.get_active_alerts` narrowed by `zone`, with the zone in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active_zone>.
    pub async fn get_active_alerts_for_zone(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        let raw = self
            .get_active_alerts_for_zone_raw(request, options)
            .await?;
        decode(raw)
    }

    /// `get_active_alerts_for_zone` without validation: the wire body as it came.
    pub async fn get_active_alerts_for_zone_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/alerts/active/zone/{zone_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
