//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::AlertFeature;

/// Which alert.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Alert identifier, such as `urn:oid:2.49.0.1.840.0.<hash>.001.1`. `alerts.get_active_alerts` returns it as `properties.id`.
    pub id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`.
#[derive(Clone)]
pub struct GetAlert {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetAlert {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_single>.
    pub async fn get_alert(&self, request: Request, options: CallOptions) -> Result<AlertFeature> {
        let raw = self.get_alert_raw(request, options).await?;
        decode(raw)
    }

    /// `get_alert` without validation: the wire body as it came.
    pub async fn get_alert_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/alerts/{id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
