//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::DefaultMeta;
use crate::types::AlertFeature;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestRegionItem {
    #[serde(rename = "AL")]
    Al,
    #[serde(rename = "AT")]
    At,
    #[serde(rename = "GL")]
    Gl,
    #[serde(rename = "GM")]
    Gm,
    #[serde(rename = "PA")]
    Pa,
    #[serde(rename = "PI")]
    Pi,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestStatusItem {
    #[serde(rename = "actual")]
    Actual,
    #[serde(rename = "exercise")]
    Exercise,
    #[serde(rename = "system")]
    System,
    #[serde(rename = "test")]
    Test,
    #[serde(rename = "draft")]
    Draft,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestSeverityItem {
    Extreme,
    Severe,
    Moderate,
    Minor,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestUrgencyItem {
    Immediate,
    Expected,
    Future,
    Past,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestCertaintyItem {
    Observed,
    Likely,
    Possible,
    Unlikely,
    Unknown,
}

/// How to narrow the alerts. Every filter is optional; the array-valued ones are sent as repeated query keys and mean "any of".
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Two-letter state, territory or marine-area codes to narrow to, such as `WA` or `PZ`. Sent as a repeated query key. Left un-enumerated deliberately: the service's own 400 lists only the marine half of what it accepts, and a guessed enum would reject the states.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub area: Option<Vec<String>>,
    /// Marine regions to narrow to.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<Vec<RequestRegionItem>>,
    /// Forecast zone codes, such as `WAZ315`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub zone: Option<Vec<String>>,
    /// A `latitude,longitude` pair; returns the alerts covering that point.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub point: Option<String>,
    /// Alert statuses to include. Lower-case, unlike every other enumerated filter here. Pass `actual` to leave out drills and tests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Vec<RequestStatusItem>>,
    /// Severities to include. Capitalised, unlike `status`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub severity: Option<Vec<RequestSeverityItem>>,
    /// Urgencies to include. Capitalised, unlike `status`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub urgency: Option<Vec<RequestUrgencyItem>>,
    /// Certainties to include. Capitalised, unlike `status`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub certainty: Option<Vec<RequestCertaintyItem>>,
    /// Event names to include, such as `Red Flag Warning`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event: Option<Vec<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertCollectionType {
    FeatureCollection,
}

/// The alerts in effect, as a GeoJSON feature collection.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AlertCollection {
    /// Always `FeatureCollection`.
    #[serde(rename = "type")]
    pub type_: AlertCollectionType,
    /// The alerts.
    pub features: Vec<AlertFeature>,
    /// Human-readable title of the collection.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// When the collection was assembled.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it.
#[derive(Clone)]
pub struct GetActiveAlerts {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetActiveAlerts {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active>.
    pub async fn get_active_alerts(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        let raw = self.get_active_alerts_raw(request, options).await?;
        decode(raw)
    }

    /// `get_active_alerts` without validation: the wire body as it came.
    pub async fn get_active_alerts_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/alerts/active",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
