//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

/// The event names.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AlertTypeList {
    /// Event names, roughly alphabetical.
    #[serde(rename = "eventTypes")]
    pub event_types: Vec<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Takes nothing.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Every event name the service issues alerts under, such as `Tornado Warning`. These are the values `event` takes on the alert endpoints.
#[derive(Clone)]
pub struct ListAlertTypes {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListAlertTypes {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Every event name the service issues alerts under, such as `Tornado Warning`. These are the values `event` takes on the alert endpoints.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_types>.
    pub async fn list_alert_types(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<AlertTypeList> {
        let raw = self.list_alert_types_raw(request, options).await?;
        decode(raw)
    }

    /// `list_alert_types` without validation: the wire body as it came.
    pub async fn list_alert_types_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/alerts/types",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
