//! Generated by truewire — do not edit by hand.

pub mod count_active_alerts;
pub mod get_active_alerts;
pub mod get_active_alerts_for_area;
pub mod get_active_alerts_for_region;
pub mod get_active_alerts_for_zone;
pub mod get_alert;
pub mod list_alert_types;
pub mod list_alerts;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::{AlertCollection, AlertFeature};

/// Watches, warnings and advisories in effect.
///
/// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active>.
#[derive(Clone)]
pub struct Alerts {
    count_active_alerts: count_active_alerts::CountActiveAlerts,
    get_active_alerts: get_active_alerts::GetActiveAlerts,
    get_active_alerts_for_area: get_active_alerts_for_area::GetActiveAlertsForArea,
    get_active_alerts_for_region: get_active_alerts_for_region::GetActiveAlertsForRegion,
    get_active_alerts_for_zone: get_active_alerts_for_zone::GetActiveAlertsForZone,
    get_alert: get_alert::GetAlert,
    list_alert_types: list_alert_types::ListAlertTypes,
    list_alerts: list_alerts::ListAlerts,
}

impl Alerts {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            count_active_alerts: count_active_alerts::CountActiveAlerts::new(core.clone()),
            get_active_alerts: get_active_alerts::GetActiveAlerts::new(core.clone()),
            get_active_alerts_for_area: get_active_alerts_for_area::GetActiveAlertsForArea::new(
                core.clone(),
            ),
            get_active_alerts_for_region:
                get_active_alerts_for_region::GetActiveAlertsForRegion::new(core.clone()),
            get_active_alerts_for_zone: get_active_alerts_for_zone::GetActiveAlertsForZone::new(
                core.clone(),
            ),
            get_alert: get_alert::GetAlert::new(core.clone()),
            list_alert_types: list_alert_types::ListAlertTypes::new(core.clone()),
            list_alerts: list_alerts::ListAlerts::new(core),
        }
    }

    /// How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active_count>.
    pub async fn count_active_alerts(
        &self,
        request: count_active_alerts::Request,
        options: CallOptions,
    ) -> Result<count_active_alerts::ActiveAlertCount> {
        self.count_active_alerts
            .count_active_alerts(request, options)
            .await
    }

    /// `count_active_alerts` without validation: the wire body as it came.
    pub async fn count_active_alerts_raw(
        &self,
        request: count_active_alerts::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.count_active_alerts
            .count_active_alerts_raw(request, options)
            .await
    }

    /// Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active>.
    pub async fn get_active_alerts(
        &self,
        request: get_active_alerts::Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        self.get_active_alerts
            .get_active_alerts(request, options)
            .await
    }

    /// `get_active_alerts` without validation: the wire body as it came.
    pub async fn get_active_alerts_raw(
        &self,
        request: get_active_alerts::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_active_alerts
            .get_active_alerts_raw(request, options)
            .await
    }

    /// The alerts in effect for one state, territory or marine area. The same as `alerts.get_active_alerts` narrowed by `area`, with the area in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active_area>.
    pub async fn get_active_alerts_for_area(
        &self,
        request: get_active_alerts_for_area::Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        self.get_active_alerts_for_area
            .get_active_alerts_for_area(request, options)
            .await
    }

    /// `get_active_alerts_for_area` without validation: the wire body as it came.
    pub async fn get_active_alerts_for_area_raw(
        &self,
        request: get_active_alerts_for_area::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_active_alerts_for_area
            .get_active_alerts_for_area_raw(request, options)
            .await
    }

    /// The alerts in effect for one marine region. The same as `alerts.get_active_alerts` narrowed by `region`, with the region in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active_region>.
    pub async fn get_active_alerts_for_region(
        &self,
        request: get_active_alerts_for_region::Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        self.get_active_alerts_for_region
            .get_active_alerts_for_region(request, options)
            .await
    }

    /// `get_active_alerts_for_region` without validation: the wire body as it came.
    pub async fn get_active_alerts_for_region_raw(
        &self,
        request: get_active_alerts_for_region::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_active_alerts_for_region
            .get_active_alerts_for_region_raw(request, options)
            .await
    }

    /// The alerts in effect for one forecast zone or county. The same as `alerts.get_active_alerts` narrowed by `zone`, with the zone in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active_zone>.
    pub async fn get_active_alerts_for_zone(
        &self,
        request: get_active_alerts_for_zone::Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        self.get_active_alerts_for_zone
            .get_active_alerts_for_zone(request, options)
            .await
    }

    /// `get_active_alerts_for_zone` without validation: the wire body as it came.
    pub async fn get_active_alerts_for_zone_raw(
        &self,
        request: get_active_alerts_for_zone::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_active_alerts_for_zone
            .get_active_alerts_for_zone_raw(request, options)
            .await
    }

    /// One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_single>.
    pub async fn get_alert(
        &self,
        request: get_alert::Request,
        options: CallOptions,
    ) -> Result<AlertFeature> {
        self.get_alert.get_alert(request, options).await
    }

    /// `get_alert` without validation: the wire body as it came.
    pub async fn get_alert_raw(
        &self,
        request: get_alert::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_alert.get_alert_raw(request, options).await
    }

    /// Every event name the service issues alerts under, such as `Tornado Warning`. These are the values `event` takes on the alert endpoints.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_types>.
    pub async fn list_alert_types(
        &self,
        request: list_alert_types::Request,
        options: CallOptions,
    ) -> Result<list_alert_types::AlertTypeList> {
        self.list_alert_types
            .list_alert_types(request, options)
            .await
    }

    /// `list_alert_types` without validation: the wire body as it came.
    pub async fn list_alert_types_raw(
        &self,
        request: list_alert_types::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.list_alert_types
            .list_alert_types_raw(request, options)
            .await
    }

    /// Alerts issued over roughly the last seven days, whether or not they are still in effect, newest first, optionally narrowed. For only what is in effect now, use `alerts.get_active_alerts`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_query>.
    pub async fn list_alerts(
        &self,
        request: list_alerts::Request,
        options: CallOptions,
    ) -> Result<AlertCollection> {
        self.list_alerts.list_alerts(request, options).await
    }

    /// `list_alerts` without validation: the wire body as it came.
    pub async fn list_alerts_raw(
        &self,
        request: list_alerts::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.list_alerts.list_alerts_raw(request, options).await
    }
}
