//! Generated by truewire — do not edit by hand.

pub mod get_active_alerts;
pub mod get_alert;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::AlertFeature;

/// Watches, warnings and advisories in effect.
///
/// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active>.
#[derive(Clone)]
pub struct Alerts {
    get_active_alerts: get_active_alerts::GetActiveAlerts,
    get_alert: get_alert::GetAlert,
}

impl Alerts {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_active_alerts: get_active_alerts::GetActiveAlerts::new(core.clone()),
            get_alert: get_alert::GetAlert::new(core),
        }
    }

    /// Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_active>.
    pub async fn get_active_alerts(
        &self,
        request: get_active_alerts::Request,
        options: CallOptions,
    ) -> Result<get_active_alerts::AlertCollection> {
        self.get_active_alerts
            .get_active_alerts(request, options)
            .await
    }

    /// `get_active_alerts` without validation: the wire body as it came.
    pub async fn get_active_alerts_raw(
        &self,
        request: get_active_alerts::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_active_alerts
            .get_active_alerts_raw(request, options)
            .await
    }

    /// One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/alerts_single>.
    pub async fn get_alert(
        &self,
        request: get_alert::Request,
        options: CallOptions,
    ) -> Result<AlertFeature> {
        self.get_alert.get_alert(request, options).await
    }

    /// `get_alert` without validation: the wire body as it came.
    pub async fn get_alert_raw(
        &self,
        request: get_alert::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_alert.get_alert_raw(request, options).await
    }
}
