// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { Product } from '../types/index.js'

/** Which type, from where. */
export interface Request {
  /** Three-letter product type, such as `AFD`. `products.list_product_types` names every code. */
  type_id: string
  /** Issuance location, such as `SEW` for Seattle. `products.list_locations` names every id; `products.list_locations_for_type` narrows them to one type. */
  location_id: string
}

export const Request: Codec<Request> = t.object({
  type_id: t.string,
  location_id: t.string,
})

/** The newest product of one type from one location, with its text. */
export class GetLatestProduct {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getLatestProduct(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The newest product of one type from one location, with its text.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/latest_product_type_location
   */
  getLatestProduct(request: Request, options?: CallOptions): Promise<Product>
  async getLatestProduct(request: Request, options?: CallOptions): Promise<Product> {
    return this.core.request({
      method: 'GET',
      path: '/products/types/{type_id}/locations/{location_id}/latest',
      request,
      requestCodec: Request,
      responseCodec: Product,
      meta: {},
      ...options,
    })
  }
}
