// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { Product, ProductCollection, ProductLocationCollection, ProductTypeCollection } from '../types/index.js'
import * as getLatestProduct from './get_latest_product.js'
import * as getProduct from './get_product.js'
import * as listLocations from './list_locations.js'
import * as listLocationsForType from './list_locations_for_type.js'
import * as listProductTypes from './list_product_types.js'
import * as listProducts from './list_products.js'
import * as listProductsByType from './list_products_by_type.js'
import * as listProductsByTypeAndLocation from './list_products_by_type_and_location.js'
import * as listTypesForLocation from './list_types_for_location.js'

/**
 * The text products the service publishes, by type.
 *
 * @see https://www.weather.gov/documentation/services-web-api#/default/product_types
 */
export class Products {
  private readonly getLatestProduct_: getLatestProduct.GetLatestProduct
  private readonly getProduct_: getProduct.GetProduct
  private readonly listLocations_: listLocations.ListLocations
  private readonly listLocationsForType_: listLocationsForType.ListLocationsForType
  private readonly listProductTypes_: listProductTypes.ListProductTypes
  private readonly listProducts_: listProducts.ListProducts
  private readonly listProductsByType_: listProductsByType.ListProductsByType
  private readonly listProductsByTypeAndLocation_: listProductsByTypeAndLocation.ListProductsByTypeAndLocation
  private readonly listTypesForLocation_: listTypesForLocation.ListTypesForLocation

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getLatestProduct_ = new getLatestProduct.GetLatestProduct(core)
    this.getProduct_ = new getProduct.GetProduct(core)
    this.listLocations_ = new listLocations.ListLocations(core)
    this.listLocationsForType_ = new listLocationsForType.ListLocationsForType(core)
    this.listProductTypes_ = new listProductTypes.ListProductTypes(core)
    this.listProducts_ = new listProducts.ListProducts(core)
    this.listProductsByType_ = new listProductsByType.ListProductsByType(core)
    this.listProductsByTypeAndLocation_ = new listProductsByTypeAndLocation.ListProductsByTypeAndLocation(core)
    this.listTypesForLocation_ = new listTypesForLocation.ListTypesForLocation(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getLatestProduct(request: getLatestProduct.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The newest product of one type from one location, with its text.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/latest_product_type_location
   */
  getLatestProduct(request: getLatestProduct.Request, options?: CallOptions): Promise<Product>
  getLatestProduct(request: getLatestProduct.Request, options?: CallOptions): Promise<Product> {
    return this.getLatestProduct_.getLatestProduct(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getProduct(request: getProduct.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One text product by id, with its text.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/product
   */
  getProduct(request: getProduct.Request, options?: CallOptions): Promise<Product>
  getProduct(request: getProduct.Request, options?: CallOptions): Promise<Product> {
    return this.getProduct_.getProduct(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listLocations(request: listLocations.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every location text products are issued for, by id, with a name where the service has one.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/product_locations
   */
  listLocations(request?: listLocations.Request, options?: CallOptions): Promise<ProductLocationCollection>
  listLocations(request?: listLocations.Request, options?: CallOptions): Promise<ProductLocationCollection> {
    return this.listLocations_.listLocations(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listLocationsForType(request: listLocationsForType.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The locations that issue one product type, by id, with their names.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/products_type_locations
   */
  listLocationsForType(request: listLocationsForType.Request, options?: CallOptions): Promise<ProductLocationCollection>
  listLocationsForType(request: listLocationsForType.Request, options?: CallOptions): Promise<ProductLocationCollection> {
    return this.listLocationsForType_.listLocationsForType(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProductTypes(request: listProductTypes.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/product_types
   */
  listProductTypes(request?: listProductTypes.Request, options?: CallOptions): Promise<ProductTypeCollection>
  listProductTypes(request?: listProductTypes.Request, options?: CallOptions): Promise<ProductTypeCollection> {
    return this.listProductTypes_.listProductTypes(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProducts(request: listProducts.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Text products issued in a span of time, newest first, narrowed by type, office, location or WMO heading. Header fields only; `products.get_product` fetches one with its text.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/products_query
   */
  listProducts(request?: listProducts.Request, options?: CallOptions): Promise<ProductCollection>
  listProducts(request?: listProducts.Request, options?: CallOptions): Promise<ProductCollection> {
    return this.listProducts_.listProducts(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProductsByType(request: listProductsByType.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every product of one type the service still holds, newest first. Header fields only.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/products_type
   */
  listProductsByType(request: listProductsByType.Request, options?: CallOptions): Promise<ProductCollection>
  listProductsByType(request: listProductsByType.Request, options?: CallOptions): Promise<ProductCollection> {
    return this.listProductsByType_.listProductsByType(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProductsByTypeAndLocation(request: listProductsByTypeAndLocation.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every product of one type from one location the service still holds, newest first. Header fields only.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/products_type_location
   */
  listProductsByTypeAndLocation(request: listProductsByTypeAndLocation.Request, options?: CallOptions): Promise<ProductCollection>
  listProductsByTypeAndLocation(request: listProductsByTypeAndLocation.Request, options?: CallOptions): Promise<ProductCollection> {
    return this.listProductsByTypeAndLocation_.listProductsByTypeAndLocation(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTypesForLocation(request: listTypesForLocation.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The product types one location issues.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/location_products
   */
  listTypesForLocation(request: listTypesForLocation.Request, options?: CallOptions): Promise<ProductTypeCollection>
  listTypesForLocation(request: listTypesForLocation.Request, options?: CallOptions): Promise<ProductTypeCollection> {
    return this.listTypesForLocation_.listTypesForLocation(request, options)
  }
}
