// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** One kind of text product. */
export interface ProductType {
  /** Three-letter code, such as `AFD`. */
  productCode: string
  /** What the code stands for, such as `Area Forecast Discussion`. */
  productName: string
}

export const ProductType: Codec<ProductType> = t.object({
  productCode: t.string,
  productName: t.string,
})

/** Takes nothing. */
export interface Request {}

export const Request: Codec<Request> = t.object({})

/** The product types, in a JSON-LD graph -- the third response vocabulary this API uses, after GeoJSON and schema.org. */
export interface ProductTypeCollection {
  /** The product types, ordered by code. */
  '@graph': ProductType[]
}

export const ProductTypeCollection: Codec<ProductTypeCollection> = t.object({
  '@graph': t.array(ProductType),
})

/** Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for. */
export class ListProductTypes {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProductTypes(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/product_types
   */
  listProductTypes(request?: Request, options?: CallOptions): Promise<ProductTypeCollection>
  async listProductTypes(request?: Request, options?: CallOptions): Promise<ProductTypeCollection> {
    return this.core.request({
      method: 'GET',
      path: '/products/types',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: ProductTypeCollection,
      meta: {},
      ...options,
    })
  }
}
