// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProductLocationCollection } from '../types/index.js'

/** Which type. */
export interface Request {
  /** Three-letter product type, such as `AFD`. `products.list_product_types` names every code. */
  type_id: string
}

export const Request: Codec<Request> = t.object({
  type_id: t.string,
})

/** The locations that issue one product type, by id, with their names. */
export class ListLocationsForType {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listLocationsForType(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The locations that issue one product type, by id, with their names.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/products_type_locations
   */
  listLocationsForType(request: Request, options?: CallOptions): Promise<ProductLocationCollection>
  async listLocationsForType(request: Request, options?: CallOptions): Promise<ProductLocationCollection> {
    return this.core.request({
      method: 'GET',
      path: '/products/types/{type_id}/locations',
      request,
      requestCodec: Request,
      responseCodec: ProductLocationCollection,
      meta: {},
      ...options,
    })
  }
}
