// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProductTypeCollection } from '../types/index.js'

/** Takes nothing. */
export interface Request {}

export const Request: Codec<Request> = t.object({})

/** Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for. */
export class ListProductTypes {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProductTypes(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/product_types
   */
  listProductTypes(request?: Request, options?: CallOptions): Promise<ProductTypeCollection>
  async listProductTypes(request?: Request, options?: CallOptions): Promise<ProductTypeCollection> {
    return this.core.request({
      method: 'GET',
      path: '/products/types',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: ProductTypeCollection,
      meta: {},
      ...options,
    })
  }
}
