// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ProductCollection } from '../types/index.js'

/** Which products. Every filter is optional. Give one value per array filter: the service reads several only comma-separated, and this client sends them as repeated keys, of which the service keeps the last. */
export interface Request {
  /** Issuance locations to narrow to, such as `SEW`. */
  location?: string[]
  /** Start of the span, inclusive. The service keeps about a week of products here; an older start returns nothing rather than failing. */
  start?: TimestampIso
  /** End of the span, exclusive: a product issued at exactly `end` is not returned. */
  end?: TimestampIso
  /** Four-letter issuing offices to narrow to, such as `KSEW`. */
  office?: string[]
  /** WMO abbreviated headings to narrow to, four letters and two digits, such as `FXUS66`. */
  wmoid?: string[]
  /** Three-letter product types to narrow to, such as `AFD`. Left un-enumerated: `products.list_product_types` lists over 300 codes, and the service adds them. */
  type?: string[]
  /** Products per response. Range [1, 500]; the service refuses anything outside it with a 400. Without it the service answers up to 5000. */
  limit?: number
}

export const Request: Codec<Request> = t.object({
  location: t.optional(t.array(t.string)),
  start: t.optional(t.dateTime),
  end: t.optional(t.dateTime),
  office: t.optional(t.array(t.string)),
  wmoid: t.optional(t.array(t.string)),
  type: t.optional(t.array(t.string)),
  limit: t.optional(t.integer),
})

/** Text products issued in a span of time, newest first, narrowed by type, office, location or WMO heading. Header fields only; `products.get_product` fetches one with its text. */
export class ListProducts {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listProducts(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Text products issued in a span of time, newest first, narrowed by type, office, location or WMO heading. Header fields only; `products.get_product` fetches one with its text.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/products_query
   */
  listProducts(request?: Request, options?: CallOptions): Promise<ProductCollection>
  async listProducts(request?: Request, options?: CallOptions): Promise<ProductCollection> {
    return this.core.request({
      method: 'GET',
      path: '/products',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: ProductCollection,
      meta: {},
      ...options,
    })
  }
}
