// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ObservationCollection } from '../types/index.js'

/** Which zone, over which span. */
export interface Request {
  /** Public zone code, such as `WAZ315`. */
  zone_id: string
  /** Start of the span, inclusive. The service keeps about a week of observations. */
  start?: TimestampIso
  /** End of the span, exclusive: an observation at exactly `end` is not returned. */
  end?: TimestampIso
  /** Observations per response, newest kept. Range [1, 500]. */
  limit?: number
}

export const Request: Codec<Request> = t.object({
  zone_id: t.string,
  start: t.optional(t.dateTime),
  end: t.optional(t.dateTime),
  limit: t.optional(t.integer),
})

/** Observations from every station in a public forecast zone, over a span, newest first. The same rows `stations.get_observations` returns for each of `stations.list_stations_for_zone`, merged. */
export class GetObservationsForZone {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getObservationsForZone(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Observations from every station in a public forecast zone, over a span, newest first. The same rows `stations.get_observations` returns for each of `stations.list_stations_for_zone`, merged.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/zone_obs
   */
  getObservationsForZone(request: Request, options?: CallOptions & { validate?: true }): Promise<ObservationCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  getObservationsForZone(request: Request, options?: CallOptions): Promise<unknown>
  async getObservationsForZone(request: Request, options?: CallOptions): Promise<ObservationCollection> {
    return this.core.request({
      method: 'GET',
      path: '/zones/forecast/{zone_id}/observations',
      request,
      requestCodec: Request,
      responseCodec: ObservationCollection,
      meta: {},
      ...options,
    })
  }
}
