// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { StationFeature } from '../types/index.js'

/** Which station. */
export interface Request {
  /** Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`. */
  station_id: string
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
})

/** One observation station: where it is, who runs it, and which zones it sits in. */
export class GetStation {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getStation(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One observation station: where it is, who runs it, and which zones it sits in.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/obs_station
   */
  getStation(request: Request, options?: CallOptions & { validate?: true }): Promise<StationFeature>
  /** When validation may be disabled, returned values are typed `unknown`. */
  getStation(request: Request, options?: CallOptions): Promise<unknown>
  async getStation(request: Request, options?: CallOptions): Promise<StationFeature> {
    return this.core.request({
      method: 'GET',
      path: '/stations/{station_id}',
      request,
      requestCodec: Request,
      responseCodec: StationFeature,
      meta: {},
      ...options,
    })
  }
}
