// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { Observation } from '../types/index.js'

/** Which station. */
export interface Request {
  /** Station identifier, such as `KSEA`. */
  station_id: string
  /** Return only an observation that has passed quality control. Off by default, which is what you want for a current reading: quality control lags the observation. */
  require_qc?: boolean
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
  require_qc: t.optional(t.boolean),
})

/** The most recent observation from one station. This is the endpoint behind "what is it doing outside right now". */
export class GetLatestObservation {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getLatestObservation(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The most recent observation from one station. This is the endpoint behind "what is it doing outside right now".
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/station_observation_latest
   */
  getLatestObservation(request: Request, options?: CallOptions): Promise<Observation>
  async getLatestObservation(request: Request, options?: CallOptions): Promise<Observation> {
    return this.core.request({
      method: 'GET',
      path: '/stations/{station_id}/observations/latest',
      request,
      requestCodec: Request,
      responseCodec: Observation,
      meta: { payload: 'properties' },
      ...options,
    })
  }
}
