// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { ObservationFeature } from '../types/index.js'

/** Where the next page is, as a whole URL. The declared walk moves the time window instead and never reads this. */
export interface ObservationPagination {
  /** URL of the next page. Absent on the last one. */
  next?: string
}

export const ObservationPagination: Codec<ObservationPagination> = t.object({
  next: t.optional(t.string),
})

/** Which station, over which span. */
export interface Request {
  /** Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`. */
  station_id: string
  /** Start of the span, inclusive. The service keeps about a week of observations; a start older than that returns nothing rather than failing. */
  start?: TimestampIso
  /** End of the span, inclusive. */
  end?: TimestampIso
  /** Observations per response. Range [1, 500]; the service caps a response at 500 whether or not this is sent, so 500 is also the default. */
  limit?: number
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
  start: t.optional(t.dateTime),
  end: t.optional(t.dateTime),
  limit: t.optional(t.integer),
})

/** The observations in the span, as a GeoJSON feature collection, newest first. */
export interface ObservationCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The observations, newest first. */
  features: ObservationFeature[]
  pagination?: ObservationPagination
}

export const ObservationCollection: Codec<ObservationCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(ObservationFeature),
  pagination: t.optional(ObservationPagination),
})

/** What one station reported over a span of time, newest first. Airport stations report about every twenty minutes, and more often when the weather changes, so a day is a few hundred observations. */
// truewire: a `window` walk has no TypeScript walker yet; call `getObservations` per page.
export class GetObservations {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getObservations(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * What one station reported over a span of time, newest first. Airport stations report about every twenty minutes, and more often when the weather changes, so a day is a few hundred observations.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/station_observation_list
   */
  getObservations(request: Request, options?: CallOptions): Promise<ObservationCollection>
  async getObservations(request: Request, options?: CallOptions): Promise<ObservationCollection> {
    return this.core.request({
      method: 'GET',
      path: '/stations/{station_id}/observations',
      request,
      requestCodec: Request,
      responseCodec: ObservationCollection,
      meta: {},
      ...options,
    })
  }
}
