// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { StationFeature } from '../types/index.js'

/** Where the next page is. A whole URL, not a bare cursor -- which is why this endpoint declares no pagination strategy. */
export interface CollectionPagination {
  /** URL of the next page, cursor already in the query string. Absent on the last page. */
  next?: string
}

export const CollectionPagination: Codec<CollectionPagination> = t.object({
  next: t.optional(t.string),
})

/** Which stations, and how many. */
export interface Request {
  /** Station identifiers to return, such as `KSEA`. Sent as a repeated query key, one per identifier. */
  id?: string[]
  /** Two-letter state or marine-area codes to narrow to. Sent as a repeated query key. */
  state?: string[]
  /** Stations per page. Range [1, 500]. */
  limit?: number
  /** Page cursor. The service does not hand this back on its own -- see the note -- so it is here for a caller who has one, not for a walk the client drives. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  id: t.optional(t.array(t.string)),
  state: t.optional(t.array(t.string)),
  limit: t.optional(t.integer),
  cursor: t.optional(t.string),
})

/** One page of stations, as a GeoJSON feature collection. */
export interface StationCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The stations. */
  features: StationFeature[]
  /** The same stations as bare URLs, in the same order. */
  observationStations?: string[]
  pagination?: CollectionPagination
}

export const StationCollection: Codec<StationCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(StationFeature),
  observationStations: t.optional(t.array(t.string)),
  pagination: t.optional(CollectionPagination),
})

/** The observation stations the service knows about, optionally narrowed to a state or to named identifiers. Use it to find the station code `stations.get_observations` takes. */
export class ListStations {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listStations(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The observation stations the service knows about, optionally narrowed to a state or to named identifiers. Use it to find the station code `stations.get_observations` takes.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/obs_stations
   */
  listStations(request?: Request, options?: CallOptions): Promise<StationCollection>
  async listStations(request?: Request, options?: CallOptions): Promise<StationCollection> {
    return this.core.request({
      method: 'GET',
      path: '/stations',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: StationCollection,
      meta: {},
      ...options,
    })
  }
}
