// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Which airport. */
export interface Request {
  /** Station identifier of an airport, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`. */
  station_id: string
}

export const Request: Codec<Request> = t.object({
  station_id: t.string,
})

/** When one Terminal Aerodrome Forecast was issued, and the span it covers. */
export interface TafSummary {
  /** URL of the forecast itself, such as `https://api.weather.gov/stations/KSEA/tafs/2026-09-30/1700`. It answers only in IWXXM XML, which is why no endpoint here fetches it. */
  id: string
  /** When the forecast was issued. */
  issueTime: TimestampIso
  /** Station identifier of the airport, such as `KSEA`. */
  location: string
  /** Start of the span the forecast covers. */
  start: TimestampIso
  /** End of the span the forecast covers. */
  end: TimestampIso
  /** Where the airport is, as Well-Known Text: `POINT(47.44 -122.31)`. Latitude first, the reverse of the GeoJSON `coordinates` elsewhere in this API. */
  geometry?: string
}

export const TafSummary: Codec<TafSummary> = t.object({
  id: t.string,
  issueTime: t.dateTime,
  location: t.string,
  start: t.dateTime,
  end: t.dateTime,
  geometry: t.optional(t.string),
})

/** The forecasts, as a JSON-LD graph. */
export interface TafCollection {
  /** The forecasts, newest first. */
  '@graph': TafSummary[]
}

export const TafCollection: Codec<TafCollection> = t.object({
  '@graph': t.array(TafSummary),
})

/** The Terminal Aerodrome Forecasts issued for an airport station over roughly the last week, newest first. Only when and for how long each one applies: the forecast text is at each one's `id`, which answers only in XML. */
export class ListTafs {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTafs(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The Terminal Aerodrome Forecasts issued for an airport station over roughly the last week, newest first. Only when and for how long each one applies: the forecast text is at each one's `id`, which answers only in XML.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/tafs
   */
  listTafs(request: Request, options?: CallOptions): Promise<TafCollection>
  async listTafs(request: Request, options?: CallOptions): Promise<TafCollection> {
    return this.core.request({
      method: 'GET',
      path: '/stations/{station_id}/tafs',
      request,
      requestCodec: Request,
      responseCodec: TafCollection,
      meta: {},
      ...options,
    })
  }
}
