# Generated by truewire — do not edit by hand.
"""Shapes shared by two or more endpoints under the client root, generated from `spec/schemas.json`."""

from typing_extensions import Literal, NotRequired, TypedDict
from truewire_core.types import TimestampIso


class AlertGeocode(TypedDict):
  """The areas covered, as codes rather than prose."""

  SAME: NotRequired[list[str]]
  """SAME (Specific Area Message Encoding) codes, one per county."""
  UGC: NotRequired[list[str]]
  """UGC (Universal Geographic Code) zone codes."""


class AlertReference(TypedDict):
  """An earlier alert this one updates, corrects or cancels."""

  identifier: str
  """Identifier of the referenced alert."""
  sender: NotRequired[str]
  """Who sent the referenced alert."""
  sent: NotRequired[TimestampIso]
  """When the referenced alert was sent."""


class CollectionPagination(TypedDict):
  """Where the next page is. A whole URL, not a bare cursor -- which is why no endpoint returning this declares a pagination strategy."""

  next: NotRequired[str]
  """URL of the next page, cursor already in the query string. Absent on the last page."""


class GridValue(TypedDict):
  """One value of a gridded series, and the interval it holds over."""

  validTime: str
  """ISO 8601 interval this value covers, as `<start>/<duration>` -- one string carrying both, such as `2026-09-09T01:00:00+00:00/PT1H`."""
  value: float | None
  """The value over `validTime`."""


class MultiPolygonGeometry(TypedDict):
  """GeoJSON geometry of several disjoint areas -- an alert covering counties that do not touch."""

  type: Literal['MultiPolygon']
  """Always `MultiPolygon`."""
  coordinates: list[list[list[tuple[float, float]]]]
  """One entry per polygon, each shaped like `PolygonGeometry.coordinates`."""


class ObservationPagination(TypedDict):
  """Where the next page is, as a whole URL. The declared walk moves the time window instead and never reads this."""

  next: NotRequired[str]
  """URL of the next page. Absent on the last one."""


class PointGeometry(TypedDict):
  """GeoJSON geometry of a feature that sits at a single place: a station, an observation, a forecast point."""

  type: Literal['Point']
  """Always `Point` for these features."""
  coordinates: tuple[float, float]
  """A GeoJSON position: longitude first, then latitude, in WGS 84 decimal degrees."""


class PolygonGeometry(TypedDict):
  """GeoJSON geometry of an area: one outer ring, then any holes."""

  type: Literal['Polygon']
  """Always `Polygon`."""
  coordinates: list[list[tuple[float, float]]]
  """Linear rings. The first is the outer boundary; any others are holes in it. Each ring repeats its first position as its last."""


Position = tuple[float, float]


class PresentWeather(TypedDict):
  """One present-weather group decoded from the station's METAR."""

  intensity: NotRequired[str | None]
  """`light`, `heavy`, or null for moderate."""
  modifier: NotRequired[str | None]
  """Qualifier such as `patches` or `blowing`."""
  weather: NotRequired[str | None]
  """The phenomenon itself: `rain`, `snow`, `fog_mist`, `thunderstorms`."""
  rawString: str
  """The METAR group this was decoded from, such as `-RA`."""


class QuantitativeValue(TypedDict):
  """A measurement and the unit it is in. The service never sends a bare number: every value arrives beside the WMO unit code it is expressed in, and `value` is null wherever the measurement is missing rather than zero."""

  unitCode: str
  """WMO unit of measure, as a URI shorthand: `wmoUnit:degC`, `wmoUnit:km_h-1`, `wmoUnit:percent`, `wmoUnit:Pa`, `wmoUnit:m`."""
  value: float | None
  """The measurement, or null where there is none. Null is common and is not an error: an airport station reports `windGust` only when there were gusts."""
  qualityControl: NotRequired[str]
  """Quality-control flag the observation carried: `V` validated, `S` screened, `C` coarse-passed, `Z` preliminary, `Q` questionable. Present on observations, absent on forecasts."""
  maxValue: NotRequired[float]
  """Upper end, where the value is a range rather than a point."""
  minValue: NotRequired[float]
  """Lower end, where the value is a range rather than a point."""


class RadarNetworkInterface(TypedDict):
  """Packet counters of one network interface."""

  interface: str
  """Interface name, such as `eth0`."""
  active: bool
  """Whether the interface is up."""
  transNoError: NotRequired[int]
  """Packets sent without error."""
  transError: NotRequired[int]
  """Packets that failed to send."""
  transDropped: NotRequired[int]
  """Outgoing packets dropped."""
  transOverrun: NotRequired[int]
  """Outgoing overruns."""
  recvNoError: NotRequired[int]
  """Packets received without error."""
  recvError: NotRequired[int]
  """Packets received with an error."""
  recvDropped: NotRequired[int]
  """Incoming packets dropped."""
  recvOverrun: NotRequired[int]
  """Incoming overruns."""


class RadarServerCommand(TypedDict):
  """The last command the server ran and received. Only `ldm` servers send it."""

  lastExecuted: NotRequired[str]
  """Last command run, such as `LDM Start`."""
  lastExecutedTime: NotRequired[TimestampIso]
  """When it ran."""
  lastNexradDataTime: NotRequired[TimestampIso]
  """When the server last received NEXRAD data."""
  lastReceived: NotRequired[str]
  """Last command received."""
  lastReceivedTime: NotRequired[TimestampIso]
  """When it was received."""
  timestamp: NotRequired[TimestampIso]
  """When this block was collected."""


class RadarServerHardware(TypedDict):
  """Host load and resources."""

  timestamp: NotRequired[TimestampIso]
  """When this block was collected."""
  cpuIdle: NotRequired[float]
  """Idle CPU, in percent."""
  ioUtilization: NotRequired[float]
  """Disk I/O utilisation, in percent."""
  disk: NotRequired[float]
  """Disk used, in percent."""
  load1: NotRequired[float]
  """One-minute load average."""
  load5: NotRequired[float]
  """Five-minute load average."""
  load15: NotRequired[float]
  """Fifteen-minute load average."""
  memory: NotRequired[float]
  """Memory used, in percent."""
  uptime: NotRequired[TimestampIso]
  """When the host last booted: a time, despite the name, not a duration."""


class RadarServerLdm(TypedDict):
  """The server's LDM product queue."""

  timestamp: NotRequired[TimestampIso]
  """When this block was collected."""
  latestProduct: NotRequired[TimestampIso]
  """Arrival of the newest product in the queue."""
  oldestProduct: NotRequired[TimestampIso]
  """Arrival of the oldest product still in the queue."""
  storageSize: NotRequired[int]
  """Size of the queue, in bytes."""
  count: NotRequired[int]
  """Products in the queue."""
  active: NotRequired[bool]
  """Whether LDM is running."""


class RadarServerPing(TypedDict):
  """Which hosts the server could reach at its last ping round."""

  targets: dict[str, dict[str, bool] | list[bool]]
  """Ping results by group of targets: `client` (downstream data clients, such as `ncep`), `ldm` and `server` (other servers, by name), `radar` (radar stations, by identifier) and `misc` (interfaces and routers, such as `eth0`). A group the server does not ping is absent."""
  timestamp: TimestampIso
  """When the ping round ran."""


ZoneKeywords = TypedDict('ZoneKeywords', {'@id': str, '@type': NotRequired[Literal['wx:Zone']]})
"""
  - `@id`: Canonical URL of the zone.
  - `@type`: Always `wx:Zone`.
"""


class Zone(ZoneKeywords):
  """One zone: a public forecast, county, fire-weather or marine area."""

  id: str
  """Zone code: two letters of state or marine area, `Z` or `C`, three digits."""
  type: Literal['land', 'marine', 'forecast', 'public', 'coastal', 'offshore', 'fire', 'county']
  """The zone type. The service answers with five of these: `public` (what `forecast` and `land` also address), `county`, `fire`, `coastal` and `offshore` (what `marine` also addresses)."""
  name: str
  """Name of the zone, such as `City of Seattle`."""
  effectiveDate: TimestampIso
  """When this version of the zone took effect."""
  expirationDate: TimestampIso
  """When it expires; `2200-01-01` for every zone in effect on 2026-09-30."""
  state: NotRequired[str | None]
  """State or territory the zone is in."""
  forecastOffice: NotRequired[str]
  """URL of the office that forecasts for the zone."""
  gridIdentifier: NotRequired[str]
  """Three-letter code of the office's forecast grid, such as `SEW`."""
  awipsLocationIdentifier: NotRequired[str]
  """AWIPS identifier of the forecasting office."""
  cwa: NotRequired[list[str]]
  """Offices whose warning area covers the zone. Deprecated upstream; use `forecastOffice`."""
  forecastOffices: NotRequired[list[str]]
  """URLs of the same offices. Deprecated upstream; use `forecastOffice`."""
  timeZone: NotRequired[list[str]]
  """IANA time zones the zone is in; two for a zone that straddles a boundary."""
  observationStations: NotRequired[list[str]]
  """URLs of the observation stations in the zone. Empty for most county, fire and marine zones."""
  radarStation: NotRequired[str | None]
  """The radar that covers the zone."""


ZoneKind = Literal['land', 'marine', 'forecast', 'public', 'coastal', 'offshore', 'fire', 'county']


class Alert(TypedDict):
  """One watch, warning or advisory, in the Common Alerting Protocol vocabulary the service issues them in."""

  id: str
  """Identifier of this alert, such as `urn:oid:2.49.0.1.840.0.<hash>.001.1`. This is what `alerts.get_alert` takes."""
  areaDesc: str
  """Semicolon-separated names of the areas covered."""
  geocode: NotRequired[AlertGeocode]
  affectedZones: NotRequired[list[str]]
  """URLs of the forecast zones covered."""
  references: NotRequired[list[AlertReference]]
  """Earlier alerts this one supersedes."""
  sent: TimestampIso
  """When the alert was sent."""
  effective: TimestampIso
  """When it takes effect."""
  onset: NotRequired[TimestampIso | None]
  """When the event itself is expected to begin, if later than `effective`."""
  expires: TimestampIso
  """When the alert expires unless updated."""
  ends: NotRequired[TimestampIso | None]
  """When the event itself is expected to end."""
  status: Literal['Actual', 'Exercise', 'System', 'Test', 'Draft']
  """Whether this is a real alert. Filter on `Actual` unless you want drills."""
  messageType: Literal['Alert', 'Update', 'Cancel', 'Ack', 'Error']
  """Whether this issues, updates or cancels."""
  category: NotRequired[
    Literal[
      'Met',
      'Geo',
      'Safety',
      'Security',
      'Rescue',
      'Fire',
      'Health',
      'Env',
      'Transport',
      'Infra',
      'CBRNE',
      'Other',
    ]
  ]
  """Broad category; `Met` for weather."""
  severity: Literal['Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown']
  """How bad the impact would be."""
  certainty: Literal['Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown']
  """How likely it is to happen."""
  urgency: Literal['Immediate', 'Expected', 'Future', 'Past', 'Unknown']
  """How soon to act."""
  event: str
  """The event name, such as `Flood Watch` or `Red Flag Warning`."""
  sender: NotRequired[str]
  """Email address of the sender."""
  senderName: str
  """The issuing office, such as `NWS Seattle WA`."""
  headline: NotRequired[str | None]
  """One-line summary with the times spelled out."""
  description: str
  """The full text of the alert."""
  instruction: NotRequired[str | None]
  """What the public is being told to do."""
  response: NotRequired[
    Literal[
      'Shelter', 'Evacuate', 'Prepare', 'Execute', 'Avoid', 'Monitor', 'AllClear', 'Assess', 'None'
    ]
  ]
  """The recommended action."""
  parameters: NotRequired[dict[str, list[str]]]
  """Free-form parameters the issuing system attached: `NWSheadline`, `VTEC`, `AWIPSidentifier` and others. Every value is a list, even when it holds one item."""


AlertGeometry = PolygonGeometry | MultiPolygonGeometry | None


class CloudLayer(TypedDict):
  """One reported cloud layer: how much of the sky it covers and how high its base is."""

  base: QuantitativeValue
  """Height of the layer's base above the station."""
  amount: Literal['OVC', 'BKN', 'SCT', 'FEW', 'SKC', 'CLR', 'VV']
  """METAR sky-cover code: `OVC` overcast, `BKN` broken, `SCT` scattered, `FEW` few, `SKC`/`CLR` clear, `VV` vertical visibility (sky obscured)."""


class ForecastPeriod(TypedDict):
  """One period of a narrative forecast: a named half-day in the twice-daily forecast, or one hour in the hourly one."""

  number: int
  """Sequence number within the forecast, starting at 1."""
  name: str
  """Name of the period, such as `Tonight` or `Wednesday`. Empty in the hourly forecast, which names nothing."""
  startTime: TimestampIso
  """When the period begins, in the forecast point's own local time."""
  endTime: TimestampIso
  """When the period ends."""
  isDaytime: bool
  """Whether this is a daytime period."""
  temperature: float
  """Forecast temperature, in `temperatureUnit`. A bare number here, unlike everywhere else in this API."""
  temperatureUnit: Literal['F', 'C']
  """Unit `temperature` is in: `F` under `units=us`, `C` under `units=si`."""
  temperatureTrend: NotRequired[str | None]
  """`rising` or `falling` where the temperature moves against the usual daily cycle."""
  probabilityOfPrecipitation: NotRequired[QuantitativeValue]
  """Chance of measurable precipitation."""
  dewpoint: NotRequired[QuantitativeValue]
  """Forecast dew point. Hourly forecasts only."""
  relativeHumidity: NotRequired[QuantitativeValue]
  """Forecast relative humidity. Hourly forecasts only."""
  windSpeed: str
  """Wind speed as prose with its unit, such as `5 to 10 mph`. A string, not a `QuantitativeValue`."""
  windDirection: str
  """Compass direction the wind comes from, such as `NNE`."""
  icon: NotRequired[str]
  """URL of an icon for the period."""
  shortForecast: str
  """A few words, such as `Partly Sunny`."""
  detailedForecast: str
  """A sentence or two. Empty in the hourly forecast."""


class GridSeries(TypedDict):
  """One gridded series: a unit and a run of intervals, each with its own value. Consecutive intervals with the same value are collapsed into one, so the series is not evenly spaced."""

  uom: NotRequired[str]
  """WMO unit code every value is in."""
  values: list[GridValue]
  """The values, in time order."""


class RadarLatency(TypedDict):
  """How far behind real time the radar's Level II data reaches the LDM host named by `host`. Every field is null for a radar with no Level II feed, such as a profiler."""

  current: QuantitativeValue | None
  """Latency of the latest data."""
  average: QuantitativeValue | None
  """Average latency."""
  max: QuantitativeValue | None
  """Highest recent latency."""
  levelTwoLastReceivedTime: TimestampIso | None
  """When the host last received Level II data."""
  maxLatencyTime: TimestampIso | None
  """When the highest latency was seen."""
  reportingHost: str | None
  """Monitoring host that reported the latency."""
  host: str | None
  """LDM host the latency is measured at."""


class RadarRdaStatus(TypedDict):
  """The status fields. A TDWR sends fewer of them than a WSR-88D."""

  resolutionVersion: NotRequired[int | None]
  """Level II resolution version."""
  nl2Path: str
  """Level II data path, such as `Default`."""
  volumeCoveragePattern: str
  """Scan strategy in use, such as `R35` (clear air) or `R212` (precipitation)."""
  controlStatus: str
  """Who controls the radar, such as `RPG (Remote) Only`."""
  buildNumber: float
  """Software build, such as `24.1`."""
  alarmSummary: str
  """Classes of active alarm, `|`-separated, such as `Transmitter|Communication`, or `No Alarms`."""
  mode: str
  """Operating mode, such as `Operational` or `Maintenance`."""
  generatorState: NotRequired[str]
  """Power source state, such as `Utility PWR Available`. WSR-88D only."""
  superResolutionStatus: NotRequired[str]
  """Whether super-resolution scanning is on. WSR-88D only."""
  operabilityStatus: str
  """Whether the radar needs maintenance, such as `RDA - On-Line`."""
  status: str
  """RDA state, such as `Operate` or `Standby`."""
  averageTransmitterPower: NotRequired[QuantitativeValue]
  """Average transmitter power. WSR-88D only."""
  reflectivityCalibrationCorrection: NotRequired[QuantitativeValue]
  """Reflectivity calibration correction. WSR-88D only."""


class RadarReport(TypedDict):
  """A periodic engineering report from the radar: its performance check or its adaptation (calibration) data."""

  timestamp: NotRequired[TimestampIso | None]
  """When the report was made."""
  reportingHost: str
  """Monitoring host that collected it, such as `rdss` or `tdss`."""
  properties: dict[str, QuantitativeValue | str | float] | list[str]
  """The readings, by name. Their set depends on the kind of radar and is not documented, so they are a map rather than fields; a TDWR sends `[]`."""


class RadarServerNetwork(TypedDict):
  """Traffic counters of the server's two network interfaces."""

  timestamp: NotRequired[TimestampIso]
  """When this block was collected."""
  eth0: NotRequired[RadarNetworkInterface]
  """The first interface."""
  eth1: NotRequired[RadarNetworkInterface]
  """The second interface."""


class Station(TypedDict):
  """One observation station."""

  stationIdentifier: str
  """Station identifier, such as `KSEA`. This is what `stations.get_observations` takes."""
  name: str
  """Human-readable station name."""
  timeZone: NotRequired[str]
  """IANA time zone the station is in, such as `America/Los_Angeles`."""
  elevation: NotRequired[QuantitativeValue]
  """Station elevation above sea level."""
  forecast: NotRequired[str]
  """URL of the forecast zone the station is in."""
  county: NotRequired[str]
  """URL of the county zone the station is in."""
  fireWeatherZone: NotRequired[str]
  """URL of the fire-weather zone the station is in."""
  provider: NotRequired[str]
  """Network the station belongs to, such as `NWS/FAA` or `MesoWest`."""
  subProvider: NotRequired[str]
  """Operator within the network."""
  distance: NotRequired[QuantitativeValue]
  """How far the station is from the grid cell asked about. Only `stations.list_stations_for_gridpoint` sends it."""
  bearing: NotRequired[QuantitativeValue]
  """Direction from the grid cell to the station, in degrees clockwise from true north. Only `stations.list_stations_for_gridpoint` sends it."""


class ZoneFeature(TypedDict):
  """One zone, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of the zone."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: PolygonGeometry | MultiPolygonGeometry | None
  """The area a zone covers."""
  properties: Zone
  """The zone itself."""


ZoneGeometry = PolygonGeometry | MultiPolygonGeometry | None


class AlertFeature(TypedDict):
  """One alert, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of this alert."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PolygonGeometry | MultiPolygonGeometry | None]
  """The area an alert covers, when it was drawn as a polygon rather than named as zones."""
  properties: Alert
  """The alert itself."""


class GridpointForecast(TypedDict):
  """A narrative forecast for one grid cell, as a list of periods. Named for the service's own term: `/gridpoints/{office}/{x},{y}/forecast` is the gridpoint forecast."""

  units: Literal['us', 'si']
  """Unit system the periods are rendered in."""
  forecastGenerator: NotRequired[str]
  """Which generator produced it, such as `BaselineForecastGenerator`."""
  generatedAt: TimestampIso
  """When this rendering was generated."""
  updateTime: TimestampIso
  """When the underlying grid data was last updated."""
  validTimes: str
  """ISO 8601 interval the forecast covers, as `<start>/<duration>`."""
  elevation: NotRequired[QuantitativeValue]
  """Elevation of the grid cell."""
  periods: list[ForecastPeriod]
  """The forecast periods, in order."""


class Observation(TypedDict):
  """One observation from one station, at one moment. Every measurement is a `QuantitativeValue`, and any of them can be null."""

  station: str
  """URL of the station that reported it."""
  stationId: NotRequired[str]
  """Station identifier, such as `KSEA`."""
  stationName: NotRequired[str]
  """Human-readable station name."""
  timestamp: TimestampIso
  """When the observation was taken."""
  rawMessage: NotRequired[str]
  """The raw METAR the observation was decoded from; empty for stations that do not report one."""
  textDescription: NotRequired[str]
  """Short plain-language summary, such as `Mostly Cloudy`."""
  icon: NotRequired[str | None]
  """URL of a weather icon for the observation."""
  elevation: NotRequired[QuantitativeValue]
  """Station elevation above sea level."""
  presentWeather: NotRequired[list[PresentWeather]]
  """Present-weather groups decoded from the METAR; empty when nothing was reported."""
  temperature: QuantitativeValue
  """Air temperature."""
  dewpoint: QuantitativeValue
  """Dew point."""
  windDirection: NotRequired[QuantitativeValue]
  """Direction the wind is coming from, in degrees clockwise from true north."""
  windSpeed: QuantitativeValue
  """Sustained wind speed."""
  windGust: NotRequired[QuantitativeValue]
  """Peak gust; its `value` is null when there were no gusts."""
  barometricPressure: NotRequired[QuantitativeValue]
  """Station pressure."""
  seaLevelPressure: NotRequired[QuantitativeValue]
  """Pressure reduced to sea level."""
  visibility: NotRequired[QuantitativeValue]
  """Horizontal visibility."""
  maxTemperatureLast24Hours: NotRequired[QuantitativeValue]
  """Highest temperature in the last 24 hours; reported once a day."""
  minTemperatureLast24Hours: NotRequired[QuantitativeValue]
  """Lowest temperature in the last 24 hours; reported once a day."""
  precipitationLastHour: NotRequired[QuantitativeValue]
  """Precipitation accumulated in the last hour."""
  precipitationLast3Hours: NotRequired[QuantitativeValue]
  """Precipitation accumulated in the last three hours."""
  precipitationLast6Hours: NotRequired[QuantitativeValue]
  """Precipitation accumulated in the last six hours."""
  relativeHumidity: NotRequired[QuantitativeValue]
  """Relative humidity."""
  windChill: NotRequired[QuantitativeValue]
  """Wind chill; its `value` is null unless it is cold and windy enough to compute one."""
  heatIndex: NotRequired[QuantitativeValue]
  """Heat index; its `value` is null unless it is hot and humid enough to compute one."""
  cloudLayers: list[CloudLayer]
  """Reported cloud layers, lowest first."""


class RadarRda(TypedDict):
  """Status of the Radar Data Acquisition unit: the radar itself."""

  timestamp: TimestampIso
  """When the status was reported."""
  reportingHost: str
  """Monitoring host that reported it, such as `rdss` or `tdss`."""
  properties: RadarRdaStatus


RadarServerKeywords = TypedDict(
  'RadarServerKeywords', {'@id': str, '@type': NotRequired[Literal['wx:RadarServer']]}
)
"""
  - `@id`: URL of this server.
  - `@type`: Always `wx:RadarServer`.
"""


class RadarServer(RadarServerKeywords):
  """One server of the radar data distribution network, and its health at `collectionTime`."""

  id: str
  """Server name, such as `ldm1` or `rds`. `radar.get_server` takes it."""
  type: str
  """Role of the server. Undocumented; `ldm` (an LDM ingest server) and `distribution` (`rds`, `tds`) on 2026-10-01."""
  active: NotRequired[bool]
  """Whether the server is in service. Only `ldm` servers send it."""
  primary: NotRequired[bool]
  """Whether the server is the primary of its pair. Only `ldm` servers send it."""
  aggregate: NotRequired[bool]
  """Whether the server aggregates the others' feeds. Only `ldm` servers send it."""
  locked: NotRequired[bool]
  """Whether the server is locked against changes. Only `ldm` servers send it."""
  radarNetworkUp: NotRequired[bool]
  """Whether the server sees the radar network as up. Only `ldm` servers send it."""
  collectionTime: TimestampIso
  """When this health report was collected."""
  reportingHost: str
  """Monitoring host that reported it, such as `rdss` or `tdss`."""
  ingestHost: NotRequired[str]
  """Host the server ingests from, such as `dns`."""
  ping: RadarServerPing
  command: NotRequired[RadarServerCommand]
  hardware: NotRequired[RadarServerHardware]
  ldm: NotRequired[RadarServerLdm]
  network: NotRequired[RadarServerNetwork]


class StationFeature(TypedDict):
  """One station, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of this station."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PointGeometry]
  """Where the station is."""
  properties: Station
  """The station itself."""


class ZoneCollection(TypedDict):
  """Zones, as a GeoJSON feature collection, ordered by code."""

  type: Literal['FeatureCollection']
  """Always `FeatureCollection`."""
  features: list[ZoneFeature]
  """The zones."""


class ObservationFeature(TypedDict):
  """One observation, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of this observation."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PointGeometry]
  """Where the station is."""
  properties: Observation
  """The observation itself."""


RadarStationKeywords = TypedDict(
  'RadarStationKeywords', {'@id': str, '@type': NotRequired[Literal['wx:RadarStation']]}
)
"""
  - `@id`: URL of this radar.
  - `@type`: Always `wx:RadarStation`.
"""


class RadarStation(RadarStationKeywords):
  """One radar: what kind it is, how far behind its data runs, and how its hardware is doing."""

  id: str
  """Station identifier, such as `KATX`. `radar.get_station` takes it."""
  name: str
  """Where the radar is, such as `Seattle`."""
  stationType: str
  """Kind of radar. Undocumented; `WSR-88D` (NEXRAD), `TDWR` (terminal Doppler) and `Profiler` on 2026-10-01. `radar.list_stations` filters on it."""
  elevation: NotRequired[QuantitativeValue]
  """Height of the radar above sea level."""
  timeZone: NotRequired[str]
  """Time zone, such as `GMT`."""
  latency: RadarLatency
  rda: RadarRda | None
  """Status of the radar itself."""
  performance: NotRequired[RadarReport | None]
  """The latest performance check. Only `radar.get_station` sends it."""
  adaptation: NotRequired[RadarReport | None]
  """The radar's adaptation (calibration) data. Only `radar.get_station` sends it."""


class StationCollection(TypedDict):
  """Stations, as a GeoJSON feature collection."""

  type: Literal['FeatureCollection']
  """Always `FeatureCollection`."""
  features: list[StationFeature]
  """The stations."""
  observationStations: NotRequired[list[str]]
  """The same stations as bare URLs, in the same order."""
  pagination: NotRequired[CollectionPagination]


class ObservationCollection(TypedDict):
  """Observations over a span, as a GeoJSON feature collection, newest first."""

  type: Literal['FeatureCollection']
  """Always `FeatureCollection`."""
  features: list[ObservationFeature]
  """The observations, newest first."""
  pagination: NotRequired[ObservationPagination]


class RadarStationFeature(TypedDict):
  """One radar, in the GeoJSON feature the API wraps it in."""

  id: str
  """URL of this radar."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: PointGeometry
  """Where the radar is."""
  properties: RadarStation
  """The radar itself."""
