# Generated by truewire — do not edit by hand.
"""Shapes shared by two or more endpoints under the client root, generated from `spec/schemas.json`."""

from typing_extensions import Literal, NotRequired, TypedDict
from truewire_core.types import TimestampIso


class AlertGeocode(TypedDict):
  """The areas covered, as codes rather than prose."""

  SAME: NotRequired[list[str]]
  """SAME (Specific Area Message Encoding) codes, one per county."""
  UGC: NotRequired[list[str]]
  """UGC (Universal Geographic Code) zone codes."""


class AlertReference(TypedDict):
  """An earlier alert this one updates, corrects or cancels."""

  identifier: str
  """Identifier of the referenced alert."""
  sender: NotRequired[str]
  """Who sent the referenced alert."""
  sent: NotRequired[TimestampIso]
  """When the referenced alert was sent."""


class GridValue(TypedDict):
  """One value of a gridded series, and the interval it holds over."""

  validTime: str
  """ISO 8601 interval this value covers, as `<start>/<duration>` -- one string carrying both, such as `2026-09-09T01:00:00+00:00/PT1H`."""
  value: float | None
  """The value over `validTime`."""


class MultiPolygonGeometry(TypedDict):
  """GeoJSON geometry of several disjoint areas -- an alert covering counties that do not touch."""

  type: Literal['MultiPolygon']
  """Always `MultiPolygon`."""
  coordinates: list[list[list[tuple[float, float]]]]
  """One entry per polygon, each shaped like `PolygonGeometry.coordinates`."""


class PointGeometry(TypedDict):
  """GeoJSON geometry of a feature that sits at a single place: a station, an observation, a forecast point."""

  type: Literal['Point']
  """Always `Point` for these features."""
  coordinates: tuple[float, float]
  """A GeoJSON position: longitude first, then latitude, in WGS 84 decimal degrees."""


class PolygonGeometry(TypedDict):
  """GeoJSON geometry of an area: one outer ring, then any holes."""

  type: Literal['Polygon']
  """Always `Polygon`."""
  coordinates: list[list[tuple[float, float]]]
  """Linear rings. The first is the outer boundary; any others are holes in it. Each ring repeats its first position as its last."""


Position = tuple[float, float]


class PresentWeather(TypedDict):
  """One present-weather group decoded from the station's METAR."""

  intensity: NotRequired[str | None]
  """`light`, `heavy`, or null for moderate."""
  modifier: NotRequired[str | None]
  """Qualifier such as `patches` or `blowing`."""
  weather: NotRequired[str | None]
  """The phenomenon itself: `rain`, `snow`, `fog_mist`, `thunderstorms`."""
  rawString: str
  """The METAR group this was decoded from, such as `-RA`."""


class QuantitativeValue(TypedDict):
  """A measurement and the unit it is in. The service never sends a bare number: every value arrives beside the WMO unit code it is expressed in, and `value` is null wherever the measurement is missing rather than zero."""

  unitCode: str
  """WMO unit of measure, as a URI shorthand: `wmoUnit:degC`, `wmoUnit:km_h-1`, `wmoUnit:percent`, `wmoUnit:Pa`, `wmoUnit:m`."""
  value: float | None
  """The measurement, or null where there is none. Null is common and is not an error: an airport station reports `windGust` only when there were gusts."""
  qualityControl: NotRequired[str]
  """Quality-control flag the observation carried: `V` validated, `S` screened, `C` coarse-passed, `Z` preliminary, `Q` questionable. Present on observations, absent on forecasts."""
  maxValue: NotRequired[float]
  """Upper end, where the value is a range rather than a point."""
  minValue: NotRequired[float]
  """Lower end, where the value is a range rather than a point."""


class Alert(TypedDict):
  """One watch, warning or advisory, in the Common Alerting Protocol vocabulary the service issues them in."""

  id: str
  """Identifier of this alert, such as `urn:oid:2.49.0.1.840.0.<hash>.001.1`. This is what `alerts.get_alert` takes."""
  areaDesc: str
  """Semicolon-separated names of the areas covered."""
  geocode: NotRequired[AlertGeocode]
  affectedZones: NotRequired[list[str]]
  """URLs of the forecast zones covered."""
  references: NotRequired[list[AlertReference]]
  """Earlier alerts this one supersedes."""
  sent: TimestampIso
  """When the alert was sent."""
  effective: TimestampIso
  """When it takes effect."""
  onset: NotRequired[TimestampIso | None]
  """When the event itself is expected to begin, if later than `effective`."""
  expires: TimestampIso
  """When the alert expires unless updated."""
  ends: NotRequired[TimestampIso | None]
  """When the event itself is expected to end."""
  status: Literal['Actual', 'Exercise', 'System', 'Test', 'Draft']
  """Whether this is a real alert. Filter on `Actual` unless you want drills."""
  messageType: Literal['Alert', 'Update', 'Cancel', 'Ack', 'Error']
  """Whether this issues, updates or cancels."""
  category: NotRequired[
    Literal[
      'Met',
      'Geo',
      'Safety',
      'Security',
      'Rescue',
      'Fire',
      'Health',
      'Env',
      'Transport',
      'Infra',
      'CBRNE',
      'Other',
    ]
  ]
  """Broad category; `Met` for weather."""
  severity: Literal['Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown']
  """How bad the impact would be."""
  certainty: Literal['Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown']
  """How likely it is to happen."""
  urgency: Literal['Immediate', 'Expected', 'Future', 'Past', 'Unknown']
  """How soon to act."""
  event: str
  """The event name, such as `Flood Watch` or `Red Flag Warning`."""
  sender: NotRequired[str]
  """Email address of the sender."""
  senderName: str
  """The issuing office, such as `NWS Seattle WA`."""
  headline: NotRequired[str | None]
  """One-line summary with the times spelled out."""
  description: str
  """The full text of the alert."""
  instruction: NotRequired[str | None]
  """What the public is being told to do."""
  response: NotRequired[
    Literal[
      'Shelter', 'Evacuate', 'Prepare', 'Execute', 'Avoid', 'Monitor', 'AllClear', 'Assess', 'None'
    ]
  ]
  """The recommended action."""
  parameters: NotRequired[dict[str, list[str]]]
  """Free-form parameters the issuing system attached: `NWSheadline`, `VTEC`, `AWIPSidentifier` and others. Every value is a list, even when it holds one item."""


AlertGeometry = PolygonGeometry | MultiPolygonGeometry | None


class CloudLayer(TypedDict):
  """One reported cloud layer: how much of the sky it covers and how high its base is."""

  base: QuantitativeValue
  amount: Literal['OVC', 'BKN', 'SCT', 'FEW', 'SKC', 'CLR', 'VV']
  """METAR sky-cover code: `OVC` overcast, `BKN` broken, `SCT` scattered, `FEW` few, `SKC`/`CLR` clear, `VV` vertical visibility (sky obscured)."""


class ForecastPeriod(TypedDict):
  """One period of a narrative forecast: a named half-day in the twice-daily forecast, or one hour in the hourly one."""

  number: int
  """Sequence number within the forecast, starting at 1."""
  name: str
  """Name of the period, such as `Tonight` or `Wednesday`. Empty in the hourly forecast, which names nothing."""
  startTime: TimestampIso
  """When the period begins, in the forecast point's own local time."""
  endTime: TimestampIso
  """When the period ends."""
  isDaytime: bool
  """Whether this is a daytime period."""
  temperature: float
  """Forecast temperature, in `temperatureUnit`. A bare number here, unlike everywhere else in this API."""
  temperatureUnit: Literal['F', 'C']
  """Unit `temperature` is in: `F` under `units=us`, `C` under `units=si`."""
  temperatureTrend: NotRequired[str | None]
  """`rising` or `falling` where the temperature moves against the usual daily cycle."""
  probabilityOfPrecipitation: NotRequired[QuantitativeValue]
  dewpoint: NotRequired[QuantitativeValue]
  relativeHumidity: NotRequired[QuantitativeValue]
  windSpeed: str
  """Wind speed as prose with its unit, such as `5 to 10 mph`. A string, not a `QuantitativeValue`."""
  windDirection: str
  """Compass direction the wind comes from, such as `NNE`."""
  icon: NotRequired[str]
  """URL of an icon for the period."""
  shortForecast: str
  """A few words, such as `Partly Sunny`."""
  detailedForecast: str
  """A sentence or two. Empty in the hourly forecast."""


class GridSeries(TypedDict):
  """One gridded series: a unit and a run of intervals, each with its own value. Consecutive intervals with the same value are collapsed into one, so the series is not evenly spaced."""

  uom: NotRequired[str]
  """WMO unit code every value is in."""
  values: list[GridValue]
  """The values, in time order."""


class Station(TypedDict):
  """One observation station."""

  stationIdentifier: str
  """Station identifier, such as `KSEA`. This is what `stations.get_observations` takes."""
  name: str
  """Human-readable station name."""
  timeZone: NotRequired[str]
  """IANA time zone the station is in, such as `America/Los_Angeles`."""
  elevation: NotRequired[QuantitativeValue]
  forecast: NotRequired[str]
  """URL of the forecast zone the station is in."""
  county: NotRequired[str]
  """URL of the county zone the station is in."""
  fireWeatherZone: NotRequired[str]
  """URL of the fire-weather zone the station is in."""
  provider: NotRequired[str]
  """Network the station belongs to, such as `NWS/FAA` or `MesoWest`."""
  subProvider: NotRequired[str]
  """Operator within the network."""


class AlertFeature(TypedDict):
  """One alert, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of this alert."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PolygonGeometry | MultiPolygonGeometry | None]
  """The area an alert covers, when it was drawn as a polygon rather than named as zones."""
  properties: Alert


class GridpointForecast(TypedDict):
  """A narrative forecast for one grid cell, as a list of periods. Named for the service's own term: `/gridpoints/{office}/{x},{y}/forecast` is the gridpoint forecast."""

  units: Literal['us', 'si']
  """Unit system the periods are rendered in."""
  forecastGenerator: NotRequired[str]
  """Which generator produced it, such as `BaselineForecastGenerator`."""
  generatedAt: TimestampIso
  """When this rendering was generated."""
  updateTime: TimestampIso
  """When the underlying grid data was last updated."""
  validTimes: str
  """ISO 8601 interval the forecast covers, as `<start>/<duration>`."""
  elevation: NotRequired[QuantitativeValue]
  periods: list[ForecastPeriod]
  """The forecast periods, in order."""


class Observation(TypedDict):
  """One observation from one station, at one moment. Every measurement is a `QuantitativeValue`, and any of them can be null."""

  station: str
  """URL of the station that reported it."""
  stationId: NotRequired[str]
  """Station identifier, such as `KSEA`."""
  stationName: NotRequired[str]
  """Human-readable station name."""
  timestamp: TimestampIso
  """When the observation was taken."""
  rawMessage: NotRequired[str]
  """The raw METAR the observation was decoded from; empty for stations that do not report one."""
  textDescription: NotRequired[str]
  """Short plain-language summary, such as `Mostly Cloudy`."""
  icon: NotRequired[str | None]
  """URL of a weather icon for the observation."""
  elevation: NotRequired[QuantitativeValue]
  presentWeather: NotRequired[list[PresentWeather]]
  """Present-weather groups decoded from the METAR; empty when nothing was reported."""
  temperature: QuantitativeValue
  dewpoint: QuantitativeValue
  windDirection: NotRequired[QuantitativeValue]
  windSpeed: QuantitativeValue
  windGust: NotRequired[QuantitativeValue]
  barometricPressure: NotRequired[QuantitativeValue]
  seaLevelPressure: NotRequired[QuantitativeValue]
  visibility: NotRequired[QuantitativeValue]
  maxTemperatureLast24Hours: NotRequired[QuantitativeValue]
  minTemperatureLast24Hours: NotRequired[QuantitativeValue]
  precipitationLastHour: NotRequired[QuantitativeValue]
  precipitationLast3Hours: NotRequired[QuantitativeValue]
  precipitationLast6Hours: NotRequired[QuantitativeValue]
  relativeHumidity: NotRequired[QuantitativeValue]
  windChill: NotRequired[QuantitativeValue]
  heatIndex: NotRequired[QuantitativeValue]
  cloudLayers: list[CloudLayer]
  """Reported cloud layers, lowest first."""


class StationFeature(TypedDict):
  """One station, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of this station."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PointGeometry]
  properties: Station


class ObservationFeature(TypedDict):
  """One observation, in the GeoJSON feature the API wraps it in."""

  id: str
  """Canonical URL of this observation."""
  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PointGeometry]
  properties: Observation
