# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import ZoneKind


class ZoneForecastPeriod(TypedDict):
  """One period: a named half-day."""

  number: int
  """Sequence number within the forecast, starting at 1."""
  name: str
  """Name of the period, such as `Tonight` or `Wednesday Night`."""
  detailedForecast: str
  """The forecaster's text for the period."""


class Request(TypedDict):
  """Which zone."""

  zone_id: str
  """Public zone code, such as `WAZ315`."""
  zone_type: ZoneKind
  """The zone type. Only public zones have one, addressed as `forecast`, `public` or `land`; a county, fire or marine zone answers 404."""


class ZoneForecast(TypedDict):
  """The forecast itself."""

  zone: str
  """URL of the zone the forecast is for."""
  updated: TimestampIso
  """When the forecaster issued it."""
  periods: list[ZoneForecastPeriod]
  """The forecast periods, in order."""


class GetForecast(Endpoint):
  """The text forecast for a public forecast zone: the forecaster's narrative, period by period, for the week ahead. Coarser than `forecast.get_forecast`, which renders one grid cell; this is what is read on NOAA Weather Radio for the whole zone."""

  @overload
  async def get_forecast(
    self,
    zone_id: str,
    *,
    zone_type: ZoneKind,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_forecast(
    self,
    zone_id: str,
    *,
    zone_type: ZoneKind,
    validate: bool | None = None,
  ) -> ZoneForecast: ...
  async def get_forecast(
    self,
    zone_id: str,
    *,
    zone_type: ZoneKind,
    validate: bool | None = None,
  ) -> ZoneForecast:
    """The text forecast for a public forecast zone: the forecaster's narrative, period by period, for the week ahead. Coarser than `forecast.get_forecast`, which renders one grid cell; this is what is read on NOAA Weather Radio for the whole zone.

    Args:
      zone_id: Public zone code, such as `WAZ315`.
      zone_type:
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/zone_forecast)
    """
    return await self.request(
      Request(zone_id=zone_id, zone_type=zone_type),
      method='GET',
      path='/zones/{zone_type}/{zone_id}/forecast',
      meta={'payload': 'properties'},
      validate=validate,
      request_type=Request,
      response_type=ZoneForecast,
    )
