# Generated by truewire — do not edit by hand.
from decimal import Decimal
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint


class Request(TypedDict):
  """Which county."""

  zone_type: Literal['county']
  """The zone type. Only `county`: the OpenAPI lists every zone type, but the service refuses any other with a 404 naming `county` as the one value it takes."""
  zone_id: str
  """County code, such as `WAC033`."""


TransmitterKeywords = TypedDict(
  'TransmitterKeywords', {'@id': str, '@type': NotRequired[Literal['wx:Transmitter']]}
)
"""
  - `@id`: URL of the transmitter.
  - `@type`: Always `wx:Transmitter`.
"""


class Transmitter(TransmitterKeywords):
  """One NOAA Weather Radio transmitter."""

  setId: NotRequired[str]
  """Which release of the transmitter list this came from."""
  callSign: str
  """Call sign, such as `KHB60`."""
  transmitterFrequency: Decimal
  """Frequency in MHz, such as `162.550`."""
  siteName: NotRequired[str]
  """Name of the transmitter, such as `Seattle`."""
  siteCity: NotRequired[str]
  """Where the transmitter stands."""
  siteState: NotRequired[str]
  """Two-letter state of the site."""
  sameCodes: NotRequired[list[str]]
  """SAME codes of the counties it broadcasts for: `0`, the FIPS state, the FIPS county, such as `053033`."""
  counties: list[str]
  """County zone codes it broadcasts for, such as `WAC033`, in the order of `sameCodes`."""


TransmitterCollectionKeywords = TypedDict(
  'TransmitterCollectionKeywords', {'@graph': list[Transmitter]}
)
"""
- `@graph`: The transmitters. Each one arrives many times over, identical: 64 copies of each on 2026-09-30.
"""


class TransmitterCollection(TransmitterCollectionKeywords):
  """The transmitters, as a JSON-LD graph."""


class ListTransmitters(Endpoint):
  """The NOAA Weather Radio transmitters that broadcast for a county. JSON-LD, not GeoJSON: the transmitters come as a `@graph`."""

  @overload
  async def list_transmitters(
    self,
    zone_type: Literal['county'] = 'county',
    *,
    zone_id: str,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_transmitters(
    self,
    zone_type: Literal['county'] = 'county',
    *,
    zone_id: str,
    validate: bool | None = None,
  ) -> TransmitterCollection: ...
  async def list_transmitters(
    self,
    zone_type: Literal['county'] = 'county',
    *,
    zone_id: str,
    validate: bool | None = None,
  ) -> TransmitterCollection:
    """The NOAA Weather Radio transmitters that broadcast for a county. JSON-LD, not GeoJSON: the transmitters come as a `@graph`.

    Args:
      zone_type: The zone type. Only `county`: the OpenAPI lists every zone type, but the service refuses any other with a 404 naming `county` as the one value it takes.
      zone_id: County code, such as `WAC033`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/transmitter_zone)
    """
    return await self.request(
      Request(zone_type=zone_type, zone_id=zone_id),
      method='GET',
      path='/zones/{zone_type}/{zone_id}/radio',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=TransmitterCollection,
    )
