//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::GridpointForecast;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RequestUnits {
    #[serde(rename = "us")]
    Us,
    #[serde(rename = "si")]
    Si,
}

/// Which grid cell, and in which units.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`.
    pub office: String,
    /// Grid column, from `points.get_point`.
    pub grid_x: i64,
    /// Grid row, from `points.get_point`.
    pub grid_y: i64,
    /// Unit system for the rendered temperatures: `us` for Fahrenheit and miles per hour, `si` for Celsius and kilometres per hour. Defaults to `us`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub units: Option<RequestUnits>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The hourly forecast for one grid cell: one period per hour for about the next week, carrying dew point and relative humidity the twice-daily forecast leaves out, and no prose.
#[derive(Clone)]
pub struct GetHourlyForecast {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetHourlyForecast {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The hourly forecast for one grid cell: one period per hour for about the next week, carrying dew point and relative humidity the twice-daily forecast leaves out, and no prose.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast_hourly>.
    pub async fn get_hourly_forecast(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<GridpointForecast> {
        let raw = self.get_hourly_forecast_raw(request, options).await?;
        decode(raw)
    }

    /// `get_hourly_forecast` without validation: the wire body as it came.
    pub async fn get_hourly_forecast_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta {
            payload: Some("properties".to_string()),
        };
        let call = HttpCall {
            method: Some("GET"),
            path: "/gridpoints/{office}/{grid_x},{grid_y}/forecast/hourly",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
