//! Generated by truewire — do not edit by hand.

pub mod get_forecast;
pub mod get_grid_data;
pub mod get_hourly_forecast;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::GridpointForecast;

/// Forecasts for one grid cell: the twice-daily narrative, the hourly series, and the raw gridded data both are rendered from.
///
/// See <https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast>.
#[derive(Clone)]
pub struct Forecast {
    get_forecast: get_forecast::GetForecast,
    get_grid_data: get_grid_data::GetGridData,
    get_hourly_forecast: get_hourly_forecast::GetHourlyForecast,
}

impl Forecast {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_forecast: get_forecast::GetForecast::new(core.clone()),
            get_grid_data: get_grid_data::GetGridData::new(core.clone()),
            get_hourly_forecast: get_hourly_forecast::GetHourlyForecast::new(core),
        }
    }

    /// The twice-daily narrative forecast for one grid cell: about a dozen named periods (`Tonight`, `Wednesday`, `Wednesday Night`) covering the next week, each with a temperature, a wind, and a sentence of prose.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast>.
    pub async fn get_forecast(
        &self,
        request: get_forecast::Request,
        options: CallOptions,
    ) -> Result<GridpointForecast> {
        self.get_forecast.get_forecast(request, options).await
    }

    /// `get_forecast` without validation: the wire body as it came.
    pub async fn get_forecast_raw(
        &self,
        request: get_forecast::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_forecast.get_forecast_raw(request, options).await
    }

    /// The raw gridded forecast for one cell: the seventy-odd series the narrative forecasts are rendered from, each a run of intervals with its own unit. This is the endpoint to reach for when the prose is not enough -- a snow-load calculation wants `snowfallAmount`, not `Snow likely, with 2 to 4 inches possible`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/gridpoint>.
    pub async fn get_grid_data(
        &self,
        request: get_grid_data::Request,
        options: CallOptions,
    ) -> Result<get_grid_data::GridData> {
        self.get_grid_data.get_grid_data(request, options).await
    }

    /// `get_grid_data` without validation: the wire body as it came.
    pub async fn get_grid_data_raw(
        &self,
        request: get_grid_data::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_grid_data.get_grid_data_raw(request, options).await
    }

    /// The hourly forecast for one grid cell: one period per hour for about the next week, carrying dew point and relative humidity the twice-daily forecast leaves out, and no prose.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast_hourly>.
    pub async fn get_hourly_forecast(
        &self,
        request: get_hourly_forecast::Request,
        options: CallOptions,
    ) -> Result<GridpointForecast> {
        self.get_hourly_forecast
            .get_hourly_forecast(request, options)
            .await
    }

    /// `get_hourly_forecast` without validation: the wire body as it came.
    pub async fn get_hourly_forecast_raw(
        &self,
        request: get_hourly_forecast::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_hourly_forecast
            .get_hourly_forecast_raw(request, options)
            .await
    }
}
