// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { GridpointForecast } from '../types/index.js'

/** Which grid cell, and in which units. */
export interface Request {
  /** Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`. */
  office: string
  /** Grid column, from `points.get_point`. */
  grid_x: number
  /** Grid row, from `points.get_point`. */
  grid_y: number
  /** Unit system for the rendered temperatures: `us` for Fahrenheit and miles per hour, `si` for Celsius and kilometres per hour. Defaults to `us`. */
  units?: 'us' | 'si'
}

export const Request: Codec<Request> = t.object({
  office: t.string,
  grid_x: t.integer,
  grid_y: t.integer,
  units: t.optional(t.literal('us', 'si')),
})

/** The twice-daily narrative forecast for one grid cell: about a dozen named periods (`Tonight`, `Wednesday`, `Wednesday Night`) covering the next week, each with a temperature, a wind, and a sentence of prose. */
export class GetForecast {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getForecast(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The twice-daily narrative forecast for one grid cell: about a dozen named periods (`Tonight`, `Wednesday`, `Wednesday Night`) covering the next week, each with a temperature, a wind, and a sentence of prose.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast
   */
  getForecast(request: Request, options?: CallOptions): Promise<GridpointForecast>
  async getForecast(request: Request, options?: CallOptions): Promise<GridpointForecast> {
    return this.core.request({
      method: 'GET',
      path: '/gridpoints/{office}/{grid_x},{grid_y}/forecast',
      request,
      requestCodec: Request,
      responseCodec: GridpointForecast,
      meta: { payload: 'properties' },
      ...options,
    })
  }
}
