//! Generated by truewire — do not edit by hand.
//!
//! Shapes shared by two or more endpoints, generated from `spec/schemas.json`.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};
use truewire_core::{serde_json, TimestampIso};

/// The areas covered, as codes rather than prose.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AlertGeocode {
    /// SAME (Specific Area Message Encoding) codes, one per county.
    #[serde(rename = "SAME", default, skip_serializing_if = "Option::is_none")]
    pub same: Option<Vec<String>>,
    /// UGC (Universal Geographic Code) zone codes.
    #[serde(rename = "UGC", default, skip_serializing_if = "Option::is_none")]
    pub ugc: Option<Vec<String>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// An earlier alert this one updates, corrects or cancels.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct AlertReference {
    /// Identifier of the referenced alert.
    pub identifier: String,
    /// Who sent the referenced alert.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    /// When the referenced alert was sent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sent: Option<TimestampIso>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One value of a gridded series, and the interval it holds over.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GridValue {
    /// ISO 8601 interval this value covers, as `<start>/<duration>` -- one string carrying both, such as `2026-09-09T01:00:00+00:00/PT1H`.
    #[serde(rename = "validTime")]
    pub valid_time: String,
    /// The value over `validTime`.
    pub value: Option<f64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MultiPolygonGeometryType {
    MultiPolygon,
}

/// GeoJSON geometry of several disjoint areas -- an alert covering counties that do not touch.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MultiPolygonGeometry {
    /// Always `MultiPolygon`.
    #[serde(rename = "type")]
    pub type_: MultiPolygonGeometryType,
    /// One entry per polygon, each shaped like `PolygonGeometry.coordinates`.
    pub coordinates: Vec<Vec<Vec<(f64, f64)>>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PointGeometryType {
    Point,
}

/// GeoJSON geometry of a feature that sits at a single place: a station, an observation, a forecast point.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PointGeometry {
    /// Always `Point` for these features.
    #[serde(rename = "type")]
    pub type_: PointGeometryType,
    /// A GeoJSON position: longitude first, then latitude, in WGS 84 decimal degrees.
    pub coordinates: (f64, f64),
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PolygonGeometryType {
    Polygon,
}

/// GeoJSON geometry of an area: one outer ring, then any holes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PolygonGeometry {
    /// Always `Polygon`.
    #[serde(rename = "type")]
    pub type_: PolygonGeometryType,
    /// Linear rings. The first is the outer boundary; any others are holes in it. Each ring repeats its first position as its last.
    pub coordinates: Vec<Vec<(f64, f64)>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

pub type Position = (f64, f64);

/// One present-weather group decoded from the station's METAR.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct PresentWeather {
    /// `light`, `heavy`, or null for moderate.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub intensity: Option<Option<String>>,
    /// Qualifier such as `patches` or `blowing`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub modifier: Option<Option<String>>,
    /// The phenomenon itself: `rain`, `snow`, `fog_mist`, `thunderstorms`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub weather: Option<Option<String>>,
    /// The METAR group this was decoded from, such as `-RA`.
    #[serde(rename = "rawString")]
    pub raw_string: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// A measurement and the unit it is in. The service never sends a bare number: every value arrives beside the WMO unit code it is expressed in, and `value` is null wherever the measurement is missing rather than zero.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct QuantitativeValue {
    /// WMO unit of measure, as a URI shorthand: `wmoUnit:degC`, `wmoUnit:km_h-1`, `wmoUnit:percent`, `wmoUnit:Pa`, `wmoUnit:m`.
    #[serde(rename = "unitCode")]
    pub unit_code: String,
    /// The measurement, or null where there is none. Null is common and is not an error: an airport station reports `windGust` only when there were gusts.
    pub value: Option<f64>,
    /// Quality-control flag the observation carried: `V` validated, `S` screened, `C` coarse-passed, `Z` preliminary, `Q` questionable. Present on observations, absent on forecasts.
    #[serde(
        rename = "qualityControl",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub quality_control: Option<String>,
    /// Upper end, where the value is a range rather than a point.
    #[serde(rename = "maxValue", default, skip_serializing_if = "Option::is_none")]
    pub max_value: Option<f64>,
    /// Lower end, where the value is a range rather than a point.
    #[serde(rename = "minValue", default, skip_serializing_if = "Option::is_none")]
    pub min_value: Option<f64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertStatus {
    Actual,
    Exercise,
    System,
    Test,
    Draft,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertMessageType {
    Alert,
    Update,
    Cancel,
    Ack,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertCategory {
    Met,
    Geo,
    Safety,
    Security,
    Rescue,
    Fire,
    Health,
    Env,
    Transport,
    Infra,
    #[serde(rename = "CBRNE")]
    Cbrne,
    Other,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertSeverity {
    Extreme,
    Severe,
    Moderate,
    Minor,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertCertainty {
    Observed,
    Likely,
    Possible,
    Unlikely,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertUrgency {
    Immediate,
    Expected,
    Future,
    Past,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertResponse {
    Shelter,
    Evacuate,
    Prepare,
    Execute,
    Avoid,
    Monitor,
    AllClear,
    Assess,
    None,
}

/// One watch, warning or advisory, in the Common Alerting Protocol vocabulary the service issues them in.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Alert {
    /// Identifier of this alert, such as `urn:oid:2.49.0.1.840.0.<hash>.001.1`. This is what `alerts.get_alert` takes.
    pub id: String,
    /// Semicolon-separated names of the areas covered.
    #[serde(rename = "areaDesc")]
    pub area_desc: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geocode: Option<AlertGeocode>,
    /// URLs of the forecast zones covered.
    #[serde(
        rename = "affectedZones",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub affected_zones: Option<Vec<String>>,
    /// Earlier alerts this one supersedes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub references: Option<Vec<AlertReference>>,
    /// When the alert was sent.
    pub sent: TimestampIso,
    /// When it takes effect.
    pub effective: TimestampIso,
    /// When the event itself is expected to begin, if later than `effective`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub onset: Option<Option<TimestampIso>>,
    /// When the alert expires unless updated.
    pub expires: TimestampIso,
    /// When the event itself is expected to end.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub ends: Option<Option<TimestampIso>>,
    /// Whether this is a real alert. Filter on `Actual` unless you want drills.
    pub status: AlertStatus,
    /// Whether this issues, updates or cancels.
    #[serde(rename = "messageType")]
    pub message_type: AlertMessageType,
    /// Broad category; `Met` for weather.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<AlertCategory>,
    /// How bad the impact would be.
    pub severity: AlertSeverity,
    /// How likely it is to happen.
    pub certainty: AlertCertainty,
    /// How soon to act.
    pub urgency: AlertUrgency,
    /// The event name, such as `Flood Watch` or `Red Flag Warning`.
    pub event: String,
    /// Email address of the sender.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sender: Option<String>,
    /// The issuing office, such as `NWS Seattle WA`.
    #[serde(rename = "senderName")]
    pub sender_name: String,
    /// One-line summary with the times spelled out.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub headline: Option<Option<String>>,
    /// The full text of the alert.
    pub description: String,
    /// What the public is being told to do.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub instruction: Option<Option<String>>,
    /// The recommended action.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<AlertResponse>,
    /// Free-form parameters the issuing system attached: `NWSheadline`, `VTEC`, `AWIPSidentifier` and others. Every value is a list, even when it holds one item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<HashMap<String, Vec<String>>>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AlertGeometryValue {
    PolygonGeometry(PolygonGeometry),
    MultiPolygonGeometry(MultiPolygonGeometry),
}

pub type AlertGeometry = Option<AlertGeometryValue>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum CloudLayerAmount {
    #[serde(rename = "OVC")]
    Ovc,
    #[serde(rename = "BKN")]
    Bkn,
    #[serde(rename = "SCT")]
    Sct,
    #[serde(rename = "FEW")]
    Few,
    #[serde(rename = "SKC")]
    Skc,
    #[serde(rename = "CLR")]
    Clr,
    #[serde(rename = "VV")]
    Vv,
}

/// One reported cloud layer: how much of the sky it covers and how high its base is.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CloudLayer {
    pub base: QuantitativeValue,
    /// METAR sky-cover code: `OVC` overcast, `BKN` broken, `SCT` scattered, `FEW` few, `SKC`/`CLR` clear, `VV` vertical visibility (sky obscured).
    pub amount: CloudLayerAmount,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ForecastPeriodTemperatureUnit {
    F,
    C,
}

/// One period of a narrative forecast: a named half-day in the twice-daily forecast, or one hour in the hourly one.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ForecastPeriod {
    /// Sequence number within the forecast, starting at 1.
    pub number: i64,
    /// Name of the period, such as `Tonight` or `Wednesday`. Empty in the hourly forecast, which names nothing.
    pub name: String,
    /// When the period begins, in the forecast point's own local time.
    #[serde(rename = "startTime")]
    pub start_time: TimestampIso,
    /// When the period ends.
    #[serde(rename = "endTime")]
    pub end_time: TimestampIso,
    /// Whether this is a daytime period.
    #[serde(rename = "isDaytime")]
    pub is_daytime: bool,
    /// Forecast temperature, in `temperatureUnit`. A bare number here, unlike everywhere else in this API.
    pub temperature: f64,
    /// Unit `temperature` is in: `F` under `units=us`, `C` under `units=si`.
    #[serde(rename = "temperatureUnit")]
    pub temperature_unit: ForecastPeriodTemperatureUnit,
    /// `rising` or `falling` where the temperature moves against the usual daily cycle.
    #[serde(
        rename = "temperatureTrend",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    #[serde(with = "truewire_core::validation::double_option")]
    pub temperature_trend: Option<Option<String>>,
    #[serde(
        rename = "probabilityOfPrecipitation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub probability_of_precipitation: Option<QuantitativeValue>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dewpoint: Option<QuantitativeValue>,
    #[serde(
        rename = "relativeHumidity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub relative_humidity: Option<QuantitativeValue>,
    /// Wind speed as prose with its unit, such as `5 to 10 mph`. A string, not a `QuantitativeValue`.
    #[serde(rename = "windSpeed")]
    pub wind_speed: String,
    /// Compass direction the wind comes from, such as `NNE`.
    #[serde(rename = "windDirection")]
    pub wind_direction: String,
    /// URL of an icon for the period.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    /// A few words, such as `Partly Sunny`.
    #[serde(rename = "shortForecast")]
    pub short_forecast: String,
    /// A sentence or two. Empty in the hourly forecast.
    #[serde(rename = "detailedForecast")]
    pub detailed_forecast: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One gridded series: a unit and a run of intervals, each with its own value. Consecutive intervals with the same value are collapsed into one, so the series is not evenly spaced.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GridSeries {
    /// WMO unit code every value is in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
    /// The values, in time order.
    pub values: Vec<GridValue>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One observation station.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Station {
    /// Station identifier, such as `KSEA`. This is what `stations.get_observations` takes.
    #[serde(rename = "stationIdentifier")]
    pub station_identifier: String,
    /// Human-readable station name.
    pub name: String,
    /// IANA time zone the station is in, such as `America/Los_Angeles`.
    #[serde(rename = "timeZone", default, skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elevation: Option<QuantitativeValue>,
    /// URL of the forecast zone the station is in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub forecast: Option<String>,
    /// URL of the county zone the station is in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    /// URL of the fire-weather zone the station is in.
    #[serde(
        rename = "fireWeatherZone",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub fire_weather_zone: Option<String>,
    /// Network the station belongs to, such as `NWS/FAA` or `MesoWest`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Operator within the network.
    #[serde(
        rename = "subProvider",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sub_provider: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AlertFeatureType {
    Feature,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AlertFeatureGeometry {
    PolygonGeometry(PolygonGeometry),
    MultiPolygonGeometry(MultiPolygonGeometry),
}

/// One alert, in the GeoJSON feature the API wraps it in.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AlertFeature {
    /// Canonical URL of this alert.
    pub id: String,
    /// Always `Feature`.
    #[serde(rename = "type")]
    pub type_: AlertFeatureType,
    /// The area an alert covers, when it was drawn as a polygon rather than named as zones.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub geometry: Option<Option<AlertFeatureGeometry>>,
    pub properties: Alert,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GridpointForecastUnits {
    #[serde(rename = "us")]
    Us,
    #[serde(rename = "si")]
    Si,
}

/// A narrative forecast for one grid cell, as a list of periods. Named for the service's own term: `/gridpoints/{office}/{x},{y}/forecast` is the gridpoint forecast.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GridpointForecast {
    /// Unit system the periods are rendered in.
    pub units: GridpointForecastUnits,
    /// Which generator produced it, such as `BaselineForecastGenerator`.
    #[serde(
        rename = "forecastGenerator",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub forecast_generator: Option<String>,
    /// When this rendering was generated.
    #[serde(rename = "generatedAt")]
    pub generated_at: TimestampIso,
    /// When the underlying grid data was last updated.
    #[serde(rename = "updateTime")]
    pub update_time: TimestampIso,
    /// ISO 8601 interval the forecast covers, as `<start>/<duration>`.
    #[serde(rename = "validTimes")]
    pub valid_times: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elevation: Option<QuantitativeValue>,
    /// The forecast periods, in order.
    pub periods: Vec<ForecastPeriod>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One observation from one station, at one moment. Every measurement is a `QuantitativeValue`, and any of them can be null.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Observation {
    /// URL of the station that reported it.
    pub station: String,
    /// Station identifier, such as `KSEA`.
    #[serde(rename = "stationId", default, skip_serializing_if = "Option::is_none")]
    pub station_id: Option<String>,
    /// Human-readable station name.
    #[serde(
        rename = "stationName",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub station_name: Option<String>,
    /// When the observation was taken.
    pub timestamp: TimestampIso,
    /// The raw METAR the observation was decoded from; empty for stations that do not report one.
    #[serde(
        rename = "rawMessage",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub raw_message: Option<String>,
    /// Short plain-language summary, such as `Mostly Cloudy`.
    #[serde(
        rename = "textDescription",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub text_description: Option<String>,
    /// URL of a weather icon for the observation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(with = "truewire_core::validation::double_option")]
    pub icon: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elevation: Option<QuantitativeValue>,
    /// Present-weather groups decoded from the METAR; empty when nothing was reported.
    #[serde(
        rename = "presentWeather",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub present_weather: Option<Vec<PresentWeather>>,
    pub temperature: QuantitativeValue,
    pub dewpoint: QuantitativeValue,
    #[serde(
        rename = "windDirection",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub wind_direction: Option<QuantitativeValue>,
    #[serde(rename = "windSpeed")]
    pub wind_speed: QuantitativeValue,
    #[serde(rename = "windGust", default, skip_serializing_if = "Option::is_none")]
    pub wind_gust: Option<QuantitativeValue>,
    #[serde(
        rename = "barometricPressure",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub barometric_pressure: Option<QuantitativeValue>,
    #[serde(
        rename = "seaLevelPressure",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub sea_level_pressure: Option<QuantitativeValue>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub visibility: Option<QuantitativeValue>,
    #[serde(
        rename = "maxTemperatureLast24Hours",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub max_temperature_last24_hours: Option<QuantitativeValue>,
    #[serde(
        rename = "minTemperatureLast24Hours",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub min_temperature_last24_hours: Option<QuantitativeValue>,
    #[serde(
        rename = "precipitationLastHour",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub precipitation_last_hour: Option<QuantitativeValue>,
    #[serde(
        rename = "precipitationLast3Hours",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub precipitation_last3_hours: Option<QuantitativeValue>,
    #[serde(
        rename = "precipitationLast6Hours",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub precipitation_last6_hours: Option<QuantitativeValue>,
    #[serde(
        rename = "relativeHumidity",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub relative_humidity: Option<QuantitativeValue>,
    #[serde(rename = "windChill", default, skip_serializing_if = "Option::is_none")]
    pub wind_chill: Option<QuantitativeValue>,
    #[serde(rename = "heatIndex", default, skip_serializing_if = "Option::is_none")]
    pub heat_index: Option<QuantitativeValue>,
    /// Reported cloud layers, lowest first.
    #[serde(rename = "cloudLayers")]
    pub cloud_layers: Vec<CloudLayer>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum StationFeatureType {
    Feature,
}

/// One station, in the GeoJSON feature the API wraps it in.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct StationFeature {
    /// Canonical URL of this station.
    pub id: String,
    /// Always `Feature`.
    #[serde(rename = "type")]
    pub type_: StationFeatureType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geometry: Option<PointGeometry>,
    pub properties: Station,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ObservationFeatureType {
    Feature,
}

/// One observation, in the GeoJSON feature the API wraps it in.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ObservationFeature {
    /// Canonical URL of this observation.
    pub id: String,
    /// Always `Feature`.
    #[serde(rename = "type")]
    pub type_: ObservationFeatureType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geometry: Option<PointGeometry>,
    pub properties: Observation,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}
