// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Where the office is. */
export interface OfficeAddress {
  /** Street address. */
  streetAddress?: string
  /** City. */
  addressLocality?: string
  /** Two-letter state code. */
  addressRegion?: string
  /** ZIP code. */
  postalCode?: string
}

export const OfficeAddress: Codec<OfficeAddress> = t.object({
  streetAddress: t.optional(t.string),
  addressLocality: t.optional(t.string),
  addressRegion: t.optional(t.string),
  postalCode: t.optional(t.string),
})

/** Which office. */
export interface Request {
  /** Three-letter office code, such as `SEW`. `points.get_point` returns it as `gridId`. */
  office_id: string
}

export const Request: Codec<Request> = t.object({
  office_id: t.string,
})

/** The office. A schema.org `GovernmentOrganization`, not a GeoJSON feature -- this corner of the API answers in a different vocabulary from the rest of it. */
export interface Office {
  /** Office code, such as `SEW`. */
  id: string
  /** Office name, such as `Seattle/Tacoma, WA`. */
  name: string
  address?: OfficeAddress
  /** Public telephone number. */
  telephone?: string
  /** Fax number; often empty. */
  faxNumber?: string
  /** Webmaster address. */
  email?: string
  /** The office's own website. */
  sameAs?: string
  /** Region the office belongs to, such as `wr` for Western. */
  nwsRegion?: string
  /** URL of the regional headquarters. */
  parentOrganization?: string
  /** URLs of the county zones the office covers. */
  responsibleCounties?: string[]
  /** URLs of the forecast zones the office covers. */
  responsibleForecastZones?: string[]
  /** URLs of the fire-weather zones the office covers. */
  responsibleFireZones?: string[]
  /** URLs of the stations the office draws observations from. */
  approvedObservationStations?: string[]
}

export const Office: Codec<Office> = t.object({
  id: t.string,
  name: t.string,
  address: t.optional(OfficeAddress),
  telephone: t.optional(t.string),
  faxNumber: t.optional(t.string),
  email: t.optional(t.string),
  sameAs: t.optional(t.string),
  nwsRegion: t.optional(t.string),
  parentOrganization: t.optional(t.string),
  responsibleCounties: t.optional(t.array(t.string)),
  responsibleForecastZones: t.optional(t.array(t.string)),
  responsibleFireZones: t.optional(t.array(t.string)),
  approvedObservationStations: t.optional(t.array(t.string)),
})

/** One weather forecast office: who to contact, and everything it is responsible for. */
export class GetOffice {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getOffice(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One weather forecast office: who to contact, and everything it is responsible for.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/office
   */
  getOffice(request: Request, options?: CallOptions): Promise<Office>
  async getOffice(request: Request, options?: CallOptions): Promise<Office> {
    return this.core.request({
      method: 'GET',
      path: '/offices/{office_id}',
      request,
      requestCodec: Request,
      responseCodec: Office,
      meta: {},
      ...options,
    })
  }
}
