// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { OfficeHeadline } from '../types/index.js'

/** Which office, and which headline. */
export interface Request {
  /** Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`. */
  office_id: string
  /** Headline id, such as `058e41fd34b935b395e9aaf0fe175dc9`. `offices.list_headlines` returns it as `id`. */
  headline_id: string
}

export const Request: Codec<Request> = t.object({
  office_id: t.string,
  headline_id: t.string,
})

/** One news headline an office has posted. */
export class GetHeadline {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getHeadline(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One news headline an office has posted.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/office_headline
   */
  getHeadline(request: Request, options?: CallOptions & { validate?: true }): Promise<OfficeHeadline>
  /** When validation may be disabled, returned values are typed `unknown`. */
  getHeadline(request: Request, options?: CallOptions): Promise<unknown>
  async getHeadline(request: Request, options?: CallOptions): Promise<OfficeHeadline> {
    return this.core.request({
      method: 'GET',
      path: '/offices/{office_id}/headlines/{headline_id}',
      request,
      requestCodec: Request,
      responseCodec: OfficeHeadline,
      meta: {},
      ...options,
    })
  }
}
