// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { OfficeHeadline } from '../types/index.js'

/** Which office. */
export interface Request {
  /** Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`. */
  office_id: string
}

export const Request: Codec<Request> = t.object({
  office_id: t.string,
})

/** The headlines, as a JSON-LD graph. */
export interface OfficeHeadlineCollection {
  /** The headlines. Empty for an office that has posted none. */
  '@graph': OfficeHeadline[]
}

export const OfficeHeadlineCollection: Codec<OfficeHeadlineCollection> = t.object({
  '@graph': t.array(OfficeHeadline),
})

/** The news headlines an office has posted. */
export class ListHeadlines {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listHeadlines(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The news headlines an office has posted.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/office_headlines
   */
  listHeadlines(request: Request, options?: CallOptions & { validate?: true }): Promise<OfficeHeadlineCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  listHeadlines(request: Request, options?: CallOptions): Promise<unknown>
  async listHeadlines(request: Request, options?: CallOptions): Promise<OfficeHeadlineCollection> {
    return this.core.request({
      method: 'GET',
      path: '/offices/{office_id}/headlines',
      request,
      requestCodec: Request,
      responseCodec: OfficeHeadlineCollection,
      meta: {},
      ...options,
    })
  }
}
