// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, type TimestampIso, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Which office. */
export interface Request {
  /** Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`. */
  office_id: string
}

export const Request: Codec<Request> = t.object({
  office_id: t.string,
})

/** One weather story: a graphic, and the text that goes with it. */
export interface WeatherStory {
  /** Code of the office that issued it, such as `AKQ`. */
  officeId: string
  /** When the story took effect. */
  startTime: TimestampIso
  /** When it stops being current. */
  endTime: TimestampIso
  /** When it was last updated. */
  updateTime: TimestampIso
  /** Title, such as `Today's Forecast`. */
  title: string
  /** The story as plain text. */
  description: string
  /** Alternative text for the graphic. */
  altText: string
  /** Whether the office flagged it as a priority. */
  priority: boolean
  /** Where the office places it among its stories, lowest first. */
  order: number
  /** URL of the graphic. The service answers only an image there, so no endpoint here fetches it. Null on a few stories: 3 of 252 across every office on 2026-09-30. */
  download: string | null
}

export const WeatherStory: Codec<WeatherStory> = t.object({
  officeId: t.string,
  startTime: t.dateTime,
  endTime: t.dateTime,
  updateTime: t.dateTime,
  title: t.string,
  description: t.string,
  altText: t.string,
  priority: t.boolean,
  order: t.integer,
  download: t.nullable(t.string),
})

/** The office's active weather stories. */
export interface WeatherStoryCollection {
  /** The stories. Empty for an office that has none active. */
  stories: WeatherStory[]
}

export const WeatherStoryCollection: Codec<WeatherStoryCollection> = t.object({
  stories: t.array(WeatherStory),
})

/** The weather stories an office has active: the forecast graphics on the front of its website, each with its text. */
export class ListWeatherStories {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listWeatherStories(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The weather stories an office has active: the forecast graphics on the front of its website, each with its text.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/office_weatherstory
   */
  listWeatherStories(request: Request, options?: CallOptions & { validate?: true }): Promise<WeatherStoryCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  listWeatherStories(request: Request, options?: CallOptions): Promise<unknown>
  async listWeatherStories(request: Request, options?: CallOptions): Promise<WeatherStoryCollection> {
    return this.core.request({
      method: 'GET',
      path: '/offices/{office_id}/weatherstories',
      request,
      requestCodec: Request,
      responseCodec: WeatherStoryCollection,
      meta: {},
      ...options,
    })
  }
}
