//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::RadarStationFeature;

/// Which radar.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Station identifier, such as `KATX`. `radar.list_stations` returns it as `properties.id`.
    pub station_id: String,
    /// Monitoring host to report status and latency from. `rdss` is the only one the service knew on 2026-10-01.
    #[serde(
        rename = "reportingHost",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reporting_host: Option<String>,
    /// LDM host to measure `latency` at, such as `ldm1`. Without it, `ldm4` on 2026-10-01; a host the service does not know answers a `latency` of nulls.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports.
#[derive(Clone)]
pub struct GetStation {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetStation {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/radar_station>.
    pub async fn get_station(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<RadarStationFeature> {
        let raw = self.get_station_raw(request, options).await?;
        decode(raw)
    }

    /// `get_station` without validation: the wire body as it came.
    pub async fn get_station_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/radar/stations/{station_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
