//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

pub type RadarProfiler = serde_json::Value;

/// Which profiler, and over what time.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Profiler station identifier, such as `TLKA2`. `radar.list_stations` with a `station_type` of `Profiler` lists them.
    pub station_id: String,
    /// Time interval, in ISO 8601: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT1H`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// Averaging interval, as an ISO 8601 duration such as `PT1H`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Metadata about one radar wind profiler, as JSON-LD. Unverified: every profiler answered 404 on 2026-10-01, so the response is not described.
#[derive(Clone)]
pub struct GetProfiler {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetProfiler {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// Metadata about one radar wind profiler, as JSON-LD. Unverified: every profiler answered 404 on 2026-10-01, so the response is not described.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/radar_profiler>.
    pub async fn get_profiler(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<RadarProfiler> {
        let raw = self.get_profiler_raw(request, options).await?;
        decode(raw)
    }

    /// `get_profiler` without validation: the wire body as it came.
    pub async fn get_profiler_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/radar/profilers/{station_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
