//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::RadarServer;

/// Which servers. The filter is optional.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Monitoring host to report from: `rdss` or `tdss` on 2026-10-01, the two the service knew. Without it, the service picks one; any other value answers an empty `@graph`.
    #[serde(
        rename = "reportingHost",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub reporting_host: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The servers, as a JSON-LD graph.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RadarServerCollection {
    /// The servers.
    #[serde(rename = "@graph")]
    pub graph: Vec<RadarServer>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The servers of the radar data distribution network -- the LDM servers that ingest NEXRAD data and the hosts that serve it on -- each with its health. JSON-LD: the servers come as a `@graph`.
#[derive(Clone)]
pub struct ListServers {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListServers {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The servers of the radar data distribution network -- the LDM servers that ingest NEXRAD data and the hosts that serve it on -- each with its health. JSON-LD: the servers come as a `@graph`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/radar_servers>.
    pub async fn list_servers(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<RadarServerCollection> {
        let raw = self.list_servers_raw(request, options).await?;
        decode(raw)
    }

    /// `list_servers` without validation: the wire body as it came.
    pub async fn list_servers_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/radar/servers",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
