//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::DefaultMeta;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RadarAlarmType {
    #[serde(rename = "wx:RadarStationAlarm")]
    WxRadarStationAlarm,
}

/// One alarm message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RadarAlarm {
    /// Always `wx:RadarStationAlarm`.
    #[serde(rename = "@type")]
    pub type_: RadarAlarmType,
    /// The radar, such as `KATX`.
    #[serde(rename = "stationId")]
    pub station_id: String,
    /// Alarm class. Undocumented, so not enumerated; on 2026-10-01 the 208 radars' logs held `cleared`, `required`, `secondary`, `mandatory` and `inoperative`.
    pub status: String,
    /// Redundant channel the alarm came from: `0`, `1` or `2` on 2026-10-01.
    #[serde(rename = "activeChannel")]
    pub active_channel: i64,
    /// The alarm text, such as `RPG LINK INITIALIZATION ERROR`.
    pub message: String,
    /// When the alarm was raised or cleared.
    pub timestamp: TimestampIso,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Which radar.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Station identifier, such as `KATX`. A profiler, or any radar with no log, answers an empty `@graph`.
    pub station_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The alarms, as a JSON-LD graph.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RadarAlarmCollection {
    /// URL of this alarm log.
    #[serde(rename = "@id", default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The alarms, newest first.
    #[serde(rename = "@graph")]
    pub graph: Vec<RadarAlarm>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The alarm log of one radar: each alarm the radar raised or cleared, newest first. JSON-LD: the alarms come as a `@graph`.
#[derive(Clone)]
pub struct ListStationAlarms {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListStationAlarms {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The alarm log of one radar: each alarm the radar raised or cleared, newest first. JSON-LD: the alarms come as a `@graph`.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/radar_station_alarms>.
    pub async fn list_station_alarms(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<RadarAlarmCollection> {
        let raw = self.list_station_alarms_raw(request, options).await?;
        decode(raw)
    }

    /// `list_station_alarms` without validation: the wire body as it came.
    pub async fn list_station_alarms_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/radar/stations/{station_id}/alarms",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
