# Generated by truewire — do not edit by hand.
from .get_queue import GetQueue
from .get_server import GetServer
from .get_station import GetStation
from .list_servers import ListServers
from .list_spgds import ListSpgds
from .list_station_alarms import ListStationAlarms
from .list_stations import ListStations


class Radar(
  GetQueue, GetServer, GetStation, ListServers, ListSpgds, ListStationAlarms, ListStations
):
  """The radar network: the NEXRAD, TDWR and profiler radars, their status and alarms, and the servers and queues that distribute their Level II data.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/radar_stations)
  """
