# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import RadarStationFeature


class Request(TypedDict):
  """Which radar."""

  station_id: str
  """Station identifier, such as `KATX`. `radar.list_stations` returns it as `properties.id`."""
  reportingHost: NotRequired[str]
  """Monitoring host to report status and latency from. `rdss` is the only one the service knew on 2026-10-01."""
  host: NotRequired[str]
  """LDM host to measure `latency` at, such as `ldm1`. Without it, `ldm4` on 2026-10-01; a host the service does not know answers a `latency` of nulls."""


class GetStation(Endpoint):
  """One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports."""

  @overload
  async def get_station(
    self,
    *,
    station_id: str,
    reporting_host: str | None = None,
    host: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_station(
    self,
    *,
    station_id: str,
    reporting_host: str | None = None,
    host: str | None = None,
    validate: bool | None = None,
  ) -> RadarStationFeature: ...
  async def get_station(
    self,
    *,
    station_id: str,
    reporting_host: str | None = None,
    host: str | None = None,
    validate: bool | None = None,
  ) -> RadarStationFeature:
    """One radar: where it is, its data latency, the status of the radar itself, and its latest performance and calibration reports.

    Args:
      station_id: Station identifier, such as `KATX`. `radar.list_stations` returns it as `properties.id`.
      reporting_host: Monitoring host to report status and latency from. `rdss` is the only one the service knew on 2026-10-01.
      host: LDM host to measure `latency` at, such as `ldm1`. Without it, `ldm4` on 2026-10-01; a host the service does not know answers a `latency` of nulls.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/radar_station)
    """
    request: Request = Request(station_id=station_id)
    if reporting_host is not None:
      request['reportingHost'] = reporting_host
    if host is not None:
      request['host'] = host
    return await self.request(
      request,
      method='GET',
      path='/radar/stations/{station_id}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=RadarStationFeature,
    )
