# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint


RadarQueueProductKeywords = TypedDict(
  'RadarQueueProductKeywords', {'@type': Literal['wx:RadarQueue']}
)
"""
- `@type`: Always `wx:RadarQueue`.
"""


class RadarQueueProduct(RadarQueueProductKeywords):
  """One Level II product in the queue."""

  host: Literal['rds', 'tds']
  """The distribution host."""
  arrivalTime: TimestampIso
  """When the product arrived at the host."""
  creationTime: TimestampIso
  """When the radar created it."""
  stationId: str
  """The radar, such as `KATX`."""
  type: str
  """Part of the Level II volume this is: `start`, `intermediate`, `end` or `model` on 2026-10-01. Undocumented, so not enumerated."""
  feed: str
  """Feed it came on, such as `NEXRAD2`."""
  resolutionVersion: int
  """Resolution version, such as `6`."""
  sequenceNumber: str
  """Volume and chunk sequence, such as `490-050`."""
  size: int
  """Size of the product, in bytes."""


class Request(TypedDict):
  """Which host, and which products. Every filter is optional."""

  host: Literal['rds', 'tds']
  """Distribution host: `rds` or `tds`."""
  limit: NotRequired[int]
  """Most products to return, 1 to 50,000. Without it, 500."""
  arrived: NotRequired[str]
  """Only products that arrived in this ISO 8601 interval: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT10M`. The answer starts at the interval's start, so a `limit` keeps the oldest. Without it, about the last two minutes. The service keeps about a week."""
  created: NotRequired[str]
  """Only products the radar created in this ISO 8601 interval, in the same forms as `arrived`. Every request with it answered 503 on 2026-10-01 (`An upstream data source is temporarily unavailable`)."""
  published: NotRequired[str]
  """Only products published in this ISO 8601 interval, in the same forms as `arrived`."""
  station: NotRequired[str]
  """Only this radar's products, such as `KATX`. An unknown one answers an empty `@graph`."""
  type: NotRequired[str]
  """Only this kind of product. Undocumented; `start`, `intermediate`, `end` and `model` on 2026-10-01, which are the parts of a Level II volume."""
  feed: NotRequired[str]
  """Only products from this feed, such as `NEXRAD2`."""
  resolution: NotRequired[int]
  """Only products of this resolution version, such as `6` or `8`."""


RadarQueueKeywords = TypedDict(
  'RadarQueueKeywords', {'@id': NotRequired[str], '@graph': list[RadarQueueProduct]}
)
"""
  - `@id`: URL of this queue.
  - `@graph`: The products, by arrival.
"""


class RadarQueue(RadarQueueKeywords):
  """The products, as a JSON-LD graph."""


class GetQueue(Endpoint):
  """The Level II products that passed through one distribution host's LDM queue, oldest first from the start of the interval. JSON-LD: the products come as a `@graph`."""

  @overload
  async def get_queue(
    self,
    host: Literal['rds', 'tds'],
    *,
    limit: int | None = None,
    arrived: str | None = None,
    created: str | None = None,
    published: str | None = None,
    station: str | None = None,
    type: str | None = None,
    feed: str | None = None,
    resolution: int | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_queue(
    self,
    host: Literal['rds', 'tds'],
    *,
    limit: int | None = None,
    arrived: str | None = None,
    created: str | None = None,
    published: str | None = None,
    station: str | None = None,
    type: str | None = None,
    feed: str | None = None,
    resolution: int | None = None,
    validate: bool | None = None,
  ) -> RadarQueue: ...
  async def get_queue(
    self,
    host: Literal['rds', 'tds'],
    *,
    limit: int | None = None,
    arrived: str | None = None,
    created: str | None = None,
    published: str | None = None,
    station: str | None = None,
    type: str | None = None,
    feed: str | None = None,
    resolution: int | None = None,
    validate: bool | None = None,
  ) -> RadarQueue:
    """The Level II products that passed through one distribution host's LDM queue, oldest first from the start of the interval. JSON-LD: the products come as a `@graph`.

    Args:
      host: Distribution host: `rds` or `tds`.
      limit: Most products to return, 1 to 50,000. Without it, 500.
      arrived: Only products that arrived in this ISO 8601 interval: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT10M`. The answer starts at the interval's start, so a `limit` keeps the oldest. Without it, about the last two minutes. The service keeps about a week.
      created: Only products the radar created in this ISO 8601 interval, in the same forms as `arrived`. Every request with it answered 503 on 2026-10-01 (`An upstream data source is temporarily unavailable`).
      published: Only products published in this ISO 8601 interval, in the same forms as `arrived`.
      station: Only this radar's products, such as `KATX`. An unknown one answers an empty `@graph`.
      type: Only this kind of product. Undocumented; `start`, `intermediate`, `end` and `model` on 2026-10-01, which are the parts of a Level II volume.
      feed: Only products from this feed, such as `NEXRAD2`.
      resolution: Only products of this resolution version, such as `6` or `8`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/radar_queue)
    """
    request: Request = Request(host=host)
    if limit is not None:
      request['limit'] = limit
    if arrived is not None:
      request['arrived'] = arrived
    if created is not None:
      request['created'] = created
    if published is not None:
      request['published'] = published
    if station is not None:
      request['station'] = station
    if type is not None:
      request['type'] = type
    if feed is not None:
      request['feed'] = feed
    if resolution is not None:
      request['resolution'] = resolution
    return await self.request(
      request,
      method='GET',
      path='/radar/queues/{host}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=RadarQueue,
    )
