# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, cast, overload
from weather_gov.core import Endpoint


RadarProfiler = Any


class Request(TypedDict):
  """Which profiler, and over what time."""

  station_id: str
  """Profiler station identifier, such as `TLKA2`. `radar.list_stations` with a `station_type` of `Profiler` lists them."""
  time: NotRequired[str]
  """Time interval, in ISO 8601: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT1H`."""
  interval: NotRequired[str]
  """Averaging interval, as an ISO 8601 duration such as `PT1H`."""


class GetProfiler(Endpoint):
  """Metadata about one radar wind profiler, as JSON-LD. Unverified: every profiler answered 404 on 2026-10-01, so the response is not described."""

  @overload
  async def get_profiler(
    self,
    *,
    station_id: str,
    time: str | None = None,
    interval: str | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_profiler(
    self,
    *,
    station_id: str,
    time: str | None = None,
    interval: str | None = None,
    validate: bool | None = None,
  ) -> RadarProfiler: ...
  async def get_profiler(
    self,
    *,
    station_id: str,
    time: str | None = None,
    interval: str | None = None,
    validate: bool | None = None,
  ) -> RadarProfiler:
    """Metadata about one radar wind profiler, as JSON-LD. Unverified: every profiler answered 404 on 2026-10-01, so the response is not described.

    Args:
      station_id: Profiler station identifier, such as `TLKA2`. `radar.list_stations` with a `station_type` of `Profiler` lists them.
      time: Time interval, in ISO 8601: `start/end`, `start/duration` or `duration/end`, either end may be `NOW`, such as `2026-09-30T23:00:00Z/PT1H`.
      interval: Averaging interval, as an ISO 8601 duration such as `PT1H`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/radar_profiler)
    """
    request: Request = Request(station_id=station_id)
    if time is not None:
      request['time'] = time
    if interval is not None:
      request['interval'] = interval
    return await self.request(
      request,
      method='GET',
      path='/radar/profilers/{station_id}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=cast(type, RadarProfiler),
    )
