//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, DateIso, HttpCall, HttpEndpoint, Result,
};

use crate::meta::DefaultMeta;
use crate::types::{CenterWeatherAdvisoryFeature, CwsuId};

/// Which advisory: its unit, its issue date and its sequence number, as they end its URL.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// The unit, such as `ZSE` for Seattle Center.
    pub cwsu_id: CwsuId,
    /// UTC date the advisory was issued.
    pub date: DateIso,
    /// Sequence number, from 101 up: `properties.sequence` of the advisory.
    pub sequence: i64,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One Center Weather Advisory, with its area. A unit occasionally gives two advisories one sequence number on one day (measured 2026-09-30, `ZAB` issued two `206`s), and the service then answers one of them; `aviation.list_cwas` holds both.
#[derive(Clone)]
pub struct GetCwa {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetCwa {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One Center Weather Advisory, with its area. A unit occasionally gives two advisories one sequence number on one day (measured 2026-09-30, `ZAB` issued two `206`s), and the service then answers one of them; `aviation.list_cwas` holds both.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/cwa>.
    pub async fn get_cwa(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<CenterWeatherAdvisoryFeature> {
        let raw = self.get_cwa_raw(request, options).await?;
        decode(raw)
    }

    /// `get_cwa` without validation: the wire body as it came.
    pub async fn get_cwa_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/aviation/cwsus/{cwsu_id}/cwas/{date}/{sequence}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
