//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::CwsuId;

/// Where the unit is.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct CenterWeatherServiceUnitAddress {
    /// Street address.
    #[serde(
        rename = "streetAddress",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub street_address: Option<String>,
    /// City.
    #[serde(
        rename = "addressLocality",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub address_locality: Option<String>,
    /// Two-letter state code.
    #[serde(
        rename = "addressRegion",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub address_region: Option<String>,
    /// ZIP code.
    #[serde(
        rename = "postalCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub postal_code: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The unit. A schema.org `GovernmentOrganization`, like `offices.get_office`, but without the zones and stations an office is responsible for.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CenterWeatherServiceUnit {
    /// The unit's code.
    pub id: CwsuId,
    /// The center it serves, such as `Seattle, WA`.
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub address: Option<CenterWeatherServiceUnitAddress>,
    /// Public telephone number; often empty.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub telephone: Option<String>,
    /// Fax number; often empty.
    #[serde(rename = "faxNumber", default, skip_serializing_if = "Option::is_none")]
    pub fax_number: Option<String>,
    /// Contact address.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The unit's own website.
    #[serde(rename = "sameAs", default, skip_serializing_if = "Option::is_none")]
    pub same_as: Option<String>,
    /// NWS region the unit belongs to, such as `wr` for Western.
    #[serde(rename = "nwsRegion", default, skip_serializing_if = "Option::is_none")]
    pub nws_region: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Which unit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// The unit, such as `ZSE` for Seattle Center.
    pub cwsu_id: CwsuId,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One Center Weather Service Unit: where it is and how to reach it.
#[derive(Clone)]
pub struct GetCwsu {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetCwsu {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One Center Weather Service Unit: where it is and how to reach it.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/cwsu>.
    pub async fn get_cwsu(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<CenterWeatherServiceUnit> {
        let raw = self.get_cwsu_raw(request, options).await?;
        decode(raw)
    }

    /// `get_cwsu` without validation: the wire body as it came.
    pub async fn get_cwsu_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/aviation/cwsus/{cwsu_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
