//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::{CenterWeatherAdvisoryCollection, CwsuId};

/// Which unit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// The unit, such as `ZSE` for Seattle Center.
    pub cwsu_id: CwsuId,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The Center Weather Advisories one unit has issued in about the last week, newest first.
#[derive(Clone)]
pub struct ListCwas {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListCwas {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The Center Weather Advisories one unit has issued in about the last week, newest first.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/cwas>.
    pub async fn list_cwas(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<CenterWeatherAdvisoryCollection> {
        let raw = self.list_cwas_raw(request, options).await?;
        decode(raw)
    }

    /// `list_cwas` without validation: the wire body as it came.
    pub async fn list_cwas_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/aviation/cwsus/{cwsu_id}/cwas",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
