//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, DateIso, HttpCall, HttpEndpoint, Result,
};

use crate::meta::DefaultMeta;
use crate::types::SigmetCollection;

/// Which unit, and which day.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// Air traffic services unit, such as `KKCI` (the Aviation Weather Center, which issues the SIGMETs for the contiguous US) or `ANC` (Anchorage). Three or four capital letters.
    pub atsu: String,
    /// UTC date the messages were issued. The service keeps about a week; an older date answers an empty collection.
    pub date: DateIso,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The SIGMETs and AIRMETs one unit issued on one UTC date, newest first.
#[derive(Clone)]
pub struct ListSigmetsForAtsuOnDate {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListSigmetsForAtsuOnDate {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The SIGMETs and AIRMETs one unit issued on one UTC date, newest first.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/sigmetsByATSUByDate>.
    pub async fn list_sigmets_for_atsu_on_date(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<SigmetCollection> {
        let raw = self
            .list_sigmets_for_atsu_on_date_raw(request, options)
            .await?;
        decode(raw)
    }

    /// `list_sigmets_for_atsu_on_date` without validation: the wire body as it came.
    pub async fn list_sigmets_for_atsu_on_date_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/aviation/sigmets/{atsu}/{date}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
