# Generated by truewire — do not edit by hand.
from .list_terms import ListTerms


class Glossary(ListTerms):
  """The service's glossary of weather terms and abbreviations.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/glossary)
  """
