// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import * as listTerms from './list_terms.js'

/**
 * The service's glossary of weather terms and abbreviations.
 *
 * @see https://www.weather.gov/documentation/services-web-api#/default/glossary
 */
export class Glossary {
  private readonly listTerms_: listTerms.ListTerms

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.listTerms_ = new listTerms.ListTerms(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTerms(request: listTerms.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The whole weather glossary: several thousand terms, each with its definition. One response, about 900 KB; the service offers no filter or paging.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/glossary
   */
  listTerms(request?: listTerms.Request, options?: CallOptions): Promise<listTerms.Glossary>
  listTerms(request?: listTerms.Request, options?: CallOptions): Promise<listTerms.Glossary> {
    return this.listTerms_.listTerms(request, options)
  }
}
