// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** One term. */
export interface GlossaryTerm {
  /** The term, such as `1-2-3 Rule`. */
  term: string
  /** Its definition. Some contain HTML markup, such as links and line breaks. */
  definition: string
}

export const GlossaryTerm: Codec<GlossaryTerm> = t.object({
  term: t.string,
  definition: t.string,
})

/** Takes nothing. */
export interface Request {}

export const Request: Codec<Request> = t.object({})

/** The glossary. */
export interface GlossaryResponse {
  /** Terms, roughly alphabetical. */
  glossary: GlossaryTerm[]
}

export const GlossaryResponse: Codec<GlossaryResponse> = t.object({
  glossary: t.array(GlossaryTerm),
})

/** The whole weather glossary: several thousand terms, each with its definition. One response, about 900 KB; the service offers no filter or paging. */
export class ListTerms {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTerms(request: Request | undefined, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The whole weather glossary: several thousand terms, each with its definition. One response, about 900 KB; the service offers no filter or paging.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/glossary
   */
  listTerms(request?: Request, options?: CallOptions): Promise<GlossaryResponse>
  async listTerms(request?: Request, options?: CallOptions): Promise<GlossaryResponse> {
    return this.core.request({
      method: 'GET',
      path: '/glossary',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: GlossaryResponse,
      meta: {},
      ...options,
    })
  }
}
