# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import GridpointForecast


class Request(TypedDict):
  """Which grid cell, and in which units."""

  office: str
  """Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`."""
  grid_x: int
  """Grid column, from `points.get_point`."""
  grid_y: int
  """Grid row, from `points.get_point`."""
  units: NotRequired[Literal['us', 'si']]
  """Unit system for the rendered temperatures: `us` for Fahrenheit and miles per hour, `si` for Celsius and kilometres per hour. Defaults to `us`."""


class GetHourlyForecast(Endpoint):
  """The hourly forecast for one grid cell: one period per hour for about the next week, carrying dew point and relative humidity the twice-daily forecast leaves out, and no prose."""

  @overload
  async def get_hourly_forecast(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    units: Literal['us', 'si'] | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_hourly_forecast(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    units: Literal['us', 'si'] | None = None,
    validate: bool | None = None,
  ) -> GridpointForecast: ...
  async def get_hourly_forecast(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    units: Literal['us', 'si'] | None = None,
    validate: bool | None = None,
  ) -> GridpointForecast:
    """The hourly forecast for one grid cell: one period per hour for about the next week, carrying dew point and relative humidity the twice-daily forecast leaves out, and no prose.

    Args:
      office: Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`.
      grid_x: Grid column, from `points.get_point`.
      grid_y: Grid row, from `points.get_point`.
      units: Unit system for the rendered temperatures: `us` for Fahrenheit and miles per hour, `si` for Celsius and kilometres per hour. Defaults to `us`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast_hourly)
    """
    request: Request = Request(office=office, grid_x=grid_x, grid_y=grid_y)
    if units is not None:
      request['units'] = units
    return await self.request(
      request,
      method='GET',
      path='/gridpoints/{office}/{grid_x},{grid_y}/forecast/hourly',
      meta={'payload': 'properties'},
      validate=validate,
      request_type=Request,
      response_type=GridpointForecast,
    )
