# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import GridSeries, QuantitativeValue


class Request(TypedDict):
  """Which grid cell."""

  office: str
  """Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`."""
  grid_x: int
  """Grid column, from `points.get_point`."""
  grid_y: int
  """Grid row, from `points.get_point`."""


class WeatherPhenomenon(TypedDict):
  """One forecast phenomenon."""

  coverage: str | None
  """How widespread it is: `patchy`, `scattered`, `likely`, `definite`."""
  weather: str | None
  """The phenomenon: `rain`, `snow`, `fog`, `thunderstorms`."""
  intensity: str | None
  """`very_light`, `light`, `moderate` or `heavy`."""
  visibility: NotRequired[QuantitativeValue]
  attributes: NotRequired[list[str]]
  """Extra qualifiers, such as `damaging_wind` or `small_hail`."""


class WeatherInterval(TypedDict):
  """The phenomena forecast over one interval."""

  validTime: str
  """ISO 8601 interval, as `<start>/<duration>`."""
  value: list[WeatherPhenomenon]
  """Phenomena forecast simultaneously over the interval. A single entry with every field null means no weather."""


class WeatherSeries(TypedDict):
  """Forecast weather phenomena over time. Unlike the numeric series it carries no `uom`, and each value is a list of simultaneous phenomena rather than a number."""

  values: list[WeatherInterval]
  """The values, in time order."""


class GridData(TypedDict):
  """The series themselves. Every one is optional: which series a cell carries depends on where it is -- a coastal cell has wave heights, an inland one does not."""

  updateTime: TimestampIso
  """When this grid was last updated."""
  validTimes: str
  """ISO 8601 interval the grid covers, as `<start>/<duration>`."""
  elevation: NotRequired[QuantitativeValue]
  forecastOffice: NotRequired[str]
  """URL of the office that produced it."""
  gridId: str
  """Office code addressing the grid."""
  gridX: int
  """Grid column."""
  gridY: int
  """Grid row."""
  temperature: NotRequired[GridSeries]
  dewpoint: NotRequired[GridSeries]
  maxTemperature: NotRequired[GridSeries]
  minTemperature: NotRequired[GridSeries]
  relativeHumidity: NotRequired[GridSeries]
  apparentTemperature: NotRequired[GridSeries]
  heatIndex: NotRequired[GridSeries]
  windChill: NotRequired[GridSeries]
  skyCover: NotRequired[GridSeries]
  windDirection: NotRequired[GridSeries]
  windSpeed: NotRequired[GridSeries]
  windGust: NotRequired[GridSeries]
  probabilityOfPrecipitation: NotRequired[GridSeries]
  quantitativePrecipitation: NotRequired[GridSeries]
  iceAccumulation: NotRequired[GridSeries]
  snowfallAmount: NotRequired[GridSeries]
  ceilingHeight: NotRequired[GridSeries]
  visibility: NotRequired[GridSeries]
  probabilityOfThunder: NotRequired[GridSeries]
  weather: NotRequired[WeatherSeries]


class GetGridData(Endpoint):
  """The raw gridded forecast for one cell: the seventy-odd series the narrative forecasts are rendered from, each a run of intervals with its own unit. This is the endpoint to reach for when the prose is not enough -- a snow-load calculation wants `snowfallAmount`, not `Snow likely, with 2 to 4 inches possible`."""

  @overload
  async def get_grid_data(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_grid_data(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    validate: bool | None = None,
  ) -> GridData: ...
  async def get_grid_data(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    validate: bool | None = None,
  ) -> GridData:
    """The raw gridded forecast for one cell: the seventy-odd series the narrative forecasts are rendered from, each a run of intervals with its own unit. This is the endpoint to reach for when the prose is not enough -- a snow-load calculation wants `snowfallAmount`, not `Snow likely, with 2 to 4 inches possible`.

    Args:
      office: Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`.
      grid_x: Grid column, from `points.get_point`.
      grid_y: Grid row, from `points.get_point`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/gridpoint)
    """
    return await self.request(
      Request(office=office, grid_x=grid_x, grid_y=grid_y),
      method='GET',
      path='/gridpoints/{office}/{grid_x},{grid_y}',
      meta={'payload': 'properties'},
      validate=validate,
      request_type=Request,
      response_type=GridData,
    )
