# Generated by truewire — do not edit by hand.
from .get_latest_product import GetLatestProduct
from .get_product import GetProduct
from .list_locations import ListLocations
from .list_locations_for_type import ListLocationsForType
from .list_product_types import ListProductTypes
from .list_products import ListProducts
from .list_products_by_type import ListProductsByType
from .list_products_by_type_and_location import ListProductsByTypeAndLocation
from .list_types_for_location import ListTypesForLocation


class Products(
  GetLatestProduct,
  GetProduct,
  ListLocations,
  ListLocationsForType,
  ListProductTypes,
  ListProducts,
  ListProductsByType,
  ListProductsByTypeAndLocation,
  ListTypesForLocation,
):
  """The text products the service publishes, by type.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/product_types)
  """
