# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import ProductLocationCollection


class Request(TypedDict):
  """Takes nothing."""


class ListLocations(Endpoint):
  """Every location text products are issued for, by id, with a name where the service has one."""

  @overload
  async def list_locations(self, *, validate: Literal[False]) -> Any: ...
  @overload
  async def list_locations(
    self,
    *,
    validate: bool | None = None,
  ) -> ProductLocationCollection: ...
  async def list_locations(
    self,
    *,
    validate: bool | None = None,
  ) -> ProductLocationCollection:
    """Every location text products are issued for, by id, with a name where the service has one.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/product_locations)
    """
    return await self.request(
      Request(),
      method='GET',
      path='/products/locations',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ProductLocationCollection,
    )
