# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import ProductCollection


class Request(TypedDict):
  """Which type, from where."""

  type_id: str
  """Three-letter product type, such as `AFD`. `products.list_product_types` names every code."""
  location_id: str
  """Issuance location, such as `SEW` for Seattle. `products.list_locations` names every id; `products.list_locations_for_type` narrows them to one type."""


class ListProductsByTypeAndLocation(Endpoint):
  """Every product of one type from one location the service still holds, newest first. Header fields only."""

  @overload
  async def list_products_by_type_and_location(
    self,
    *,
    type_id: str,
    location_id: str,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_products_by_type_and_location(
    self,
    *,
    type_id: str,
    location_id: str,
    validate: bool | None = None,
  ) -> ProductCollection: ...
  async def list_products_by_type_and_location(
    self,
    *,
    type_id: str,
    location_id: str,
    validate: bool | None = None,
  ) -> ProductCollection:
    """Every product of one type from one location the service still holds, newest first. Header fields only.

    Args:
      type_id: Three-letter product type, such as `AFD`. `products.list_product_types` names every code.
      location_id: Issuance location, such as `SEW` for Seattle. `products.list_locations` names every id; `products.list_locations_for_type` narrows them to one type.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/products_type_location)
    """
    return await self.request(
      Request(type_id=type_id, location_id=location_id),
      method='GET',
      path='/products/types/{type_id}/locations/{location_id}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ProductCollection,
    )
