# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import ProductLocationCollection


class Request(TypedDict):
  """Which type."""

  type_id: str
  """Three-letter product type, such as `AFD`. `products.list_product_types` names every code."""


class ListLocationsForType(Endpoint):
  """The locations that issue one product type, by id, with their names."""

  @overload
  async def list_locations_for_type(
    self,
    type_id: str,
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_locations_for_type(
    self,
    type_id: str,
    *,
    validate: bool | None = None,
  ) -> ProductLocationCollection: ...
  async def list_locations_for_type(
    self,
    type_id: str,
    *,
    validate: bool | None = None,
  ) -> ProductLocationCollection:
    """The locations that issue one product type, by id, with their names.

    Args:
      type_id: Three-letter product type, such as `AFD`. `products.list_product_types` names every code.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/products_type_locations)
    """
    return await self.request(
      Request(type_id=type_id),
      method='GET',
      path='/products/types/{type_id}/locations',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ProductLocationCollection,
    )
