# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import ProductTypeCollection


class Request(TypedDict):
  """Takes nothing."""


class ListProductTypes(Endpoint):
  """Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for."""

  @overload
  async def list_product_types(self, *, validate: Literal[False]) -> Any: ...
  @overload
  async def list_product_types(
    self,
    *,
    validate: bool | None = None,
  ) -> ProductTypeCollection: ...
  async def list_product_types(
    self,
    *,
    validate: bool | None = None,
  ) -> ProductTypeCollection:
    """Every kind of text product the service issues, by code. Three-letter codes such as `AFD` (area forecast discussion) or `TOR` (tornado warning), each with the name it stands for.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/product_types)
    """
    return await self.request(
      Request(),
      method='GET',
      path='/products/types',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ProductTypeCollection,
    )
