# Generated by truewire — do not edit by hand.
from .get_office import GetOffice


class Offices(GetOffice):
  """The weather forecast offices that issue everything else here.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/office)
  """
