# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import OfficeHeadline


class Request(TypedDict):
  """Which office, and which headline."""

  office_id: str
  """Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`."""
  headline_id: str
  """Headline id, such as `058e41fd34b935b395e9aaf0fe175dc9`. `offices.list_headlines` returns it as `id`."""


class GetHeadline(Endpoint):
  """One news headline an office has posted."""

  @overload
  async def get_headline(
    self,
    *,
    office_id: str,
    headline_id: str,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_headline(
    self,
    *,
    office_id: str,
    headline_id: str,
    validate: bool | None = None,
  ) -> OfficeHeadline: ...
  async def get_headline(
    self,
    *,
    office_id: str,
    headline_id: str,
    validate: bool | None = None,
  ) -> OfficeHeadline:
    """One news headline an office has posted.

    Args:
      office_id: Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`.
      headline_id: Headline id, such as `058e41fd34b935b395e9aaf0fe175dc9`. `offices.list_headlines` returns it as `id`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/office_headline)
    """
    return await self.request(
      Request(office_id=office_id, headline_id=headline_id),
      method='GET',
      path='/offices/{office_id}/headlines/{headline_id}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=OfficeHeadline,
    )
