# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint


class OfficeBriefing(TypedDict):
  """One briefing."""

  id: str
  """Briefing id, a UUID."""
  officeId: str
  """Code of the office that issued it, such as `AKQ`."""
  startTime: TimestampIso
  """When the briefing took effect."""
  endTime: TimestampIso
  """When it stops being current."""
  updateTime: TimestampIso
  """When it was last updated."""
  title: str
  """Title, often only a prompt such as `Click to view briefing`."""
  description: str
  """What the briefing covers, as plain text."""
  priority: bool
  """Whether the office flagged it as a priority."""
  download: str
  """URL of the briefing as a PDF. The service answers only `application/pdf` there, so no endpoint here fetches it."""


class Request(TypedDict):
  """Which office."""

  office_id: str
  """Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`."""


class ActiveBriefing(TypedDict):
  """The office's active briefing, or null."""

  briefing: OfficeBriefing | None
  """The briefing. Null when the office has none active, which is most of them."""


class GetBriefing(Endpoint):
  """The decision-support briefing an office has active, if any: a slide deck for emergency managers, downloadable as a PDF."""

  @overload
  async def get_briefing(self, office_id: str, *, validate: Literal[False]) -> Any: ...
  @overload
  async def get_briefing(
    self,
    office_id: str,
    *,
    validate: bool | None = None,
  ) -> ActiveBriefing: ...
  async def get_briefing(
    self,
    office_id: str,
    *,
    validate: bool | None = None,
  ) -> ActiveBriefing:
    """The decision-support briefing an office has active, if any: a slide deck for emergency managers, downloadable as a PDF.

    Args:
      office_id: Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/office_briefing)
    """
    return await self.request(
      Request(office_id=office_id),
      method='GET',
      path='/offices/{office_id}/briefing',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ActiveBriefing,
    )
