# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint


class Request(TypedDict):
  """Which office."""

  office_id: str
  """Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`."""


class WeatherStory(TypedDict):
  """One weather story: a graphic, and the text that goes with it."""

  officeId: str
  """Code of the office that issued it, such as `AKQ`."""
  startTime: TimestampIso
  """When the story took effect."""
  endTime: TimestampIso
  """When it stops being current."""
  updateTime: TimestampIso
  """When it was last updated."""
  title: str
  """Title, such as `Today's Forecast`."""
  description: str
  """The story as plain text."""
  altText: str
  """Alternative text for the graphic."""
  priority: bool
  """Whether the office flagged it as a priority."""
  order: int
  """Where the office places it among its stories, lowest first."""
  download: str | None
  """URL of the graphic. The service answers only an image there, so no endpoint here fetches it. Null on a few stories: 3 of 252 across every office on 2026-09-30."""


class WeatherStoryCollection(TypedDict):
  """The office's active weather stories."""

  stories: list[WeatherStory]
  """The stories. Empty for an office that has none active."""


class ListWeatherStories(Endpoint):
  """The weather stories an office has active: the forecast graphics on the front of its website, each with its text."""

  @overload
  async def list_weather_stories(
    self,
    office_id: str,
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_weather_stories(
    self,
    office_id: str,
    *,
    validate: bool | None = None,
  ) -> WeatherStoryCollection: ...
  async def list_weather_stories(
    self,
    office_id: str,
    *,
    validate: bool | None = None,
  ) -> WeatherStoryCollection:
    """The weather stories an office has active: the forecast graphics on the front of its website, each with its text.

    Args:
      office_id: Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/office_weatherstory)
    """
    return await self.request(
      Request(office_id=office_id),
      method='GET',
      path='/offices/{office_id}/weatherstories',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=WeatherStoryCollection,
    )
