# Generated by truewire — do not edit by hand.
from .get_transmitter import GetTransmitter
from .list_transmitters import ListTransmitters


class Radio(GetTransmitter, ListTransmitters):
  """NOAA Weather Radio: the transmitters that broadcast forecasts and warnings, and the counties each one serves.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/transmitters)
  """
