# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import TransmitterCollection


class Request(TypedDict):
  """Which page."""

  cursor: NotRequired[str]
  """Page cursor, from the `cursor` query parameter of the previous page's `pagination.next`. Leave it out for the first page. The service does not hand it back on its own -- see the notes -- so it is here for a caller who has one, not for a walk the client drives."""


class ListTransmitters(Endpoint):
  """Every NOAA Weather Radio transmitter, a page at a time. JSON-LD, not GeoJSON: the transmitters come as a `@graph`."""

  @overload
  async def list_transmitters(
    self,
    cursor: str | None = None,
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_transmitters(
    self,
    cursor: str | None = None,
    *,
    validate: bool | None = None,
  ) -> TransmitterCollection: ...
  async def list_transmitters(
    self,
    cursor: str | None = None,
    *,
    validate: bool | None = None,
  ) -> TransmitterCollection:
    """Every NOAA Weather Radio transmitter, a page at a time. JSON-LD, not GeoJSON: the transmitters come as a `@graph`.

    Args:
      cursor: Page cursor, from the `cursor` query parameter of the previous page's `pagination.next`. Leave it out for the first page. The service does not hand it back on its own -- see the notes -- so it is here for a caller who has one, not for a walk the client drives.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/transmitters)
    """
    request: Request = Request()
    if cursor is not None:
      request['cursor'] = cursor
    return await self.request(
      request,
      method='GET',
      path='/radio',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=TransmitterCollection,
    )
