# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint


class ActiveAlertCount(TypedDict):
  """Counts of the alerts in effect. Only keys with at least one alert appear in the three maps."""

  total: int
  """Alerts in effect."""
  land: int
  """Alerts affecting land zones."""
  marine: int
  """Alerts affecting marine zones."""
  regions: dict[str, int]
  """Alerts by marine region code, such as `GL`."""
  areas: dict[str, int]
  """Alerts by state, territory or marine-area code, such as `TX` or `PZ`."""
  zones: dict[str, int]
  """Alerts by zone or county code, such as `AZC009`."""


class Request(TypedDict):
  """Takes nothing."""


class CountActiveAlerts(Endpoint):
  """How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone."""

  @overload
  async def count_active_alerts(self, *, validate: Literal[False]) -> Any: ...
  @overload
  async def count_active_alerts(
    self,
    *,
    validate: bool | None = None,
  ) -> ActiveAlertCount: ...
  async def count_active_alerts(self, *, validate: bool | None = None) -> ActiveAlertCount:
    """How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone.

    Args:
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/alerts_active_count)
    """
    return await self.request(
      Request(),
      method='GET',
      path='/alerts/active/count',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ActiveAlertCount,
    )
