# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import AlertCollection


class Request(TypedDict):
  """Which marine region."""

  region: Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI']
  """Marine region: `AL` Alaska, `AT` Atlantic, `GL` Great Lakes, `GM` Gulf of Mexico, `PA` Pacific, `PI` Pacific Islands."""


class GetActiveAlertsForRegion(Endpoint):
  """The alerts in effect for one marine region. The same as `alerts.get_active_alerts` narrowed by `region`, with the region in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out."""

  @overload
  async def get_active_alerts_for_region(
    self,
    region: Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI'],
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_active_alerts_for_region(
    self,
    region: Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI'],
    *,
    validate: bool | None = None,
  ) -> AlertCollection: ...
  async def get_active_alerts_for_region(
    self,
    region: Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI'],
    *,
    validate: bool | None = None,
  ) -> AlertCollection:
    """The alerts in effect for one marine region. The same as `alerts.get_active_alerts` narrowed by `region`, with the region in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.

    Args:
      region: Marine region: `AL` Alaska, `AT` Atlantic, `GL` Great Lakes, `GM` Gulf of Mexico, `PA` Pacific, `PI` Pacific Islands.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/alerts_active_region)
    """
    return await self.request(
      Request(region=region),
      method='GET',
      path='/alerts/active/region/{region}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=AlertCollection,
    )
