# Generated by truewire — do not edit by hand.
from truewire_core.types import TimestampIso
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import AlertFeature


class Request(TypedDict):
  """How to narrow the alerts. Every filter is optional; the array-valued ones are sent as repeated query keys and mean "any of"."""

  area: NotRequired[list[str]]
  """Two-letter state, territory or marine-area codes to narrow to, such as `WA` or `PZ`. Sent as a repeated query key. Left un-enumerated deliberately: the service's own 400 lists only the marine half of what it accepts, and a guessed enum would reject the states."""
  region: NotRequired[list[Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI']]]
  """Marine regions to narrow to."""
  zone: NotRequired[list[str]]
  """Forecast zone codes, such as `WAZ315`."""
  point: NotRequired[str]
  """A `latitude,longitude` pair; returns the alerts covering that point."""
  status: NotRequired[list[Literal['actual', 'exercise', 'system', 'test', 'draft']]]
  """Alert statuses to include. Lower-case, unlike every other enumerated filter here. Pass `actual` to leave out drills and tests."""
  severity: NotRequired[list[Literal['Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown']]]
  """Severities to include. Capitalised, unlike `status`."""
  urgency: NotRequired[list[Literal['Immediate', 'Expected', 'Future', 'Past', 'Unknown']]]
  """Urgencies to include. Capitalised, unlike `status`."""
  certainty: NotRequired[list[Literal['Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown']]]
  """Certainties to include. Capitalised, unlike `status`."""
  event: NotRequired[list[str]]
  """Event names to include, such as `Red Flag Warning`."""


class AlertCollection(TypedDict):
  """The alerts in effect, as a GeoJSON feature collection."""

  type: Literal['FeatureCollection']
  """Always `FeatureCollection`."""
  features: list[AlertFeature]
  """The alerts."""
  title: NotRequired[str]
  """Human-readable title of the collection."""
  updated: NotRequired[TimestampIso]
  """When the collection was assembled."""


class GetActiveAlerts(Endpoint):
  """Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it."""

  @overload
  async def get_active_alerts(
    self,
    *,
    area: list[str] | None = None,
    region: list[Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI']] | None = None,
    zone: list[str] | None = None,
    point: str | None = None,
    status: list[Literal['actual', 'exercise', 'system', 'test', 'draft']] | None = None,
    severity: list[Literal['Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown']] | None = None,
    urgency: list[Literal['Immediate', 'Expected', 'Future', 'Past', 'Unknown']] | None = None,
    certainty: list[Literal['Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown']] | None = None,
    event: list[str] | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_active_alerts(
    self,
    *,
    area: list[str] | None = None,
    region: list[Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI']] | None = None,
    zone: list[str] | None = None,
    point: str | None = None,
    status: list[Literal['actual', 'exercise', 'system', 'test', 'draft']] | None = None,
    severity: list[Literal['Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown']] | None = None,
    urgency: list[Literal['Immediate', 'Expected', 'Future', 'Past', 'Unknown']] | None = None,
    certainty: list[Literal['Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown']] | None = None,
    event: list[str] | None = None,
    validate: bool | None = None,
  ) -> AlertCollection: ...
  async def get_active_alerts(
    self,
    *,
    area: list[str] | None = None,
    region: list[Literal['AL', 'AT', 'GL', 'GM', 'PA', 'PI']] | None = None,
    zone: list[str] | None = None,
    point: str | None = None,
    status: list[Literal['actual', 'exercise', 'system', 'test', 'draft']] | None = None,
    severity: list[Literal['Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown']] | None = None,
    urgency: list[Literal['Immediate', 'Expected', 'Future', 'Past', 'Unknown']] | None = None,
    certainty: list[Literal['Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown']] | None = None,
    event: list[str] | None = None,
    validate: bool | None = None,
  ) -> AlertCollection:
    """Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it.

    Args:
      area: Two-letter state, territory or marine-area codes to narrow to, such as `WA` or `PZ`. Sent as a repeated query key. Left un-enumerated deliberately: the service's own 400 lists only the marine half of what it accepts, and a guessed enum would reject the states.
      region: Marine regions to narrow to.
      zone: Forecast zone codes, such as `WAZ315`.
      point: A `latitude,longitude` pair; returns the alerts covering that point.
      status: Alert statuses to include. Lower-case, unlike every other enumerated filter here. Pass `actual` to leave out drills and tests.
      severity: Severities to include. Capitalised, unlike `status`.
      urgency: Urgencies to include. Capitalised, unlike `status`.
      certainty: Certainties to include. Capitalised, unlike `status`.
      event: Event names to include, such as `Red Flag Warning`.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/alerts_active)
    """
    request: Request = Request()
    if area is not None:
      request['area'] = area
    if region is not None:
      request['region'] = region
    if zone is not None:
      request['zone'] = zone
    if point is not None:
      request['point'] = point
    if status is not None:
      request['status'] = status
    if severity is not None:
      request['severity'] = severity
    if urgency is not None:
      request['urgency'] = urgency
    if certainty is not None:
      request['certainty'] = certainty
    if event is not None:
      request['event'] = event
    return await self.request(
      request,
      method='GET',
      path='/alerts/active',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=AlertCollection,
    )
