# Generated by truewire — do not edit by hand.
from .get_latest_observation import GetLatestObservation
from .get_observations import GetObservations
from .list_stations import ListStations


class Stations(GetLatestObservation, GetObservations, ListStations):
  """Observation stations and what they have reported.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/obs_stations)
  """
