# Generated by truewire — do not edit by hand.
from datetime import datetime
from truewire_core import PaginatedResponse
from truewire_core.exceptions import LogicError
from truewire_core.types import TimestampIso, timestamp_iso
from typing_extensions import Any, Literal, NotRequired, Sequence, TypedDict, cast, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import ObservationFeature


class ObservationPagination(TypedDict):
  """Where the next page is, as a whole URL. The declared walk moves the time window instead and never reads this."""

  next: NotRequired[str]
  """URL of the next page. Absent on the last one."""


class Request(TypedDict):
  """Which station, over which span."""

  station_id: str
  """Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`."""
  start: NotRequired[TimestampIso]
  """Start of the span, inclusive. The service keeps about a week of observations; a start older than that returns nothing rather than failing."""
  end: NotRequired[TimestampIso]
  """End of the span, exclusive: an observation at exactly `end` is not returned."""
  limit: NotRequired[int]
  """Observations per response. Range [1, 500]; the service caps a response at 500 whether or not this is sent, so 500 is also the default."""


class ObservationCollection(TypedDict):
  """The observations in the span, as a GeoJSON feature collection, newest first."""

  type: Literal['FeatureCollection']
  """Always `FeatureCollection`."""
  features: list[ObservationFeature]
  """The observations, newest first."""
  pagination: NotRequired[ObservationPagination]


class GetObservations(Endpoint):
  """What one station reported over a span of time, newest first. A busy airport station such as `KSEA` reports every five minutes, plus an hourly report at 53 minutes past, so a day there is about 300 observations."""

  @overload
  def get_observations_paged(
    self,
    station_id: str,
    *,
    start: TimestampIso | None = None,
    end: TimestampIso | None = None,
    limit: int | None = None,
    validate: Literal[False],
  ) -> PaginatedResponse[Any, tuple[TimestampIso | None, list[ObservationFeature]]]: ...
  @overload
  def get_observations_paged(
    self,
    station_id: str,
    *,
    start: TimestampIso | None = None,
    end: TimestampIso | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[
    ObservationFeature, tuple[TimestampIso | None, list[ObservationFeature]]
  ]: ...
  def get_observations_paged(
    self,
    station_id: str,
    *,
    start: TimestampIso | None = None,
    end: TimestampIso | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> PaginatedResponse[ObservationFeature, tuple[TimestampIso | None, list[ObservationFeature]]]:
    """What one station reported over a span of time, newest first. A busy airport station such as `KSEA` reports every five minutes, plus an hourly report at 53 minutes past, so a day there is about 300 observations.

    Paged variant of `get_observations`: Walks backwards by moving `end` to the earliest `properties.timestamp` of each page that came back full, never past the caller's own `start` and stops on the first page shorter than the venue's row cap. Awaitable (flattens every page) or async-iterable (one page at a time).

    The boundary row a venue re-serves is dropped by its `properties.timestamp` value, so no row is duplicated or skipped whichever way the venue bounds its ranges. The walk requests pages of at least 2 rows and at most 500: a page must hold one new row beside the one it re-reads.

    Args:
      station_id: Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`.
      start: Start of the span, inclusive. The service keeps about a week of observations; a start older than that returns nothing rather than failing.
      end: End of the span, exclusive: an observation at exactly `end` is not returned.
      limit: Observations per response. Range [1, 500]; the service caps a response at 500 whether or not this is sent, so 500 is also the default.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/station_observation_list)
    """
    limit = min(max(limit, 2), 500) if limit is not None else None
    cap: int | None = limit if limit is not None else 500

    async def next(
      state: tuple[TimestampIso | None, list[ObservationFeature]],
    ) -> tuple[
      Sequence[ObservationFeature], tuple[TimestampIso | None, list[ObservationFeature]] | None
    ]:
      def key_of(item: ObservationFeature):
        """One row's `properties.timestamp`, normalized to compare against the moving bound."""
        raw_0 = item.get('properties') if item is not None else None
        raw = raw_0.get('timestamp') if raw_0 is not None else None
        return (
          None
          if raw is None
          else timestamp_iso.parse(cast(str, raw))
          if not isinstance(raw, datetime)
          else raw
        )

      pos, carried = state
      response = await self.get_observations(
        station_id, start=start, end=pos, limit=limit, validate=validate
      )
      rows = response.get('features')
      rows = rows if rows is not None else []
      keys = [key_of(item) for item in rows]
      carried_keys = [key_of(item) for item in carried]
      fresh = [item for item, key in zip(rows, keys) if key not in carried_keys]
      values = [key for key in keys if key is not None]
      extreme = min(values) if values else None
      if cap is not None and len(rows) >= cap:
        if extreme is None or extreme == pos:
          raise LogicError(
            f'`get_observations_paged` requested from {pos} and the venue returned a full page of {len(rows)} rows all sharing one `properties.timestamp` value; the rest of that value is unreachable and advancing would drop it.'
          )
        return fresh, (extreme, [item for item, key in zip(rows, keys) if key == extreme])
      if cap is None and extreme is not None and extreme != pos:
        return fresh, (extreme, [item for item, key in zip(rows, keys) if key == extreme])
      return fresh, None

    return PaginatedResponse((end, []), next)

  @overload
  async def get_observations(
    self,
    station_id: str,
    *,
    start: TimestampIso | None = None,
    end: TimestampIso | None = None,
    limit: int | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_observations(
    self,
    station_id: str,
    *,
    start: TimestampIso | None = None,
    end: TimestampIso | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> ObservationCollection: ...
  async def get_observations(
    self,
    station_id: str,
    *,
    start: TimestampIso | None = None,
    end: TimestampIso | None = None,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> ObservationCollection:
    """What one station reported over a span of time, newest first. A busy airport station such as `KSEA` reports every five minutes, plus an hourly report at 53 minutes past, so a day there is about 300 observations.

    Args:
      station_id: Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`.
      start: Start of the span, inclusive. The service keeps about a week of observations; a start older than that returns nothing rather than failing.
      end: End of the span, exclusive: an observation at exactly `end` is not returned.
      limit: Observations per response. Range [1, 500]; the service caps a response at 500 whether or not this is sent, so 500 is also the default.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/station_observation_list)
    """
    request: Request = Request(station_id=station_id)
    if start is not None:
      request['start'] = start
    if end is not None:
      request['end'] = end
    if limit is not None:
      request['limit'] = limit
    return await self.request(
      request,
      method='GET',
      path='/stations/{station_id}/observations',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=ObservationCollection,
    )
