# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import StationCollection


class Request(TypedDict):
  """Which grid cell, and how many stations."""

  office: str
  """Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`."""
  grid_x: int
  """Grid column, from `points.get_point`."""
  grid_y: int
  """Grid row, from `points.get_point`."""
  limit: NotRequired[int]
  """Most stations to return, nearest kept. Range [1, 500]; outside it the service answers 400. Without it, every station (73 for SEW 125,68 on 2026-09-30)."""


class ListStationsForGridpoint(Endpoint):
  """The observation stations usable for a grid cell, nearest first. Each carries its `distance` and `bearing` from the cell."""

  @overload
  async def list_stations_for_gridpoint(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    limit: int | None = None,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_stations_for_gridpoint(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> StationCollection: ...
  async def list_stations_for_gridpoint(
    self,
    office: str,
    *,
    grid_x: int,
    grid_y: int,
    limit: int | None = None,
    validate: bool | None = None,
  ) -> StationCollection:
    """The observation stations usable for a grid cell, nearest first. Each carries its `distance` and `bearing` from the cell.

    Args:
      office: Three-letter forecast office code addressing the grid, such as `SEW`. `points.get_point` returns it as `gridId`.
      grid_x: Grid column, from `points.get_point`.
      grid_y: Grid row, from `points.get_point`.
      limit: Most stations to return, nearest kept. Range [1, 500]; outside it the service answers 400. Without it, every station (73 for SEW 125,68 on 2026-09-30).
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/gridpoint_stations)
    """
    request: Request = Request(office=office, grid_x=grid_x, grid_y=grid_y)
    if limit is not None:
      request['limit'] = limit
    return await self.request(
      request,
      method='GET',
      path='/gridpoints/{office}/{grid_x},{grid_y}/stations',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=StationCollection,
    )
