// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { Transmitter } from '../types/index.js'

/** Which transmitter. */
export interface Request {
  /** Call sign, such as `KHB60`. `radio.list_transmitters` and `zones.list_transmitters` return it as `callSign`. */
  call_sign: string
}

export const Request: Codec<Request> = t.object({
  call_sign: t.string,
})

/** One NOAA Weather Radio transmitter, by call sign. */
export class GetTransmitter {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getTransmitter(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One NOAA Weather Radio transmitter, by call sign.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/transmitter
   */
  getTransmitter(request: Request, options?: CallOptions): Promise<Transmitter>
  async getTransmitter(request: Request, options?: CallOptions): Promise<Transmitter> {
    return this.core.request({
      method: 'GET',
      path: '/radio/{call_sign}',
      request,
      requestCodec: Request,
      responseCodec: Transmitter,
      meta: {},
      ...options,
    })
  }
}
