// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { TransmitterCollection } from '../types/index.js'

/** Which page. */
export interface Request {
  /** Page cursor, from the `cursor` query parameter of the previous page's `pagination.next`. Leave it out for the first page. The service does not hand it back on its own -- see the notes -- so it is here for a caller who has one, not for a walk the client drives. */
  cursor?: string
}

export const Request: Codec<Request> = t.object({
  cursor: t.optional(t.string),
})

/** Every NOAA Weather Radio transmitter, a page at a time. JSON-LD, not GeoJSON: the transmitters come as a `@graph`. */
export class ListTransmitters {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listTransmitters(request: Request | undefined, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every NOAA Weather Radio transmitter, a page at a time. JSON-LD, not GeoJSON: the transmitters come as a `@graph`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/transmitters
   */
  listTransmitters(request?: Request, options?: CallOptions & { validate?: true }): Promise<TransmitterCollection>
  /** When validation may be disabled, returned values are typed `unknown`. */
  listTransmitters(request?: Request, options?: CallOptions): Promise<unknown>
  async listTransmitters(request?: Request, options?: CallOptions): Promise<TransmitterCollection> {
    return this.core.request({
      method: 'GET',
      path: '/radio',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: TransmitterCollection,
      meta: {},
      ...options,
    })
  }
}
