// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'

/** Counts of the alerts in effect. Only keys with at least one alert appear in the three maps. */
export interface ActiveAlertCount {
  /** Alerts in effect. */
  total: number
  /** Alerts affecting land zones. */
  land: number
  /** Alerts affecting marine zones. */
  marine: number
  /** Alerts by marine region code, such as `GL`. */
  regions: Record<string, number>
  /** Alerts by state, territory or marine-area code, such as `TX` or `PZ`. */
  areas: Record<string, number>
  /** Alerts by zone or county code, such as `AZC009`. */
  zones: Record<string, number>
}

export const ActiveAlertCount: Codec<ActiveAlertCount> = t.object({
  total: t.integer,
  land: t.integer,
  marine: t.integer,
  regions: t.record(t.integer),
  areas: t.record(t.integer),
  zones: t.record(t.integer),
})

/** Takes nothing. */
export interface Request {}

export const Request: Codec<Request> = t.object({})

/** How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone. */
export class CountActiveAlerts {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  countActiveAlerts(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_count
   */
  countActiveAlerts(request?: Request, options?: CallOptions): Promise<ActiveAlertCount>
  async countActiveAlerts(request?: Request, options?: CallOptions): Promise<ActiveAlertCount> {
    return this.core.request({
      method: 'GET',
      path: '/alerts/active/count',
      request: request ?? {},
      requestCodec: Request,
      responseCodec: ActiveAlertCount,
      meta: {},
      ...options,
    })
  }
}
