// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { AlertCollection } from '../types/index.js'

/** Which marine region. */
export interface Request {
  /** Marine region: `AL` Alaska, `AT` Atlantic, `GL` Great Lakes, `GM` Gulf of Mexico, `PA` Pacific, `PI` Pacific Islands. */
  region: 'AL' | 'AT' | 'GL' | 'GM' | 'PA' | 'PI'
}

export const Request: Codec<Request> = t.object({
  region: t.literal('AL', 'AT', 'GL', 'GM', 'PA', 'PI'),
})

/** The alerts in effect for one marine region. The same as `alerts.get_active_alerts` narrowed by `region`, with the region in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out. */
export class GetActiveAlertsForRegion {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getActiveAlertsForRegion(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alerts in effect for one marine region. The same as `alerts.get_active_alerts` narrowed by `region`, with the region in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_region
   */
  getActiveAlertsForRegion(request: Request, options?: CallOptions): Promise<AlertCollection>
  async getActiveAlertsForRegion(request: Request, options?: CallOptions): Promise<AlertCollection> {
    return this.core.request({
      method: 'GET',
      path: '/alerts/active/region/{region}',
      request,
      requestCodec: Request,
      responseCodec: AlertCollection,
      meta: {},
      ...options,
    })
  }
}
