// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { AlertCollection } from '../types/index.js'

/** Which zone. */
export interface Request {
  /** Forecast zone (`WAZ315`) or county (`AZC009`) code: two letters of state or marine area, `Z` or `C`, three digits. */
  zone_id: string
}

export const Request: Codec<Request> = t.object({
  zone_id: t.string,
})

/** The alerts in effect for one forecast zone or county. The same as `alerts.get_active_alerts` narrowed by `zone`, with the zone in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out. */
export class GetActiveAlertsForZone {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getActiveAlertsForZone(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alerts in effect for one forecast zone or county. The same as `alerts.get_active_alerts` narrowed by `zone`, with the zone in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_zone
   */
  getActiveAlertsForZone(request: Request, options?: CallOptions): Promise<AlertCollection>
  async getActiveAlertsForZone(request: Request, options?: CallOptions): Promise<AlertCollection> {
    return this.core.request({
      method: 'GET',
      path: '/alerts/active/zone/{zone_id}',
      request,
      requestCodec: Request,
      responseCodec: AlertCollection,
      meta: {},
      ...options,
    })
  }
}
