// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { AlertFeature } from '../types/index.js'

/** Which alert. */
export interface Request {
  /** Alert identifier, such as `urn:oid:2.49.0.1.840.0.<hash>.001.1`. `alerts.get_active_alerts` returns it as `properties.id`. */
  id: string
}

export const Request: Codec<Request> = t.object({
  id: t.string,
})

/** One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`. */
export class GetAlert {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getAlert(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_single
   */
  getAlert(request: Request, options?: CallOptions): Promise<AlertFeature>
  async getAlert(request: Request, options?: CallOptions): Promise<AlertFeature> {
    return this.core.request({
      method: 'GET',
      path: '/alerts/{id}',
      request,
      requestCodec: Request,
      responseCodec: AlertFeature,
      meta: {},
      ...options,
    })
  }
}
