// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { AlertCollection, AlertFeature } from '../types/index.js'
import * as countActiveAlerts from './count_active_alerts.js'
import * as getActiveAlerts from './get_active_alerts.js'
import * as getActiveAlertsForArea from './get_active_alerts_for_area.js'
import * as getActiveAlertsForRegion from './get_active_alerts_for_region.js'
import * as getActiveAlertsForZone from './get_active_alerts_for_zone.js'
import * as getAlert from './get_alert.js'
import * as listAlertTypes from './list_alert_types.js'
import * as listAlerts from './list_alerts.js'

/**
 * Watches, warnings and advisories in effect.
 *
 * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active
 */
export class Alerts {
  private readonly countActiveAlerts_: countActiveAlerts.CountActiveAlerts
  private readonly getActiveAlerts_: getActiveAlerts.GetActiveAlerts
  private readonly getActiveAlertsForArea_: getActiveAlertsForArea.GetActiveAlertsForArea
  private readonly getActiveAlertsForRegion_: getActiveAlertsForRegion.GetActiveAlertsForRegion
  private readonly getActiveAlertsForZone_: getActiveAlertsForZone.GetActiveAlertsForZone
  private readonly getAlert_: getAlert.GetAlert
  private readonly listAlertTypes_: listAlertTypes.ListAlertTypes
  private readonly listAlerts_: listAlerts.ListAlerts

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.countActiveAlerts_ = new countActiveAlerts.CountActiveAlerts(core)
    this.getActiveAlerts_ = new getActiveAlerts.GetActiveAlerts(core)
    this.getActiveAlertsForArea_ = new getActiveAlertsForArea.GetActiveAlertsForArea(core)
    this.getActiveAlertsForRegion_ = new getActiveAlertsForRegion.GetActiveAlertsForRegion(core)
    this.getActiveAlertsForZone_ = new getActiveAlertsForZone.GetActiveAlertsForZone(core)
    this.getAlert_ = new getAlert.GetAlert(core)
    this.listAlertTypes_ = new listAlertTypes.ListAlertTypes(core)
    this.listAlerts_ = new listAlerts.ListAlerts(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  countActiveAlerts(request: countActiveAlerts.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * How many alerts are in effect right now, in total and broken down by land and marine, marine region, state or marine area, and zone.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_count
   */
  countActiveAlerts(request?: countActiveAlerts.Request, options?: CallOptions): Promise<countActiveAlerts.ActiveAlertCount>
  countActiveAlerts(request?: countActiveAlerts.Request, options?: CallOptions): Promise<countActiveAlerts.ActiveAlertCount> {
    return this.countActiveAlerts_.countActiveAlerts(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getActiveAlerts(request: getActiveAlerts.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every watch, warning and advisory in effect right now, optionally narrowed. Unnarrowed this is the whole country and runs to a few hundred alerts, so narrow by `area`, `zone` or `point` unless you want all of it.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active
   */
  getActiveAlerts(request?: getActiveAlerts.Request, options?: CallOptions): Promise<AlertCollection>
  getActiveAlerts(request?: getActiveAlerts.Request, options?: CallOptions): Promise<AlertCollection> {
    return this.getActiveAlerts_.getActiveAlerts(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getActiveAlertsForArea(request: getActiveAlertsForArea.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alerts in effect for one state, territory or marine area. The same as `alerts.get_active_alerts` narrowed by `area`, with the area in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_area
   */
  getActiveAlertsForArea(request: getActiveAlertsForArea.Request, options?: CallOptions): Promise<AlertCollection>
  getActiveAlertsForArea(request: getActiveAlertsForArea.Request, options?: CallOptions): Promise<AlertCollection> {
    return this.getActiveAlertsForArea_.getActiveAlertsForArea(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getActiveAlertsForRegion(request: getActiveAlertsForRegion.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alerts in effect for one marine region. The same as `alerts.get_active_alerts` narrowed by `region`, with the region in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_region
   */
  getActiveAlertsForRegion(request: getActiveAlertsForRegion.Request, options?: CallOptions): Promise<AlertCollection>
  getActiveAlertsForRegion(request: getActiveAlertsForRegion.Request, options?: CallOptions): Promise<AlertCollection> {
    return this.getActiveAlertsForRegion_.getActiveAlertsForRegion(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getActiveAlertsForZone(request: getActiveAlertsForZone.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The alerts in effect for one forecast zone or county. The same as `alerts.get_active_alerts` narrowed by `zone`, with the zone in the path. Takes no other filter, so drills and test messages come back too; `alerts.get_active_alerts` with `status: ["actual"]` leaves them out.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_active_zone
   */
  getActiveAlertsForZone(request: getActiveAlertsForZone.Request, options?: CallOptions): Promise<AlertCollection>
  getActiveAlertsForZone(request: getActiveAlertsForZone.Request, options?: CallOptions): Promise<AlertCollection> {
    return this.getActiveAlertsForZone_.getActiveAlertsForZone(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getAlert(request: getAlert.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One alert by its identifier, including the polygon it was drawn for when it has one. The identifiers come from `alerts.get_active_alerts`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_single
   */
  getAlert(request: getAlert.Request, options?: CallOptions): Promise<AlertFeature>
  getAlert(request: getAlert.Request, options?: CallOptions): Promise<AlertFeature> {
    return this.getAlert_.getAlert(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listAlertTypes(request: listAlertTypes.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Every event name the service issues alerts under, such as `Tornado Warning`. These are the values `event` takes on the alert endpoints.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_types
   */
  listAlertTypes(request?: listAlertTypes.Request, options?: CallOptions): Promise<listAlertTypes.AlertTypeList>
  listAlertTypes(request?: listAlertTypes.Request, options?: CallOptions): Promise<listAlertTypes.AlertTypeList> {
    return this.listAlertTypes_.listAlertTypes(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listAlerts(request: listAlerts.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Alerts issued over roughly the last seven days, whether or not they are still in effect, newest first, optionally narrowed. For only what is in effect now, use `alerts.get_active_alerts`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/alerts_query
   */
  listAlerts(request?: listAlerts.Request, options?: CallOptions): Promise<AlertCollection>
  listAlerts(request?: listAlerts.Request, options?: CallOptions): Promise<AlertCollection> {
    return this.listAlerts_.listAlerts(request, options)
  }
}
