// Generated by truewire — do not edit by hand.
/** Shapes shared by two or more endpoints, generated from `spec/schemas.json`. */
import { type Codec, type TimestampIso, t } from '@truewire/core'

/** The area an aviation advisory covers. Shaped like a GeoJSON `Polygon`, but each position is latitude first (`AdvisoryPosition`), so a GeoJSON library draws it transposed. */
export interface AdvisoryPolygon {
  /** Always `Polygon`. */
  type: 'Polygon'
  /** Linear rings; the first is the outer boundary. Each ring repeats its first position as its last. */
  coordinates: (readonly [number, number])[][]
}

export const AdvisoryPolygon: Codec<AdvisoryPolygon> = t.object({
  type: t.literal('Polygon'),
  coordinates: t.array(t.array(t.tuple([t.number, t.number]))),
})

export type AdvisoryPosition = readonly [number, number]

export const AdvisoryPosition: Codec<AdvisoryPosition> = t.tuple([t.number, t.number])

/** The areas covered, as codes rather than prose. */
export interface AlertGeocode {
  /** SAME (Specific Area Message Encoding) codes, one per county. */
  SAME?: string[]
  /** UGC (Universal Geographic Code) zone codes. */
  UGC?: string[]
}

export const AlertGeocode: Codec<AlertGeocode> = t.object({
  SAME: t.optional(t.array(t.string)),
  UGC: t.optional(t.array(t.string)),
})

/** An earlier alert this one updates, corrects or cancels. */
export interface AlertReference {
  /** Identifier of the referenced alert. */
  identifier: string
  /** Who sent the referenced alert. */
  sender?: string
  /** When the referenced alert was sent. */
  sent?: TimestampIso
}

export const AlertReference: Codec<AlertReference> = t.object({
  identifier: t.string,
  sender: t.optional(t.string),
  sent: t.optional(t.dateTime),
})

/** A Center Weather Advisory: a short-fused warning of weather hazardous to aircraft inside one en-route center's airspace. */
export interface CenterWeatherAdvisory {
  /** Canonical URL of the advisory, ending in its issue date and sequence number: the arguments `aviation.get_cwa` takes. */
  id: string
  /** When the advisory was issued. */
  issueTime: TimestampIso
  /** Three-letter code of a Center Weather Service Unit: the NWS meteorologists posted at one FAA air route traffic control center, and named after it (`ZSE` is Seattle Center). */
  cwsu: 'ZAB' | 'ZAN' | 'ZAU' | 'ZBW' | 'ZDC' | 'ZDV' | 'ZFA' | 'ZFW' | 'ZHU' | 'ZID' | 'ZJX' | 'ZKC' | 'ZLA' | 'ZLC' | 'ZMA' | 'ZME' | 'ZMP' | 'ZNY' | 'ZOA' | 'ZOB' | 'ZSE' | 'ZTL'
  /** Sequence number within the day: the hundreds digit numbers a hazard and the rest counts the advisories about it (`101`, `102`, then `201` for a second hazard). Not always unique: measured 2026-09-30, `ZAB` issued two `206`s that day. */
  sequence: number
  /** Start of the period the advisory is valid for. */
  start: TimestampIso
  /** End of the period the advisory is valid for. */
  end: TimestampIso
  /** What the advisory was issued for, as a code URL; null on a few. */
  observedProperty: string | null
  /** The advisory itself, in the abbreviated plain language of aviation weather (`AREA TS MOV LTL TOPS TO FL280`). */
  text: string
}

export const CenterWeatherAdvisory: Codec<CenterWeatherAdvisory> = t.object({
  id: t.string,
  issueTime: t.dateTime,
  cwsu: t.literal('ZAB', 'ZAN', 'ZAU', 'ZBW', 'ZDC', 'ZDV', 'ZFA', 'ZFW', 'ZHU', 'ZID', 'ZJX', 'ZKC', 'ZLA', 'ZLC', 'ZMA', 'ZME', 'ZMP', 'ZNY', 'ZOA', 'ZOB', 'ZSE', 'ZTL'),
  sequence: t.integer,
  start: t.dateTime,
  end: t.dateTime,
  observedProperty: t.nullable(t.string),
  text: t.string,
})

/** Where the next page is. A whole URL, not a bare cursor -- which is why no endpoint returning this declares a pagination strategy. */
export interface CollectionPagination {
  /** URL of the next page, cursor already in the query string. Absent on the last page. */
  next?: string
}

export const CollectionPagination: Codec<CollectionPagination> = t.object({
  next: t.optional(t.string),
})

export type CwsuId = 'ZAB' | 'ZAN' | 'ZAU' | 'ZBW' | 'ZDC' | 'ZDV' | 'ZFA' | 'ZFW' | 'ZHU' | 'ZID' | 'ZJX' | 'ZKC' | 'ZLA' | 'ZLC' | 'ZMA' | 'ZME' | 'ZMP' | 'ZNY' | 'ZOA' | 'ZOB' | 'ZSE' | 'ZTL'

export const CwsuId: Codec<CwsuId> = t.literal('ZAB', 'ZAN', 'ZAU', 'ZBW', 'ZDC', 'ZDV', 'ZFA', 'ZFW', 'ZHU', 'ZID', 'ZJX', 'ZKC', 'ZLA', 'ZLC', 'ZMA', 'ZME', 'ZMP', 'ZNY', 'ZOA', 'ZOB', 'ZSE', 'ZTL')

/** One value of a gridded series, and the interval it holds over. */
export interface GridValue {
  /** ISO 8601 interval this value covers, as `<start>/<duration>` -- one string carrying both, such as `2026-09-09T01:00:00+00:00/PT1H`. */
  validTime: string
  /** The value over `validTime`. */
  value: number | null
}

export const GridValue: Codec<GridValue> = t.object({
  validTime: t.string,
  value: t.nullable(t.number),
})

/** GeoJSON geometry of several disjoint areas -- an alert covering counties that do not touch. */
export interface MultiPolygonGeometry {
  /** Always `MultiPolygon`. */
  type: 'MultiPolygon'
  /** One entry per polygon, each shaped like `PolygonGeometry.coordinates`. */
  coordinates: (readonly [number, number])[][][]
}

export const MultiPolygonGeometry: Codec<MultiPolygonGeometry> = t.object({
  type: t.literal('MultiPolygon'),
  coordinates: t.array(t.array(t.array(t.tuple([t.number, t.number])))),
})

/** Where the next page is, as a whole URL. The declared walk moves the time window instead and never reads this. */
export interface ObservationPagination {
  /** URL of the next page. Absent on the last one. */
  next?: string
}

export const ObservationPagination: Codec<ObservationPagination> = t.object({
  next: t.optional(t.string),
})

/** GeoJSON geometry of a feature that sits at a single place: a station, an observation, a forecast point. */
export interface PointGeometry {
  /** Always `Point` for these features. */
  type: 'Point'
  /** A GeoJSON position: longitude first, then latitude, in WGS 84 decimal degrees. */
  coordinates: readonly [number, number]
}

export const PointGeometry: Codec<PointGeometry> = t.object({
  type: t.literal('Point'),
  coordinates: t.tuple([t.number, t.number]),
})

/** GeoJSON geometry of an area: one outer ring, then any holes. */
export interface PolygonGeometry {
  /** Always `Polygon`. */
  type: 'Polygon'
  /** Linear rings. The first is the outer boundary; any others are holes in it. Each ring repeats its first position as its last. */
  coordinates: (readonly [number, number])[][]
}

export const PolygonGeometry: Codec<PolygonGeometry> = t.object({
  type: t.literal('Polygon'),
  coordinates: t.array(t.array(t.tuple([t.number, t.number]))),
})

export type Position = readonly [number, number]

export const Position: Codec<Position> = t.tuple([t.number, t.number])

/** One present-weather group decoded from the station's METAR. */
export interface PresentWeather {
  /** `light`, `heavy`, or null for moderate. */
  intensity?: string | null
  /** Qualifier such as `patches` or `blowing`. */
  modifier?: string | null
  /** The phenomenon itself: `rain`, `snow`, `fog_mist`, `thunderstorms`. */
  weather?: string | null
  /** The METAR group this was decoded from, such as `-RA`. */
  rawString: string
}

export const PresentWeather: Codec<PresentWeather> = t.object({
  intensity: t.optional(t.nullable(t.string)),
  modifier: t.optional(t.nullable(t.string)),
  weather: t.optional(t.nullable(t.string)),
  rawString: t.string,
})

/** A measurement and the unit it is in. The service never sends a bare number: every value arrives beside the WMO unit code it is expressed in, and `value` is null wherever the measurement is missing rather than zero. */
export interface QuantitativeValue {
  /** WMO unit of measure, as a URI shorthand: `wmoUnit:degC`, `wmoUnit:km_h-1`, `wmoUnit:percent`, `wmoUnit:Pa`, `wmoUnit:m`. */
  unitCode: string
  /** The measurement, or null where there is none. Null is common and is not an error: an airport station reports `windGust` only when there were gusts. */
  value: number | null
  /** Quality-control flag the observation carried: `V` validated, `S` screened, `C` coarse-passed, `Z` preliminary, `Q` questionable. Present on observations, absent on forecasts. */
  qualityControl?: string
  /** Upper end, where the value is a range rather than a point. */
  maxValue?: number
  /** Lower end, where the value is a range rather than a point. */
  minValue?: number
}

export const QuantitativeValue: Codec<QuantitativeValue> = t.object({
  unitCode: t.string,
  value: t.nullable(t.number),
  qualityControl: t.optional(t.string),
  maxValue: t.optional(t.number),
  minValue: t.optional(t.number),
})

/** A SIGMET or AIRMET: a warning to aircraft in flight of significant weather (convection, turbulence, icing, obscured mountains) over an area, issued by an air traffic services unit. */
export interface Sigmet {
  /** URL of the message, ending in its issuing unit, UTC issue date and `HHMM` issue time: the arguments `aviation.get_sigmet` takes. Not unique: every message a unit issues in the same minute shares it. */
  id: string
  /** When the message was issued. */
  issueTime: TimestampIso
  /** Flight information region the message covers; null on some. */
  fir: string | null
  /** The air traffic services unit that issued it, such as `KKCI` (the Aviation Weather Center) or `ANC` (Anchorage). */
  atsu: string
  /** Sequence identifier; null on some. */
  sequence: string | null
  /** The hazard, as a WMO code URL; null on more than half. */
  phenomenon: string | null
  /** Start of the period the message is valid for. */
  start: TimestampIso
  /** End of the period the message is valid for. */
  end: TimestampIso
}

export const Sigmet: Codec<Sigmet> = t.object({
  id: t.string,
  issueTime: t.dateTime,
  fir: t.nullable(t.string),
  atsu: t.string,
  sequence: t.nullable(t.string),
  phenomenon: t.nullable(t.string),
  start: t.dateTime,
  end: t.dateTime,
})

/** One zone: a public forecast, county, fire-weather or marine area. */
export interface Zone {
  /** Canonical URL of the zone. */
  '@id': string
  /** Always `wx:Zone`. */
  '@type'?: 'wx:Zone'
  /** Zone code: two letters of state or marine area, `Z` or `C`, three digits. */
  id: string
  /** The zone type. The service answers with five of these: `public` (what `forecast` and `land` also address), `county`, `fire`, `coastal` and `offshore` (what `marine` also addresses). */
  type: 'land' | 'marine' | 'forecast' | 'public' | 'coastal' | 'offshore' | 'fire' | 'county'
  /** Name of the zone, such as `City of Seattle`. */
  name: string
  /** When this version of the zone took effect. */
  effectiveDate: TimestampIso
  /** When it expires; `2200-01-01` for every zone in effect on 2026-09-30. */
  expirationDate: TimestampIso
  /** State or territory the zone is in. */
  state?: string | null
  /** URL of the office that forecasts for the zone. */
  forecastOffice?: string
  /** Three-letter code of the office's forecast grid, such as `SEW`. */
  gridIdentifier?: string
  /** AWIPS identifier of the forecasting office. */
  awipsLocationIdentifier?: string
  /** Offices whose warning area covers the zone. Deprecated upstream; use `forecastOffice`. */
  cwa?: string[]
  /** URLs of the same offices. Deprecated upstream; use `forecastOffice`. */
  forecastOffices?: string[]
  /** IANA time zones the zone is in; two for a zone that straddles a boundary. */
  timeZone?: string[]
  /** URLs of the observation stations in the zone. Empty for most county, fire and marine zones. */
  observationStations?: string[]
  /** The radar that covers the zone. */
  radarStation?: string | null
}

export const Zone: Codec<Zone> = t.object({
  '@id': t.string,
  '@type': t.optional(t.literal('wx:Zone')),
  id: t.string,
  type: t.literal('land', 'marine', 'forecast', 'public', 'coastal', 'offshore', 'fire', 'county'),
  name: t.string,
  effectiveDate: t.dateTime,
  expirationDate: t.dateTime,
  state: t.optional(t.nullable(t.string)),
  forecastOffice: t.optional(t.string),
  gridIdentifier: t.optional(t.string),
  awipsLocationIdentifier: t.optional(t.string),
  cwa: t.optional(t.array(t.string)),
  forecastOffices: t.optional(t.array(t.string)),
  timeZone: t.optional(t.array(t.string)),
  observationStations: t.optional(t.array(t.string)),
  radarStation: t.optional(t.nullable(t.string)),
})

export type ZoneKind = 'land' | 'marine' | 'forecast' | 'public' | 'coastal' | 'offshore' | 'fire' | 'county'

export const ZoneKind: Codec<ZoneKind> = t.literal('land', 'marine', 'forecast', 'public', 'coastal', 'offshore', 'fire', 'county')

/** One watch, warning or advisory, in the Common Alerting Protocol vocabulary the service issues them in. */
export interface Alert {
  /** Identifier of this alert, such as `urn:oid:2.49.0.1.840.0.<hash>.001.1`. This is what `alerts.get_alert` takes. */
  id: string
  /** Semicolon-separated names of the areas covered. */
  areaDesc: string
  geocode?: AlertGeocode
  /** URLs of the forecast zones covered. */
  affectedZones?: string[]
  /** Earlier alerts this one supersedes. */
  references?: AlertReference[]
  /** When the alert was sent. */
  sent: TimestampIso
  /** When it takes effect. */
  effective: TimestampIso
  /** When the event itself is expected to begin, if later than `effective`. */
  onset?: TimestampIso | null
  /** When the alert expires unless updated. */
  expires: TimestampIso
  /** When the event itself is expected to end. */
  ends?: TimestampIso | null
  /** Whether this is a real alert. Filter on `Actual` unless you want drills. */
  status: 'Actual' | 'Exercise' | 'System' | 'Test' | 'Draft'
  /** Whether this issues, updates or cancels. */
  messageType: 'Alert' | 'Update' | 'Cancel' | 'Ack' | 'Error'
  /** Broad category; `Met` for weather. */
  category?: 'Met' | 'Geo' | 'Safety' | 'Security' | 'Rescue' | 'Fire' | 'Health' | 'Env' | 'Transport' | 'Infra' | 'CBRNE' | 'Other'
  /** How bad the impact would be. */
  severity: 'Extreme' | 'Severe' | 'Moderate' | 'Minor' | 'Unknown'
  /** How likely it is to happen. */
  certainty: 'Observed' | 'Likely' | 'Possible' | 'Unlikely' | 'Unknown'
  /** How soon to act. */
  urgency: 'Immediate' | 'Expected' | 'Future' | 'Past' | 'Unknown'
  /** The event name, such as `Flood Watch` or `Red Flag Warning`. */
  event: string
  /** Email address of the sender. */
  sender?: string
  /** The issuing office, such as `NWS Seattle WA`. */
  senderName: string
  /** One-line summary with the times spelled out. */
  headline?: string | null
  /** The full text of the alert. */
  description: string
  /** What the public is being told to do. */
  instruction?: string | null
  /** The recommended action. */
  response?: 'Shelter' | 'Evacuate' | 'Prepare' | 'Execute' | 'Avoid' | 'Monitor' | 'AllClear' | 'Assess' | 'None'
  /** Free-form parameters the issuing system attached: `NWSheadline`, `VTEC`, `AWIPSidentifier` and others. Every value is a list, even when it holds one item. */
  parameters?: Record<string, string[]>
}

export const Alert: Codec<Alert> = t.object({
  id: t.string,
  areaDesc: t.string,
  geocode: t.optional(AlertGeocode),
  affectedZones: t.optional(t.array(t.string)),
  references: t.optional(t.array(AlertReference)),
  sent: t.dateTime,
  effective: t.dateTime,
  onset: t.optional(t.nullable(t.dateTime)),
  expires: t.dateTime,
  ends: t.optional(t.nullable(t.dateTime)),
  status: t.literal('Actual', 'Exercise', 'System', 'Test', 'Draft'),
  messageType: t.literal('Alert', 'Update', 'Cancel', 'Ack', 'Error'),
  category: t.optional(t.literal('Met', 'Geo', 'Safety', 'Security', 'Rescue', 'Fire', 'Health', 'Env', 'Transport', 'Infra', 'CBRNE', 'Other')),
  severity: t.literal('Extreme', 'Severe', 'Moderate', 'Minor', 'Unknown'),
  certainty: t.literal('Observed', 'Likely', 'Possible', 'Unlikely', 'Unknown'),
  urgency: t.literal('Immediate', 'Expected', 'Future', 'Past', 'Unknown'),
  event: t.string,
  sender: t.optional(t.string),
  senderName: t.string,
  headline: t.optional(t.nullable(t.string)),
  description: t.string,
  instruction: t.optional(t.nullable(t.string)),
  response: t.optional(t.literal('Shelter', 'Evacuate', 'Prepare', 'Execute', 'Avoid', 'Monitor', 'AllClear', 'Assess', 'None')),
  parameters: t.optional(t.record(t.array(t.string))),
})

export type AlertGeometry = PolygonGeometry | MultiPolygonGeometry | null

export const AlertGeometry: Codec<AlertGeometry> = t.union(PolygonGeometry, MultiPolygonGeometry, t.null)

/** One Center Weather Advisory, in the GeoJSON feature the API wraps it in. The feature has no `id` of its own; the advisory's URL is `properties.id`. */
export interface CenterWeatherAdvisoryFeature {
  /** Always `Feature`. */
  type: 'Feature'
  /** The area the advisory covers, latitude first; null on some. */
  geometry: AdvisoryPolygon | null
  /** The advisory itself. */
  properties: CenterWeatherAdvisory
}

export const CenterWeatherAdvisoryFeature: Codec<CenterWeatherAdvisoryFeature> = t.object({
  type: t.literal('Feature'),
  geometry: t.nullable(AdvisoryPolygon),
  properties: CenterWeatherAdvisory,
})

/** One reported cloud layer: how much of the sky it covers and how high its base is. */
export interface CloudLayer {
  /** Height of the layer's base above the station. */
  base: QuantitativeValue
  /** METAR sky-cover code: `OVC` overcast, `BKN` broken, `SCT` scattered, `FEW` few, `SKC`/`CLR` clear, `VV` vertical visibility (sky obscured). */
  amount: 'OVC' | 'BKN' | 'SCT' | 'FEW' | 'SKC' | 'CLR' | 'VV'
}

export const CloudLayer: Codec<CloudLayer> = t.object({
  base: QuantitativeValue,
  amount: t.literal('OVC', 'BKN', 'SCT', 'FEW', 'SKC', 'CLR', 'VV'),
})

/** One period of a narrative forecast: a named half-day in the twice-daily forecast, or one hour in the hourly one. */
export interface ForecastPeriod {
  /** Sequence number within the forecast, starting at 1. */
  number: number
  /** Name of the period, such as `Tonight` or `Wednesday`. Empty in the hourly forecast, which names nothing. */
  name: string
  /** When the period begins, in the forecast point's own local time. */
  startTime: TimestampIso
  /** When the period ends. */
  endTime: TimestampIso
  /** Whether this is a daytime period. */
  isDaytime: boolean
  /** Forecast temperature, in `temperatureUnit`. A bare number here, unlike everywhere else in this API. */
  temperature: number
  /** Unit `temperature` is in: `F` under `units=us`, `C` under `units=si`. */
  temperatureUnit: 'F' | 'C'
  /** `rising` or `falling` where the temperature moves against the usual daily cycle. */
  temperatureTrend?: string | null
  /** Chance of measurable precipitation. */
  probabilityOfPrecipitation?: QuantitativeValue
  /** Forecast dew point. Hourly forecasts only. */
  dewpoint?: QuantitativeValue
  /** Forecast relative humidity. Hourly forecasts only. */
  relativeHumidity?: QuantitativeValue
  /** Wind speed as prose with its unit, such as `5 to 10 mph`. A string, not a `QuantitativeValue`. */
  windSpeed: string
  /** Compass direction the wind comes from, such as `NNE`. */
  windDirection: string
  /** URL of an icon for the period. */
  icon?: string
  /** A few words, such as `Partly Sunny`. */
  shortForecast: string
  /** A sentence or two. Empty in the hourly forecast. */
  detailedForecast: string
}

export const ForecastPeriod: Codec<ForecastPeriod> = t.object({
  number: t.integer,
  name: t.string,
  startTime: t.dateTime,
  endTime: t.dateTime,
  isDaytime: t.boolean,
  temperature: t.number,
  temperatureUnit: t.literal('F', 'C'),
  temperatureTrend: t.optional(t.nullable(t.string)),
  probabilityOfPrecipitation: t.optional(QuantitativeValue),
  dewpoint: t.optional(QuantitativeValue),
  relativeHumidity: t.optional(QuantitativeValue),
  windSpeed: t.string,
  windDirection: t.string,
  icon: t.optional(t.string),
  shortForecast: t.string,
  detailedForecast: t.string,
})

/** One gridded series: a unit and a run of intervals, each with its own value. Consecutive intervals with the same value are collapsed into one, so the series is not evenly spaced. */
export interface GridSeries {
  /** WMO unit code every value is in. */
  uom?: string
  /** The values, in time order. */
  values: GridValue[]
}

export const GridSeries: Codec<GridSeries> = t.object({
  uom: t.optional(t.string),
  values: t.array(GridValue),
})

/** One SIGMET or AIRMET, in the GeoJSON feature the API wraps it in. The feature has no `id` of its own; the message's URL is `properties.id`. */
export interface SigmetFeature {
  /** Always `Feature`. */
  type: 'Feature'
  /** The area the message covers, latitude first; null on some. */
  geometry: AdvisoryPolygon | null
  /** The message itself. */
  properties: Sigmet
}

export const SigmetFeature: Codec<SigmetFeature> = t.object({
  type: t.literal('Feature'),
  geometry: t.nullable(AdvisoryPolygon),
  properties: Sigmet,
})

/** One observation station. */
export interface Station {
  /** Station identifier, such as `KSEA`. This is what `stations.get_observations` takes. */
  stationIdentifier: string
  /** Human-readable station name. */
  name: string
  /** IANA time zone the station is in, such as `America/Los_Angeles`. */
  timeZone?: string
  /** Station elevation above sea level. */
  elevation?: QuantitativeValue
  /** URL of the forecast zone the station is in. */
  forecast?: string
  /** URL of the county zone the station is in. */
  county?: string
  /** URL of the fire-weather zone the station is in. */
  fireWeatherZone?: string
  /** Network the station belongs to, such as `NWS/FAA` or `MesoWest`. */
  provider?: string
  /** Operator within the network. */
  subProvider?: string
  /** How far the station is from the grid cell asked about. Only `stations.list_stations_for_gridpoint` sends it. */
  distance?: QuantitativeValue
  /** Direction from the grid cell to the station, in degrees clockwise from true north. Only `stations.list_stations_for_gridpoint` sends it. */
  bearing?: QuantitativeValue
}

export const Station: Codec<Station> = t.object({
  stationIdentifier: t.string,
  name: t.string,
  timeZone: t.optional(t.string),
  elevation: t.optional(QuantitativeValue),
  forecast: t.optional(t.string),
  county: t.optional(t.string),
  fireWeatherZone: t.optional(t.string),
  provider: t.optional(t.string),
  subProvider: t.optional(t.string),
  distance: t.optional(QuantitativeValue),
  bearing: t.optional(QuantitativeValue),
})

/** One zone, in the GeoJSON feature the API wraps it in. */
export interface ZoneFeature {
  /** Canonical URL of the zone. */
  id: string
  /** Always `Feature`. */
  type: 'Feature'
  /** The area a zone covers. */
  geometry: PolygonGeometry | MultiPolygonGeometry | null
  /** The zone itself. */
  properties: Zone
}

export const ZoneFeature: Codec<ZoneFeature> = t.object({
  id: t.string,
  type: t.literal('Feature'),
  geometry: t.union(PolygonGeometry, MultiPolygonGeometry, t.null),
  properties: Zone,
})

export type ZoneGeometry = PolygonGeometry | MultiPolygonGeometry | null

export const ZoneGeometry: Codec<ZoneGeometry> = t.union(PolygonGeometry, MultiPolygonGeometry, t.null)

/** One alert, in the GeoJSON feature the API wraps it in. */
export interface AlertFeature {
  /** Canonical URL of this alert. */
  id: string
  /** Always `Feature`. */
  type: 'Feature'
  /** The area an alert covers, when it was drawn as a polygon rather than named as zones. */
  geometry?: PolygonGeometry | MultiPolygonGeometry | null
  /** The alert itself. */
  properties: Alert
}

export const AlertFeature: Codec<AlertFeature> = t.object({
  id: t.string,
  type: t.literal('Feature'),
  geometry: t.optional(t.union(PolygonGeometry, MultiPolygonGeometry, t.null)),
  properties: Alert,
})

/** Center Weather Advisories, as a GeoJSON feature collection, newest first. The service keeps about a week of them and answers all of them at once: there is no paging. */
export interface CenterWeatherAdvisoryCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The advisories; empty when the unit issued none this week. */
  features: CenterWeatherAdvisoryFeature[]
}

export const CenterWeatherAdvisoryCollection: Codec<CenterWeatherAdvisoryCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(CenterWeatherAdvisoryFeature),
})

/** A narrative forecast for one grid cell, as a list of periods. Named for the service's own term: `/gridpoints/{office}/{x},{y}/forecast` is the gridpoint forecast. */
export interface GridpointForecast {
  /** Unit system the periods are rendered in. */
  units: 'us' | 'si'
  /** Which generator produced it, such as `BaselineForecastGenerator`. */
  forecastGenerator?: string
  /** When this rendering was generated. */
  generatedAt: TimestampIso
  /** When the underlying grid data was last updated. */
  updateTime: TimestampIso
  /** ISO 8601 interval the forecast covers, as `<start>/<duration>`. */
  validTimes: string
  /** Elevation of the grid cell. */
  elevation?: QuantitativeValue
  /** The forecast periods, in order. */
  periods: ForecastPeriod[]
}

export const GridpointForecast: Codec<GridpointForecast> = t.object({
  units: t.literal('us', 'si'),
  forecastGenerator: t.optional(t.string),
  generatedAt: t.dateTime,
  updateTime: t.dateTime,
  validTimes: t.string,
  elevation: t.optional(QuantitativeValue),
  periods: t.array(ForecastPeriod),
})

/** One observation from one station, at one moment. Every measurement is a `QuantitativeValue`, and any of them can be null. */
export interface Observation {
  /** URL of the station that reported it. */
  station: string
  /** Station identifier, such as `KSEA`. */
  stationId?: string
  /** Human-readable station name. */
  stationName?: string
  /** When the observation was taken. */
  timestamp: TimestampIso
  /** The raw METAR the observation was decoded from; empty for stations that do not report one. */
  rawMessage?: string
  /** Short plain-language summary, such as `Mostly Cloudy`. */
  textDescription?: string
  /** URL of a weather icon for the observation. */
  icon?: string | null
  /** Station elevation above sea level. */
  elevation?: QuantitativeValue
  /** Present-weather groups decoded from the METAR; empty when nothing was reported. */
  presentWeather?: PresentWeather[]
  /** Air temperature. */
  temperature: QuantitativeValue
  /** Dew point. */
  dewpoint: QuantitativeValue
  /** Direction the wind is coming from, in degrees clockwise from true north. */
  windDirection?: QuantitativeValue
  /** Sustained wind speed. */
  windSpeed: QuantitativeValue
  /** Peak gust; its `value` is null when there were no gusts. */
  windGust?: QuantitativeValue
  /** Station pressure. */
  barometricPressure?: QuantitativeValue
  /** Pressure reduced to sea level. */
  seaLevelPressure?: QuantitativeValue
  /** Horizontal visibility. */
  visibility?: QuantitativeValue
  /** Highest temperature in the last 24 hours; reported once a day. */
  maxTemperatureLast24Hours?: QuantitativeValue
  /** Lowest temperature in the last 24 hours; reported once a day. */
  minTemperatureLast24Hours?: QuantitativeValue
  /** Precipitation accumulated in the last hour. */
  precipitationLastHour?: QuantitativeValue
  /** Precipitation accumulated in the last three hours. */
  precipitationLast3Hours?: QuantitativeValue
  /** Precipitation accumulated in the last six hours. */
  precipitationLast6Hours?: QuantitativeValue
  /** Relative humidity. */
  relativeHumidity?: QuantitativeValue
  /** Wind chill; its `value` is null unless it is cold and windy enough to compute one. */
  windChill?: QuantitativeValue
  /** Heat index; its `value` is null unless it is hot and humid enough to compute one. */
  heatIndex?: QuantitativeValue
  /** Reported cloud layers, lowest first. */
  cloudLayers: CloudLayer[]
}

export const Observation: Codec<Observation> = t.object({
  station: t.string,
  stationId: t.optional(t.string),
  stationName: t.optional(t.string),
  timestamp: t.dateTime,
  rawMessage: t.optional(t.string),
  textDescription: t.optional(t.string),
  icon: t.optional(t.nullable(t.string)),
  elevation: t.optional(QuantitativeValue),
  presentWeather: t.optional(t.array(PresentWeather)),
  temperature: QuantitativeValue,
  dewpoint: QuantitativeValue,
  windDirection: t.optional(QuantitativeValue),
  windSpeed: QuantitativeValue,
  windGust: t.optional(QuantitativeValue),
  barometricPressure: t.optional(QuantitativeValue),
  seaLevelPressure: t.optional(QuantitativeValue),
  visibility: t.optional(QuantitativeValue),
  maxTemperatureLast24Hours: t.optional(QuantitativeValue),
  minTemperatureLast24Hours: t.optional(QuantitativeValue),
  precipitationLastHour: t.optional(QuantitativeValue),
  precipitationLast3Hours: t.optional(QuantitativeValue),
  precipitationLast6Hours: t.optional(QuantitativeValue),
  relativeHumidity: t.optional(QuantitativeValue),
  windChill: t.optional(QuantitativeValue),
  heatIndex: t.optional(QuantitativeValue),
  cloudLayers: t.array(CloudLayer),
})

/** SIGMETs and AIRMETs, as a GeoJSON feature collection, newest first. The service keeps about a week of them and answers everything that matched at once: there is no paging. */
export interface SigmetCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The messages. */
  features: SigmetFeature[]
}

export const SigmetCollection: Codec<SigmetCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(SigmetFeature),
})

/** One station, in the GeoJSON feature the API wraps it in. */
export interface StationFeature {
  /** Canonical URL of this station. */
  id: string
  /** Always `Feature`. */
  type: 'Feature'
  /** Where the station is. */
  geometry?: PointGeometry
  /** The station itself. */
  properties: Station
}

export const StationFeature: Codec<StationFeature> = t.object({
  id: t.string,
  type: t.literal('Feature'),
  geometry: t.optional(PointGeometry),
  properties: Station,
})

/** Zones, as a GeoJSON feature collection, ordered by code. */
export interface ZoneCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The zones. */
  features: ZoneFeature[]
}

export const ZoneCollection: Codec<ZoneCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(ZoneFeature),
})

/** One observation, in the GeoJSON feature the API wraps it in. */
export interface ObservationFeature {
  /** Canonical URL of this observation. */
  id: string
  /** Always `Feature`. */
  type: 'Feature'
  /** Where the station is. */
  geometry?: PointGeometry
  /** The observation itself. */
  properties: Observation
}

export const ObservationFeature: Codec<ObservationFeature> = t.object({
  id: t.string,
  type: t.literal('Feature'),
  geometry: t.optional(PointGeometry),
  properties: Observation,
})

/** Stations, as a GeoJSON feature collection. */
export interface StationCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The stations. */
  features: StationFeature[]
  /** The same stations as bare URLs, in the same order. */
  observationStations?: string[]
  pagination?: CollectionPagination
}

export const StationCollection: Codec<StationCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(StationFeature),
  observationStations: t.optional(t.array(t.string)),
  pagination: t.optional(CollectionPagination),
})

/** Observations over a span, as a GeoJSON feature collection, newest first. */
export interface ObservationCollection {
  /** Always `FeatureCollection`. */
  type: 'FeatureCollection'
  /** The observations, newest first. */
  features: ObservationFeature[]
  pagination?: ObservationPagination
}

export const ObservationCollection: Codec<ObservationCollection> = t.object({
  type: t.literal('FeatureCollection'),
  features: t.array(ObservationFeature),
  pagination: t.optional(ObservationPagination),
})
