# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, NotRequired, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import PointGeometry, QuantitativeValue


class Request(TypedDict):
  """The coordinates to resolve."""

  latitude: float
  """Latitude in WGS 84 decimal degrees. The service rounds to four decimal places and redirects anything longer, so pass no more precision than that."""
  longitude: float
  """Longitude in WGS 84 decimal degrees, negative west of the prime meridian."""


class RelativeLocation(TypedDict):
  """Which place, and how far away."""

  city: str
  """City name."""
  state: str
  """Two-letter state code."""
  distance: NotRequired[QuantitativeValue]
  bearing: NotRequired[QuantitativeValue]


class RelativeLocationFeature(TypedDict):
  """The nearest named place, as its own GeoJSON feature."""

  type: Literal['Feature']
  """Always `Feature`."""
  geometry: NotRequired[PointGeometry]
  properties: RelativeLocation


class Point(TypedDict):
  """What the coordinates resolve to."""

  cwa: NotRequired[str]
  """County warning area: the three-letter code of the office responsible, such as `SEW`. Identical to `gridId`."""
  gridId: str
  """Forecast office code addressing the grid, such as `SEW`. Pass this as `office` to the `forecast` endpoints."""
  gridX: int
  """Grid column. Pass this as `grid_x`."""
  gridY: int
  """Grid row. Pass this as `grid_y`."""
  forecastOffice: NotRequired[str]
  """URL of the responsible office."""
  forecast: str
  """URL of the twice-daily forecast for this cell."""
  forecastHourly: str
  """URL of the hourly forecast for this cell."""
  forecastGridData: str
  """URL of the raw gridded data both forecasts are rendered from."""
  observationStations: str
  """URL of the stations that observe this cell."""
  forecastZone: NotRequired[str]
  """URL of the forecast zone the point is in."""
  county: NotRequired[str]
  """URL of the county zone the point is in."""
  fireWeatherZone: NotRequired[str]
  """URL of the fire-weather zone the point is in."""
  timeZone: str
  """IANA time zone of the point, such as `America/Los_Angeles`. Forecast period times are in this zone."""
  radarStation: NotRequired[str]
  """Identifier of the radar covering the point, such as `KATX`."""
  relativeLocation: NotRequired[RelativeLocationFeature]


class GetPoint(Endpoint):
  """Resolve a latitude/longitude to the forecast grid it falls in. Almost every other endpoint here is addressed by grid cell rather than by coordinates, so this is where a caller starts: it returns the office and the grid indices `forecast.get_forecast` takes, plus the zones, the radar station and the nearest city."""

  @overload
  async def get_point(
    self,
    *,
    latitude: float,
    longitude: float,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def get_point(
    self,
    *,
    latitude: float,
    longitude: float,
    validate: bool | None = None,
  ) -> Point: ...
  async def get_point(
    self,
    *,
    latitude: float,
    longitude: float,
    validate: bool | None = None,
  ) -> Point:
    """Resolve a latitude/longitude to the forecast grid it falls in. Almost every other endpoint here is addressed by grid cell rather than by coordinates, so this is where a caller starts: it returns the office and the grid indices `forecast.get_forecast` takes, plus the zones, the radar station and the nearest city.

    Args:
      latitude: Latitude in WGS 84 decimal degrees. The service rounds to four decimal places and redirects anything longer, so pass no more precision than that.
      longitude: Longitude in WGS 84 decimal degrees, negative west of the prime meridian.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/point)
    """
    return await self.request(
      Request(latitude=latitude, longitude=longitude),
      method='GET',
      path='/points/{latitude},{longitude}',
      meta={'payload': 'properties'},
      validate=validate,
      request_type=Request,
      response_type=Point,
    )
