//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

use crate::types::Transmitter;

/// Which transmitter.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Call sign, such as `KHB60`. `radio.list_transmitters` and `zones.list_transmitters` return it as `callSign`.
    pub call_sign: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new(call_sign: String) -> Self {
        Self {
            call_sign,
            extra: Default::default(),
        }
    }
}

/// One NOAA Weather Radio transmitter, by call sign.
#[derive(Clone)]
pub struct GetTransmitter {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetTransmitter {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One NOAA Weather Radio transmitter, by call sign.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/transmitter>.
    pub async fn get_transmitter(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<Transmitter> {
        let raw = self.get_transmitter_raw(request, options).await?;
        decode(raw)
    }

    /// `get_transmitter` without validation: the wire body as it came.
    pub async fn get_transmitter_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/radio/{call_sign}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
