// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { CwsuId } from '../types/index.js'

/** Where the unit is. */
export interface CenterWeatherServiceUnitAddress {
  /** Street address. */
  streetAddress?: string
  /** City. */
  addressLocality?: string
  /** Two-letter state code. */
  addressRegion?: string
  /** ZIP code. */
  postalCode?: string
}

export const CenterWeatherServiceUnitAddress: Codec<CenterWeatherServiceUnitAddress> = t.object({
  streetAddress: t.optional(t.string),
  addressLocality: t.optional(t.string),
  addressRegion: t.optional(t.string),
  postalCode: t.optional(t.string),
})

/** The unit. A schema.org `GovernmentOrganization`, like `offices.get_office`, but without the zones and stations an office is responsible for. */
export interface CenterWeatherServiceUnit {
  /** The unit's code. */
  id: CwsuId
  /** The center it serves, such as `Seattle, WA`. */
  name: string
  address?: CenterWeatherServiceUnitAddress
  /** Public telephone number; often empty. */
  telephone?: string
  /** Fax number; often empty. */
  faxNumber?: string
  /** Contact address. */
  email?: string
  /** The unit's own website. */
  sameAs?: string
  /** NWS region the unit belongs to, such as `wr` for Western. */
  nwsRegion?: string
}

export const CenterWeatherServiceUnit: Codec<CenterWeatherServiceUnit> = t.object({
  id: CwsuId,
  name: t.string,
  address: t.optional(CenterWeatherServiceUnitAddress),
  telephone: t.optional(t.string),
  faxNumber: t.optional(t.string),
  email: t.optional(t.string),
  sameAs: t.optional(t.string),
  nwsRegion: t.optional(t.string),
})

/** Which unit. */
export interface Request {
  /** The unit, such as `ZSE` for Seattle Center. */
  cwsu_id: CwsuId
}

export const Request: Codec<Request> = t.object({
  cwsu_id: CwsuId,
})

/** One Center Weather Service Unit: where it is and how to reach it. */
export class GetCwsu {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getCwsu(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One Center Weather Service Unit: where it is and how to reach it.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/cwsu
   */
  getCwsu(request: Request, options?: CallOptions): Promise<CenterWeatherServiceUnit>
  async getCwsu(request: Request, options?: CallOptions): Promise<CenterWeatherServiceUnit> {
    return this.core.request({
      method: 'GET',
      path: '/aviation/cwsus/{cwsu_id}',
      request,
      requestCodec: Request,
      responseCodec: CenterWeatherServiceUnit,
      meta: {},
      ...options,
    })
  }
}
