// Generated by truewire — do not edit by hand.
import type { CallOptions, HttpEndpoint } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import type { CenterWeatherAdvisoryCollection, CenterWeatherAdvisoryFeature, SigmetCollection, SigmetFeature } from '../types/index.js'
import * as getCwa from './get_cwa.js'
import * as getCwsu from './get_cwsu.js'
import * as getSigmet from './get_sigmet.js'
import * as listCwas from './list_cwas.js'
import * as listSigmets from './list_sigmets.js'
import * as listSigmetsForAtsu from './list_sigmets_for_atsu.js'
import * as listSigmetsForAtsuOnDate from './list_sigmets_for_atsu_on_date.js'

/**
 * Aviation weather: the Center Weather Service Units at the FAA's en-route centers and the advisories they issue, and the SIGMETs and AIRMETs that warn aircraft in flight of significant weather.
 *
 * @see https://www.weather.gov/documentation/services-web-api#/default/sigmetQuery
 */
export class Aviation {
  private readonly getCwa_: getCwa.GetCwa
  private readonly getCwsu_: getCwsu.GetCwsu
  private readonly getSigmet_: getSigmet.GetSigmet
  private readonly listCwas_: listCwas.ListCwas
  private readonly listSigmets_: listSigmets.ListSigmets
  private readonly listSigmetsForAtsu_: listSigmetsForAtsu.ListSigmetsForAtsu
  private readonly listSigmetsForAtsuOnDate_: listSigmetsForAtsuOnDate.ListSigmetsForAtsuOnDate

  constructor(readonly core: HttpEndpoint<DefaultMeta>) {
    this.getCwa_ = new getCwa.GetCwa(core)
    this.getCwsu_ = new getCwsu.GetCwsu(core)
    this.getSigmet_ = new getSigmet.GetSigmet(core)
    this.listCwas_ = new listCwas.ListCwas(core)
    this.listSigmets_ = new listSigmets.ListSigmets(core)
    this.listSigmetsForAtsu_ = new listSigmetsForAtsu.ListSigmetsForAtsu(core)
    this.listSigmetsForAtsuOnDate_ = new listSigmetsForAtsuOnDate.ListSigmetsForAtsuOnDate(core)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getCwa(request: getCwa.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One Center Weather Advisory, with its area. A unit occasionally gives two advisories one sequence number on one day (measured 2026-09-30, `ZAB` issued two `206`s), and the service then answers one of them; `aviation.list_cwas` holds both.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/cwa
   */
  getCwa(request: getCwa.Request, options?: CallOptions): Promise<CenterWeatherAdvisoryFeature>
  getCwa(request: getCwa.Request, options?: CallOptions): Promise<CenterWeatherAdvisoryFeature> {
    return this.getCwa_.getCwa(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getCwsu(request: getCwsu.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One Center Weather Service Unit: where it is and how to reach it.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/cwsu
   */
  getCwsu(request: getCwsu.Request, options?: CallOptions): Promise<getCwsu.CenterWeatherServiceUnit>
  getCwsu(request: getCwsu.Request, options?: CallOptions): Promise<getCwsu.CenterWeatherServiceUnit> {
    return this.getCwsu_.getCwsu(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getSigmet(request: getSigmet.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * One SIGMET or AIRMET, with its area, named by its unit and the UTC date and minute it was issued. Several messages a unit issues in the same minute share that name, and the service then answers one of them: measured 2026-09-30, `KKCI/2026-09-30/2355` answered the Kansas City region's SIGMET out of the several `KKCI` issued at 23:55. To see them all, filter `aviation.list_sigmets_for_atsu_on_date`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/sigmet
   */
  getSigmet(request: getSigmet.Request, options?: CallOptions): Promise<SigmetFeature>
  getSigmet(request: getSigmet.Request, options?: CallOptions): Promise<SigmetFeature> {
    return this.getSigmet_.getSigmet(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listCwas(request: listCwas.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The Center Weather Advisories one unit has issued in about the last week, newest first.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/cwas
   */
  listCwas(request: listCwas.Request, options?: CallOptions): Promise<CenterWeatherAdvisoryCollection>
  listCwas(request: listCwas.Request, options?: CallOptions): Promise<CenterWeatherAdvisoryCollection> {
    return this.listCwas_.listCwas(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listSigmets(request: listSigmets.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * SIGMETs and AIRMETs from every unit, newest first, from about the last week. Unfiltered this is a large response (1.5 MB measured); narrow it by `date`, `start` or `sequence`, or ask one unit through `aviation.list_sigmets_for_atsu`.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/sigmetQuery
   */
  listSigmets(request?: listSigmets.Request, options?: CallOptions): Promise<SigmetCollection>
  listSigmets(request?: listSigmets.Request, options?: CallOptions): Promise<SigmetCollection> {
    return this.listSigmets_.listSigmets(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listSigmetsForAtsu(request: listSigmetsForAtsu.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The SIGMETs and AIRMETs one unit has issued in about the last week, newest first.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/sigmetsByATSU
   */
  listSigmetsForAtsu(request: listSigmetsForAtsu.Request, options?: CallOptions): Promise<SigmetCollection>
  listSigmetsForAtsu(request: listSigmetsForAtsu.Request, options?: CallOptions): Promise<SigmetCollection> {
    return this.listSigmetsForAtsu_.listSigmetsForAtsu(request, options)
  }

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  listSigmetsForAtsuOnDate(request: listSigmetsForAtsuOnDate.Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * The SIGMETs and AIRMETs one unit issued on one UTC date, newest first.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/sigmetsByATSUByDate
   */
  listSigmetsForAtsuOnDate(request: listSigmetsForAtsuOnDate.Request, options?: CallOptions): Promise<SigmetCollection>
  listSigmetsForAtsuOnDate(request: listSigmetsForAtsuOnDate.Request, options?: CallOptions): Promise<SigmetCollection> {
    return this.listSigmetsForAtsuOnDate_.listSigmetsForAtsuOnDate(request, options)
  }
}
