//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

use crate::types::OfficeHeadline;

/// Which office, and which headline.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`.
    pub office_id: String,
    /// Headline id, such as `058e41fd34b935b395e9aaf0fe175dc9`. `offices.list_headlines` returns it as `id`.
    pub headline_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new(office_id: String, headline_id: String) -> Self {
        Self {
            office_id,
            headline_id,
            extra: Default::default(),
        }
    }
}

/// One news headline an office has posted.
#[derive(Clone)]
pub struct GetHeadline {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetHeadline {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One news headline an office has posted.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/office_headline>.
    pub async fn get_headline(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<OfficeHeadline> {
        let raw = self.get_headline_raw(request, options).await?;
        decode(raw)
    }

    /// `get_headline` without validation: the wire body as it came.
    pub async fn get_headline_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/offices/{office_id}/headlines/{headline_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
