//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

use crate::types::OfficeHeadline;

/// Which office.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`.
    pub office_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The headlines, as a JSON-LD graph.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct OfficeHeadlineCollection {
    /// The headlines. Empty for an office that has posted none.
    #[serde(rename = "@graph")]
    pub at_graph: Vec<OfficeHeadline>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new(office_id: String) -> Self {
        Self {
            office_id,
            extra: Default::default(),
        }
    }
}

/// The news headlines an office has posted.
#[derive(Clone)]
pub struct ListHeadlines {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListHeadlines {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The news headlines an office has posted.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/office_headlines>.
    pub async fn list_headlines(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<OfficeHeadlineCollection> {
        let raw = self.list_headlines_raw(request, options).await?;
        decode(raw)
    }

    /// `list_headlines` without validation: the wire body as it came.
    pub async fn list_headlines_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/offices/{office_id}/headlines",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
