//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso};

use crate::meta::DefaultMeta;

/// Which office.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Three-letter office code, such as `AKQ`. `points.get_point` returns it as `gridId`.
    pub office_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One weather story: a graphic, and the text that goes with it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct WeatherStory {
    /// Code of the office that issued it, such as `AKQ`.
    #[serde(rename = "officeId")]
    pub office_id: String,
    /// When the story took effect.
    #[serde(rename = "startTime")]
    pub start_time: TimestampIso,
    /// When it stops being current.
    #[serde(rename = "endTime")]
    pub end_time: TimestampIso,
    /// When it was last updated.
    #[serde(rename = "updateTime")]
    pub update_time: TimestampIso,
    /// Title, such as `Today's Forecast`.
    pub title: String,
    /// The story as plain text.
    pub description: String,
    /// Alternative text for the graphic.
    #[serde(rename = "altText")]
    pub alt_text: String,
    /// Whether the office flagged it as a priority.
    pub priority: bool,
    /// Where the office places it among its stories, lowest first.
    pub order: i64,
    /// URL of the graphic. The service answers only an image there, so no endpoint here fetches it. Null on a few stories: 3 of 252 across every office on 2026-09-30.
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub download: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The office's active weather stories.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct WeatherStoryCollection {
    /// The stories. Empty for an office that has none active.
    pub stories: Vec<WeatherStory>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new(office_id: String) -> Self {
        Self {
            office_id,
            extra: Default::default(),
        }
    }
}

/// The weather stories an office has active: the forecast graphics on the front of its website, each with its text.
#[derive(Clone)]
pub struct ListWeatherStories {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListWeatherStories {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The weather stories an office has active: the forecast graphics on the front of its website, each with its text.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/office_weatherstory>.
    pub async fn list_weather_stories(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<WeatherStoryCollection> {
        let raw = self.list_weather_stories_raw(request, options).await?;
        decode(raw)
    }

    /// `list_weather_stories` without validation: the wire body as it came.
    pub async fn list_weather_stories_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/offices/{office_id}/weatherstories",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
