// Generated by truewire — do not edit by hand.
import { type CallOptions, type Codec, type HttpEndpoint, t } from '@truewire/core'
import type { DefaultMeta } from '../meta.js'
import { PointGeometry, QuantitativeValue } from '../types/index.js'

/** The coordinates to resolve. */
export interface Request {
  /** Latitude in WGS 84 decimal degrees. The service rounds to four decimal places and redirects anything longer, so pass no more precision than that. */
  latitude: number
  /** Longitude in WGS 84 decimal degrees, negative west of the prime meridian. */
  longitude: number
}

export const Request: Codec<Request> = t.object({
  latitude: t.number,
  longitude: t.number,
})

/** Which place, and how far away. */
export interface RelativeLocation {
  /** City name. */
  city: string
  /** Two-letter state code. */
  state: string
  distance?: QuantitativeValue
  bearing?: QuantitativeValue
}

export const RelativeLocation: Codec<RelativeLocation> = t.object({
  city: t.string,
  state: t.string,
  distance: t.optional(QuantitativeValue),
  bearing: t.optional(QuantitativeValue),
})

/** The nearest named place, as its own GeoJSON feature. */
export interface RelativeLocationFeature {
  /** Always `Feature`. */
  type: 'Feature'
  geometry?: PointGeometry
  properties: RelativeLocation
}

export const RelativeLocationFeature: Codec<RelativeLocationFeature> = t.object({
  type: t.literal('Feature'),
  geometry: t.optional(PointGeometry),
  properties: RelativeLocation,
})

/** What the coordinates resolve to. */
export interface Point {
  /** County warning area: the three-letter code of the office responsible, such as `SEW`. Identical to `gridId`. */
  cwa?: string
  /** Forecast office code addressing the grid, such as `SEW`. Pass this as `office` to the `forecast` endpoints. */
  gridId: string
  /** Grid column. Pass this as `grid_x`. */
  gridX: number
  /** Grid row. Pass this as `grid_y`. */
  gridY: number
  /** URL of the responsible office. */
  forecastOffice?: string
  /** URL of the twice-daily forecast for this cell. */
  forecast: string
  /** URL of the hourly forecast for this cell. */
  forecastHourly: string
  /** URL of the raw gridded data both forecasts are rendered from. */
  forecastGridData: string
  /** URL of the stations that observe this cell. */
  observationStations: string
  /** URL of the forecast zone the point is in. */
  forecastZone?: string
  /** URL of the county zone the point is in. */
  county?: string
  /** URL of the fire-weather zone the point is in. */
  fireWeatherZone?: string
  /** IANA time zone of the point, such as `America/Los_Angeles`. Forecast period times are in this zone. */
  timeZone: string
  /** Identifier of the radar covering the point, such as `KATX`. */
  radarStation?: string
  relativeLocation?: RelativeLocationFeature
}

export const Point: Codec<Point> = t.object({
  cwa: t.optional(t.string),
  gridId: t.string,
  gridX: t.integer,
  gridY: t.integer,
  forecastOffice: t.optional(t.string),
  forecast: t.string,
  forecastHourly: t.string,
  forecastGridData: t.string,
  observationStations: t.string,
  forecastZone: t.optional(t.string),
  county: t.optional(t.string),
  fireWeatherZone: t.optional(t.string),
  timeZone: t.string,
  radarStation: t.optional(t.string),
  relativeLocation: t.optional(RelativeLocationFeature),
})

/** Resolve a latitude/longitude to the forecast grid it falls in. Almost every other endpoint here is addressed by grid cell rather than by coordinates, so this is where a caller starts: it returns the office and the grid indices `forecast.get_forecast` takes, plus the zones, the radar station and the nearest city. */
export class GetPoint {
  constructor(readonly core: HttpEndpoint<DefaultMeta>) {}

  /** With `validate: false`: the parsed body as it came, typed `unknown`. */
  getPoint(request: Request, options: CallOptions & { validate: false }): Promise<unknown>
  /**
   * Resolve a latitude/longitude to the forecast grid it falls in. Almost every other endpoint here is addressed by grid cell rather than by coordinates, so this is where a caller starts: it returns the office and the grid indices `forecast.get_forecast` takes, plus the zones, the radar station and the nearest city.
   *
   * @see https://www.weather.gov/documentation/services-web-api#/default/point
   */
  getPoint(request: Request, options?: CallOptions): Promise<Point>
  async getPoint(request: Request, options?: CallOptions): Promise<Point> {
    return this.core.request({
      method: 'GET',
      path: '/points/{latitude},{longitude}',
      request,
      requestCodec: Request,
      responseCodec: Point,
      meta: { payload: 'properties' },
      ...options,
    })
  }
}
