//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::StationFeature;

/// Which station.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`.
    pub station_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// One observation station: where it is, who runs it, and which zones it sits in.
#[derive(Clone)]
pub struct GetStation {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetStation {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// One observation station: where it is, who runs it, and which zones it sits in.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/obs_station>.
    pub async fn get_station(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<StationFeature> {
        let raw = self.get_station_raw(request, options).await?;
        decode(raw)
    }

    /// `get_station` without validation: the wire body as it came.
    pub async fn get_station_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/stations/{station_id}",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
