//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};
use truewire_core::{
    decode, dump, serde_json, CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso,
};

use crate::meta::DefaultMeta;
use crate::types::ObservationFeature;

/// Where the next page is, as a whole URL. The declared walk moves the time window instead and never reads this.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ObservationPagination {
    /// URL of the next page. Absent on the last one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// Which station, over which span.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Station identifier, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`.
    pub station_id: String,
    /// Start of the span, inclusive. The service keeps about a week of observations; a start older than that returns nothing rather than failing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start: Option<TimestampIso>,
    /// End of the span, inclusive.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<TimestampIso>,
    /// Observations per response. Range [1, 500]; the service caps a response at 500 whether or not this is sent, so 500 is also the default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ObservationCollectionType {
    FeatureCollection,
}

/// The observations in the span, as a GeoJSON feature collection, newest first.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ObservationCollection {
    /// Always `FeatureCollection`.
    #[serde(rename = "type")]
    pub type_: ObservationCollectionType,
    /// The observations, newest first.
    pub features: Vec<ObservationFeature>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pagination: Option<ObservationPagination>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// What one station reported over a span of time, newest first. Airport stations report about every twenty minutes, and more often when the weather changes, so a day is a few hundred observations.
#[derive(Clone)]
pub struct GetObservations {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl GetObservations {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// What one station reported over a span of time, newest first. Airport stations report about every twenty minutes, and more often when the weather changes, so a day is a few hundred observations.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/station_observation_list>.
    pub async fn get_observations(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<ObservationCollection> {
        let raw = self.get_observations_raw(request, options).await?;
        decode(raw)
    }

    /// `get_observations` without validation: the wire body as it came.
    pub async fn get_observations_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/stations/{station_id}/observations",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
