//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result};

use crate::meta::DefaultMeta;

use crate::types::StationCollection;

/// Which stations, and how many.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Station identifiers to return, such as `KSEA`. Sent as a repeated query key, one per identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<String>>,
    /// Two-letter state or marine-area codes to narrow to. Sent as a repeated query key.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<Vec<String>>,
    /// Stations per page. Range [1, 500].
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Page cursor. The service does not hand this back on its own -- see the note -- so it is here for a caller who has one, not for a walk the client drives.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new() -> Self {
        Self {
            id: None,
            state: None,
            limit: None,
            cursor: None,
            extra: Default::default(),
        }
    }
}

/// The observation stations the service knows about, optionally narrowed to a state or to named identifiers. Use it to find the station code `stations.get_observations` takes.
#[derive(Clone)]
pub struct ListStations {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListStations {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The observation stations the service knows about, optionally narrowed to a state or to named identifiers. Use it to find the station code `stations.get_observations` takes.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/obs_stations>.
    pub async fn list_stations(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<StationCollection> {
        let raw = self.list_stations_raw(request, options).await?;
        decode(raw)
    }

    /// `list_stations` without validation: the wire body as it came.
    pub async fn list_stations_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/stations",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
