//! Generated by truewire — do not edit by hand.

use std::sync::Arc;

use serde::{Deserialize, Serialize};

use truewire_core::{decode, dump, serde_json};

use truewire_core::{CallOptions, HttpCall, HttpEndpoint, Result, TimestampIso};

use crate::meta::DefaultMeta;

/// Which airport.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct Request {
    /// Station identifier of an airport, such as `KSEA`. `stations.list_stations` returns it as `stationIdentifier`.
    pub station_id: String,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// When one Terminal Aerodrome Forecast was issued, and the span it covers.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TafSummary {
    /// URL of the forecast itself, such as `https://api.weather.gov/stations/KSEA/tafs/2026-09-30/1700`. It answers only in IWXXM XML, which is why no endpoint here fetches it.
    pub id: String,
    /// When the forecast was issued.
    #[serde(rename = "issueTime")]
    pub issue_time: TimestampIso,
    /// Station identifier of the airport, such as `KSEA`.
    pub location: String,
    /// Start of the span the forecast covers.
    pub start: TimestampIso,
    /// End of the span the forecast covers.
    pub end: TimestampIso,
    /// Where the airport is, as Well-Known Text: `POINT(47.44 -122.31)`. Latitude first, the reverse of the GeoJSON `coordinates` elsewhere in this API.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geometry: Option<String>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

/// The forecasts, as a JSON-LD graph.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct TafCollection {
    /// The forecasts, newest first.
    #[serde(rename = "@graph")]
    pub at_graph: Vec<TafSummary>,
    /// Keys the spec does not document, kept as they came.
    #[serde(flatten)]
    pub extra: serde_json::Map<String, serde_json::Value>,
}

impl Request {
    /// Build a request with every required field; optional fields are absent.
    pub fn new(station_id: String) -> Self {
        Self {
            station_id,
            extra: Default::default(),
        }
    }
}

/// The Terminal Aerodrome Forecasts issued for an airport station over roughly the last week, newest first. Only when and for how long each one applies: the forecast text is at each one's `id`, which answers only in XML.
#[derive(Clone)]
pub struct ListTafs {
    core: Arc<dyn HttpEndpoint<DefaultMeta>>,
}

impl ListTafs {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self { core }
    }

    /// The Terminal Aerodrome Forecasts issued for an airport station over roughly the last week, newest first. Only when and for how long each one applies: the forecast text is at each one's `id`, which answers only in XML.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/tafs>.
    pub async fn list_tafs(&self, request: Request, options: CallOptions) -> Result<TafCollection> {
        let raw = self.list_tafs_raw(request, options).await?;
        decode(raw)
    }

    /// `list_tafs` without validation: the wire body as it came.
    pub async fn list_tafs_raw(
        &self,
        request: Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        let meta = DefaultMeta { payload: None };
        let call = HttpCall {
            method: Some("GET"),
            path: "/stations/{station_id}/tafs",
            request: Some(dump(&request)?),
            meta: &meta,
            options,
        };
        self.core.request(call).await
    }
}
