//! Generated by truewire — do not edit by hand.

pub mod get_latest_observation;
pub mod get_observations;
pub mod list_stations;

use std::sync::Arc;

use truewire_core::{serde_json, CallOptions, HttpEndpoint, Result};

use crate::meta::DefaultMeta;
use crate::types::Observation;

/// Observation stations and what they have reported.
///
/// See <https://www.weather.gov/documentation/services-web-api#/default/obs_stations>.
#[derive(Clone)]
pub struct Stations {
    get_latest_observation: get_latest_observation::GetLatestObservation,
    get_observations: get_observations::GetObservations,
    list_stations: list_stations::ListStations,
}

impl Stations {
    pub fn new(core: Arc<dyn HttpEndpoint<DefaultMeta>>) -> Self {
        Self {
            get_latest_observation: get_latest_observation::GetLatestObservation::new(core.clone()),
            get_observations: get_observations::GetObservations::new(core.clone()),
            list_stations: list_stations::ListStations::new(core),
        }
    }

    /// The most recent observation from one station. This is the endpoint behind "what is it doing outside right now".
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/station_observation_latest>.
    pub async fn get_latest_observation(
        &self,
        request: get_latest_observation::Request,
        options: CallOptions,
    ) -> Result<Observation> {
        self.get_latest_observation
            .get_latest_observation(request, options)
            .await
    }

    /// `get_latest_observation` without validation: the wire body as it came.
    pub async fn get_latest_observation_raw(
        &self,
        request: get_latest_observation::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_latest_observation
            .get_latest_observation_raw(request, options)
            .await
    }

    /// What one station reported over a span of time, newest first. Airport stations report about every twenty minutes, and more often when the weather changes, so a day is a few hundred observations.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/station_observation_list>.
    pub async fn get_observations(
        &self,
        request: get_observations::Request,
        options: CallOptions,
    ) -> Result<get_observations::ObservationCollection> {
        self.get_observations
            .get_observations(request, options)
            .await
    }

    /// `get_observations` without validation: the wire body as it came.
    pub async fn get_observations_raw(
        &self,
        request: get_observations::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.get_observations
            .get_observations_raw(request, options)
            .await
    }

    /// The observation stations the service knows about, optionally narrowed to a state or to named identifiers. Use it to find the station code `stations.get_observations` takes.
    ///
    /// See <https://www.weather.gov/documentation/services-web-api#/default/obs_stations>.
    pub async fn list_stations(
        &self,
        request: list_stations::Request,
        options: CallOptions,
    ) -> Result<list_stations::StationCollection> {
        self.list_stations.list_stations(request, options).await
    }

    /// `list_stations` without validation: the wire body as it came.
    pub async fn list_stations_raw(
        &self,
        request: list_stations::Request,
        options: CallOptions,
    ) -> Result<serde_json::Value> {
        self.list_stations.list_stations_raw(request, options).await
    }
}
