# Generated by truewire — do not edit by hand.
from .get_cwa import GetCwa
from .get_cwsu import GetCwsu
from .get_sigmet import GetSigmet
from .list_cwas import ListCwas
from .list_sigmets import ListSigmets
from .list_sigmets_for_atsu import ListSigmetsForAtsu
from .list_sigmets_for_atsu_on_date import ListSigmetsForAtsuOnDate


class Aviation(
  GetCwa, GetCwsu, GetSigmet, ListCwas, ListSigmets, ListSigmetsForAtsu, ListSigmetsForAtsuOnDate
):
  """Aviation weather: the Center Weather Service Units at the FAA's en-route centers and the advisories they issue, and the SIGMETs and AIRMETs that warn aircraft in flight of significant weather.

  References:
    - [Upstream docs](https://www.weather.gov/documentation/services-web-api#/default/sigmetQuery)
  """
