# Generated by truewire — do not edit by hand.
from typing_extensions import Any, Literal, TypedDict, overload
from weather_gov.core import Endpoint
from weather_gov.schemas import SigmetCollection


class Request(TypedDict):
  """Which unit."""

  atsu: str
  """Air traffic services unit, such as `KKCI` (the Aviation Weather Center, which issues the SIGMETs for the contiguous US) or `ANC` (Anchorage). Three or four capital letters."""


class ListSigmetsForAtsu(Endpoint):
  """The SIGMETs and AIRMETs one unit has issued in about the last week, newest first."""

  @overload
  async def list_sigmets_for_atsu(
    self,
    atsu: str,
    *,
    validate: Literal[False],
  ) -> Any: ...
  @overload
  async def list_sigmets_for_atsu(
    self,
    atsu: str,
    *,
    validate: bool | None = None,
  ) -> SigmetCollection: ...
  async def list_sigmets_for_atsu(
    self,
    atsu: str,
    *,
    validate: bool | None = None,
  ) -> SigmetCollection:
    """The SIGMETs and AIRMETs one unit has issued in about the last week, newest first.

    Args:
      atsu: Air traffic services unit, such as `KKCI` (the Aviation Weather Center, which issues the SIGMETs for the contiguous US) or `ANC` (Anchorage). Three or four capital letters.
      validate: Override this call's response validation; falls back to the client-level default when omitted. `False` returns the parsed body as it came, typed `Any`.

    References:
      - [Official docs](https://www.weather.gov/documentation/services-web-api#/default/sigmetsByATSU)
    """
    return await self.request(
      Request(atsu=atsu),
      method='GET',
      path='/aviation/sigmets/{atsu}',
      meta={},
      validate=validate,
      request_type=Request,
      response_type=SigmetCollection,
    )
